const words = [
  { word: "create", meaning: "を創り出す；を引き起こす" },
  { word: "increase", meaning: "増加する（⇔ decrease ⇒ 223）；を増やす" },
  { word: "improve", meaning: "を向上させる；よくなる" },
  { word: "mean", meaning: "を意味する；（...する）つもりである（to do）" },
  { word: "own", meaning: "を所有している；（事実・罪など）を認める" },
  { word: "include", meaning: "を含む（⇔ exclude ⇒ 1009）" },
  { word: "consider", meaning: "を見なす；について考える" },
  { word: "allow", meaning: "を許す；を与える；（～を）考慮に入れる（for）" },
  { word: "suggest", meaning: "を提案する；を暗示する" },
  { word: "produce", meaning: "を生産する；を取り出す" },
  { word: "decide", meaning: "を決める；に決着をつける" },
  { word: "offer", meaning: "を提供する，申し出る" },
  { word: "require", meaning: "を要求する；を必要とする" },
  { word: "share", meaning: "を共有する；を分担する" },
  { word: "store", meaning: "を保存する；を蓄える" },
  { word: "tend", meaning: "傾向がある；を世話する" },
  { word: "concern", meaning: "〔受身形で〕心配している；〔受身形で〕（～に）関係する（with）；に関連する" },
  { word: "describe", meaning: "について述べる，を説明する" },
  { word: "involve", meaning: "を関与させる；を伴う" },
  { word: "reduce", meaning: "を減らす；を（～に）変える（to）" },
  { word: "design", meaning: "を設計する；を計画する" },
  { word: "force", meaning: "に強いる；を強要する" },
  { word: "limit", meaning: "を制限［規制］する" },
  { word: "bear", meaning: "に耐える（≒ endure ⇒ 824）；を負う；を産む；を（心に）抱く" },
  { word: "affect", meaning: "に影響を及ぼす（≒ influence ⇒ 49）；を感動させる" },
  { word: "deal", meaning: "〔deal withで〕を処理する；〔deal inで〕を商う；を分配する" },
  { word: "avoid", meaning: "を避ける" },
  { word: "relate", meaning: "を関連づける；（～に）関連する（to）" },
  { word: "realize", meaning: "に気づく；を実現する" },
  { word: "encourage", meaning: "を奨励する；を励ます（⇔ discourage ⇒ 706）" },
  { word: "compare", meaning: "を比較する；を（～に）たとえる（to）" },
  { word: "measure", meaning: "を測る；を（比較して）評価する" },
  { word: "exist", meaning: "存在する；生存する" },
  { word: "mark", meaning: "に印をつける；を（記号で）示す；に汚れをつける" },
  { word: "challenge", meaning: "に異議を唱える；（人）に挑む" },
  { word: "depend", meaning: "頼る；～次第である" },
  { word: "object", meaning: "反対する；（...）と言って反対する（that節）" },
  { word: "demand", meaning: "を要求する" },
  { word: "found", meaning: "を設立する；（理論など）を（～に基づいて）築く（on）" },
  { word: "complete", meaning: "を完成させる，仕上げる" },
  { word: "idea", meaning: "考え，思いつき；理解；見解；概念" },
  { word: "accord", meaning: "一致；合意，協定" },
  { word: "company", meaning: "会社；〔集合的に〕仲間；（仲間と）一緒にいること；一座" },
  { word: "interest", meaning: "興味；利子；利害" },
  { word: "research", meaning: "（～についての）研究，調査（into / on / in）" },
  { word: "cause", meaning: "原因（⇔ effect ⇒ 48）；理由；大義" },
  { word: "reason", meaning: "理由；（...する）根拠（to do）；理性；分別" },
  { word: "effect", meaning: "影響，効果；結果" },
  { word: "influence", meaning: "影響（力）" },
  { word: "situation", meaning: "状況；（人の置かれた）立場" },
  { word: "environment", meaning: "環境（≒ surroundings）" },
  { word: "skill", meaning: "技能；熟練" },
  { word: "matter", meaning: "事柄；問題；〔～s〕事態；〔the ～〕困難；物質" },
  { word: "view", meaning: "（～についての）見解（on / about）；（～に対する）（特定の）見方（of）；眺め" },
  { word: "value", meaning: "価値；価格；評価；〔～s〕価値観" },
  { word: "species", meaning: "（生物の）種；種類" },
  { word: "thought", meaning: "考え；思考" },
  { word: "knowledge", meaning: "知識；知っていること；認識" },
  { word: "memory", meaning: "記憶（力）；（～の）思い出（of）" },
  { word: "practice", meaning: "実践，実行；（社会の）慣習；練習" },
  { word: "benefit", meaning: "利益，恩恵；給付金" },
  { word: "theory", meaning: "学説；理論；原理；推測" },
  { word: "issue", meaning: "問題（点）；発行（物）；発表" },
  { word: "experiment", meaning: "（～を対象とする）実験（on）" },
  { word: "article", meaning: "記事；条項；品物" },
  { word: "focus", meaning: "焦点；関心の的" },
  { word: "subject", meaning: "話題；科目；主題；被験者" },
  { word: "project", meaning: "計画；事業；研究計画" },
  { word: "quality", meaning: "質（⇔ quantity ⇒ 471）；特質" },
  { word: "role", meaning: "役割；（俳優などの）役" },
  { word: "term", meaning: "（専門）用語；〔～s〕条件；〔～s〕間柄；学期" },
  { word: "statement", meaning: "声明；主張；明細書" },
  { word: "material", meaning: "材料，素材；資料；生地" },
  { word: "evidence", meaning: "証拠" },
  { word: "source", meaning: "（～の）源，根源（of）；出所，情報源" },
  { word: "community", meaning: "（共同）社会，～界；地域社会；地域住民" },
  { word: "technology", meaning: "科学技術；応用技術" },
  { word: "culture", meaning: "文化；教養；耕作；養殖；培養" },
  { word: "appropriate", meaning: "（～に）適切な（for / to）" },
  { word: "likely", meaning: "ありそうな（⇔ unlikely ありそうもない）" },
  { word: "possible", meaning: "可能な；可能性のある" },
  { word: "individual", meaning: "個々の；個人の" },
  { word: "public", meaning: "公の（⇔ private 私的な）；公衆の；公開の" },
  { word: "common", meaning: "共通の；普通の；一般の" },
  { word: "certain", meaning: "確信して；確かな；ある；一定の" },
  { word: "similar", meaning: "似ている，類似した；同様の" },
  { word: "recent", meaning: "最近の" },
  { word: "major", meaning: "主要な；大きい（ほうの）；長調の" },
  { word: "patient", meaning: "忍耐強い；勤勉な" },
  { word: "particular", meaning: "特定の；特別の；（～について）やかましい（about）" },
  { word: "physical", meaning: "身体の（⇔ mental ⇒ 183）；物質的な；物理学の" },
  { word: "various", meaning: "さまざまな；いくつかの" },
  { word: "available", meaning: "手に入る；利用できる；手が空いている" },
  { word: "native", meaning: "出生地の；原産の；生得の" },
  { word: "political", meaning: "政治（上）の" },
  { word: "due", meaning: "予定された；（支払）期日で；しかるべき" },
  { word: "blank", meaning: "空白の；無表情な；がらんとした" },
  { word: "ancient", meaning: "古代の；昔からの" },
  { word: "correct", meaning: "正しい；適切な" },
  { word: "despite", meaning: "～にもかかわらず（≒ in spite of）" },
  { word: "notice", meaning: "に気づく" },
  { word: "refer", meaning: "言及する，関連する；参照する" },
  { word: "approach", meaning: "に近づく；に取り組む" },
  { word: "wonder", meaning: "かなと思う；（に）驚く（at）" },
  { word: "imagine", meaning: "（を）想像する；（を）推測する" },
  { word: "recognize", meaning: "を識別できる；を認める" },
  { word: "solve", meaning: "を解く，解明する；（困難など）を解決する" },
  { word: "occur", meaning: "起こる；心に浮かぶ；現れる" },
  { word: "argue", meaning: "\"と主張する（≒ claim ⇒ 110, maintain ⇒ 206）；議論する\"" },
  { word: "claim", meaning: "と主張する；を（自分のものとして）要求する" },
  { word: "express", meaning: "を表す，述べる" },
  { word: "draw", meaning: "を引き出す；を引く；を描く；近づく" },
  { word: "waste", meaning: "を浪費する，無駄にする" },
  { word: "advance", meaning: "を進歩させる；を進める；進歩する；進む" },
  { word: "spread", meaning: "を広める；広がる" },
  { word: "prepare", meaning: "を準備する；を調理する；（～のために）準備をする（for）" },
  { word: "gain", meaning: "を獲得する；（を）増す" },
  { word: "achieve", meaning: "を達成する；を成し遂げる" },
  { word: "establish", meaning: "を確立する；を設立する" },
  { word: "supply", meaning: "を供給する" },
  { word: "suppose", meaning: "と思う；と仮定する" },
  { word: "perform", meaning: "（を）行う；（を）演じる，（を）演奏する" },
  { word: "prefer", meaning: "のほうを好む" },
  { word: "determine", meaning: "を決定する；を正確に知る" },
  { word: "treat", meaning: "を扱う；を治療する" },
  { word: "prove", meaning: "を証明する；判明する，わかる" },
  { word: "apply", meaning: "を適用［応用］する；申し込む；（～に）適用される（to / in）" },
  { word: "mention", meaning: "に言及する；と言う" },
  { word: "communicate", meaning: "（～と）情報交換をする（with）；を伝達する" },
  { word: "contain", meaning: "を含む；を収容する；（感情など）を抑える" },
  { word: "contact", meaning: "と連絡を取る；接触する" },
  { word: "regard", meaning: "を見なす；を見る；を評価する" },
  { word: "respect", meaning: "を尊敬する；を尊重する" },
  { word: "search", meaning: "捜す；を捜索する；を詳しく調べる" },
  { word: "connect", meaning: "をつなぐ；を関連づける" },
  { word: "decline", meaning: "減少する；衰退する；を断る" },
  { word: "prevent", meaning: "を妨げる；を防ぐ" },
  { word: "suffer", meaning: "苦しむ；患う；（苦痛など）を経験する" },
  { word: "survive", meaning: "を切り抜けて生き残る；より長生きする；生き延びる" },
  { word: "publish", meaning: "を出版する；を公表する" },
  { word: "opportunity", meaning: "機会（≒ chance）" },
  { word: "task", meaning: "（課せられた）仕事，作業；課題；タスク" },
  { word: "industry", meaning: "産業；勤勉（≒ diligence）" },
  { word: "medium", meaning: "（情報伝達の）媒体；手段" },
  { word: "economy", meaning: "経済（状態）；経済圏；節約" },
  { word: "policy", meaning: "政策，方針；（個人の）主義" },
  { word: "account", meaning: "説明；勘定；口座" },
  { word: "trade", meaning: "貿易；商売，取引" },
  { word: "model", meaning: "模範；モデル；模型；型" },
  { word: "figure", meaning: "数字；姿；人物；図表" },
  { word: "cell", meaning: "細胞；独房；電池" },
  { word: "image", meaning: "印象，イメージ；画像；像" },
  { word: "emotion", meaning: "感情，情動；感動" },
  { word: "stress", meaning: "ストレス；圧力；強調" },
  { word: "decade", meaning: "10年間" },
  { word: "range", meaning: "範囲；射程距離；（同類の）組" },
  { word: "character", meaning: "性格，個性；特徴；登場人物；文字" },
  { word: "advantage", meaning: "利点；優勢；有利" },
  { word: "phrase", meaning: "句；成句；言葉遣い" },
  { word: "damage", meaning: "損害，損傷；〔～s〕損害賠償金" },
  { word: "impact", meaning: "影響；（激しい）衝突；衝撃（力）" },
  { word: "method", meaning: "方法；体系；秩序" },
  { word: "resource", meaning: "〔通例～s〕資源；〔通例～s〕資金；才覚" },
  { word: "region", meaning: "地域；領域；部位" },
  { word: "medicine", meaning: "薬；医学" },
  { word: "detail", meaning: "〔～s〕詳細（な情報），細部" },
  { word: "feature", meaning: "特徴；〔通例～s〕顔つき；特集記事［番組］" },
  { word: "function", meaning: "機能；関数" },
  { word: "access", meaning: "利用，入手；接近（の機会・方法・権利）" },
  { word: "item", meaning: "品目，項目；（同種の中の）～個；（短い）記事" },
  { word: "income", meaning: "収入；所得" },
  { word: "attitude", meaning: "態度；考え方，心構え" },
  { word: "site", meaning: "用地，場所；跡地；（ウェブ）サイト" },
  { word: "aspect", meaning: "（物事の）側面；観点；様相" },
  { word: "structure", meaning: "構造；体系；構造物" },
  { word: "habit", meaning: "習慣，癖" },
  { word: "link", meaning: "関連，つながり；（2地点を結ぶ）交通手段；リンク" },
  { word: "instance", meaning: "（具体的な）例，実例；（特定の）場合" },
  { word: "positive", meaning: "肯定的な；積極的な；確信して；（検査結果が）陽性の" },
  { word: "negative", meaning: "否定的な；消極的な；（検査結果が）陰性の" },
  { word: "complex", meaning: "複雑な；複合（体）の" },
  { word: "current", meaning: "現在の；現代の；通用している" },
  { word: "mental", meaning: "精神の；知能の；頭の中で行う" },
  { word: "specific", meaning: "特定の；明確な，具体的な；（～に）特有の（to）" },
  { word: "significant", meaning: "重要な，重大な；意義深い" },
  { word: "essential", meaning: "（～に）必要不可欠な（to / for）；本質的な" },
  { word: "official", meaning: "公用の；公式の；役所の" },
  { word: "financial", meaning: "財政（上）の；財界の" },
  { word: "academic", meaning: "学問の；大学の" },
  { word: "aware", meaning: "気づいて，知って" },
  { word: "worth", meaning: "（...する）に値する（doing）；の価値がある" },
  { word: "potential", meaning: "潜在的な；可能性を秘めた" },
  { word: "active", meaning: "積極的な；活動的な；効力のある" },
  { word: "digital", meaning: "デジタル方式の；デジタル［数字］表示の" },
  { word: "mobile", meaning: "可動［移動］式の；流動性のある" },
  { word: "novel", meaning: "斬新な，目新しい" },
  { word: "plastic", meaning: "柔軟な；プラスチックの，ビニールの" },
  { word: "chemical", meaning: "化学の，化学的な" },
  { word: "necessary", meaning: "必要な（≒ essential ⇒ 186）" },
  { word: "eventually", meaning: "結局（は）" },
  { word: "identify", meaning: "を特定する；を（～と）同一視する（with）" },
  { word: "represent", meaning: "を表す；を代表する；に相当する" },
  { word: "indicate", meaning: "を指し示す；を述べる" },
  { word: "manage", meaning: "をなんとか成し遂げる；を管理する" },
  { word: "attend", meaning: "に出席する；（を）世話する；（～に）対処［対応］する（to）" },
  { word: "maintain", meaning: "を維持する；と主張する；を養う" },
  { word: "survey", meaning: "を調査する；をじろじろ見る；を概観する" },
  { word: "replace", meaning: "に取って代わる；を取り替える" },
  { word: "sort", meaning: "を（～に）分類する（into）；を（～から）えり分ける（from）" },
  { word: "conduct", meaning: "（調査・実験など）を実施する；を導く" },
  { word: "associate", meaning: "を結び付けて考える；（～と）交際する（with）" },
  { word: "attempt", meaning: "を試みる，企てる" },
  { word: "promote", meaning: "を促進する；〔通例受身形で〕昇進する" },
  { word: "earn", meaning: "を稼ぐ；を得る；をもたらす" },
  { word: "unite", meaning: "を団結させる；（を）結合する；団結する" },
  { word: "feed", meaning: "に食べ物［乳］を与える；に（～を）供給［補給］する（with）；餌を食べる" },
  { word: "seek", meaning: "を追い求める；（助けなど）を要請する" },
  { word: "observe", meaning: "に気づく；を観察する；を遵守する" },
  { word: "reveal", meaning: "を明らかにする；を見せる" },
  { word: "estimate", meaning: "と推定する；を見積もる；を評価する" },
  { word: "reflect", meaning: "を反映する；（を）反射する；（を）熟考する" },
  { word: "attract", meaning: "を引きつける" },
  { word: "decrease", meaning: "減少する（⇔ increase ⇒ 2）；を減らす" },
  { word: "ignore", meaning: "を無視する" },
  { word: "match", meaning: "（と）合う；に匹敵する；一致する" },
  { word: "define", meaning: "を定義する；を明確にする" },
  { word: "adapt", meaning: "適応する；を（～に）適合させる（to）" },
  { word: "contribute", meaning: "貢献する，一因となる；（を）寄付する；（を）寄稿する" },
  { word: "exchange", meaning: "（を）交換する；両替する" },
  { word: "display", meaning: "を示す；を発揮する；を展示［陳列］する" },
  { word: "respond", meaning: "反応する；答える" },
  { word: "hide", meaning: "を隠す（≒ conceal ⇒ 1116）；隠れる" },
  { word: "doubt", meaning: "ではないと思う；を疑う" },
  { word: "remove", meaning: "を取り除く；を解雇する" },
  { word: "wind", meaning: "（ねじなど）を巻く；（道などが）曲がりくねる；巻きつく" },
  { word: "assume", meaning: "を当然のことと思う，と仮定する；（権力など）を手に入れる；（責任など）を引き受ける" },
  { word: "relax", meaning: "くつろぐ；緩む；をくつろがせる；を緩める" },
  { word: "satisfy", meaning: "を満足させる；（条件など）を満たす" },
  { word: "desire", meaning: "を強く望む" },
  { word: "succeed", meaning: "（～に）成功する（in）；（～を）継承する（to）" },
  { word: "concept", meaning: "概念；考え；（商品・販売の）コンセプト" },
  { word: "fashion", meaning: "流行，ファッション；方法，流儀" },
  { word: "device", meaning: "装置，機器；方策；デバイス" },
  { word: "charge", meaning: "料金；世話；管理；告発" },
  { word: "contrast", meaning: "（～との）対照（with / to）" },
  { word: "colleague", meaning: "（職場の）同僚" },
  { word: "pain", meaning: "苦痛，痛み；苦悩；〔～s〕骨折り" },
  { word: "bill", meaning: "請求書；【英】勘定書（≒ 【米】check）；法案" },
  { word: "content", meaning: "内容，中身；コンテンツ" },
  { word: "section", meaning: "部門；部分；地区；欄" },
  { word: "audience", meaning: "〔集合的に〕聴衆，観客；視聴者" },
  { word: "surface", meaning: "表面；〔the ～〕外見" },
  { word: "crop", meaning: "〔しばしば～s〕作物；収穫高" },
  { word: "topic", meaning: "話題，トピック；主題" },
  { word: "technique", meaning: "技術；技巧；手法" },
  { word: "status", meaning: "地位；状態" },
  { word: "option", meaning: "選択（の自由）；選択肢" },
  { word: "reward", meaning: "報酬；報い" },
  { word: "race", meaning: "人種；民族；競争" },
  { word: "crime", meaning: "罪，犯罪；違法行為" },
  { word: "conflict", meaning: "争い；論争；不一致" },
  { word: "struggle", meaning: "闘い；懸命の努力" },
  { word: "context", meaning: "状況，背景；文脈" },
  { word: "debate", meaning: "討論，論争；討論会" },
  { word: "fuel", meaning: "燃料；勢いを増加させるもの" },
  { word: "pollution", meaning: "汚染，公害" },
  { word: "trend", meaning: "（～への）傾向（toward）；流行" },
  { word: "balance", meaning: "均衡，バランス；（体の）平衡；残高" },
  { word: "traffic", meaning: "交通；通行；交通［輸送］量；（不正）取引" },
  { word: "strategy", meaning: "戦略" },
  { word: "basis", meaning: "基礎；根拠；基準" },
  { word: "consequence", meaning: "〔通例～s〕結果；重大性" },
  { word: "aim", meaning: "目的，目標；狙い" },
  { word: "ancestor", meaning: "祖先（⇔ descendant 子孫）；原型" },
  { word: "gene", meaning: "遺伝子" },
  { word: "track", meaning: "跡；軌道；【米】（鉄道の）番線；走路" },
  { word: "revolution", meaning: "革命；回転；（天体の）公転（⇔ rotation 自転）" },
  { word: "progress", meaning: "進歩；前進" },
  { word: "cognitive", meaning: "認知の" },
  { word: "ideal", meaning: "理想的な；観念的な" },
  { word: "efficient", meaning: "効率的な；有能な" },
  { word: "universal", meaning: "普遍的な；宇宙の；万能の" },
  { word: "vast", meaning: "莫大な；広大な" },
  { word: "extra", meaning: "追加の，余分の；別勘定の" },
  { word: "entire", meaning: "全体の，全部の（≒ whole）；完全な" },
  { word: "familiar", meaning: "精通している；よく知られている" },
  { word: "obvious", meaning: "明らかな（≒ clear）" },
  { word: "moral", meaning: "道徳（上）の，倫理的な；道徳的な" },
  { word: "ordinary", meaning: "一般の，普通の；並の" },
  { word: "equal", meaning: "（～に）等しい（to）；匹敵する；平等な" },
  { word: "previous", meaning: "以前の，前の" },
  { word: "FALSE", meaning: "間違った；虚偽の；偽の" },
  { word: "rare", meaning: "まれな，珍しい；希少な" },
  { word: "legal", meaning: "法律の；合法の（⇔ illegal 違法の）" },
  { word: "independent", meaning: "（～から）独立した（of / from）" },
  { word: "extreme", meaning: "極端な；極度の，過激な" },
  { word: "actual", meaning: "実際の，現実の" },
  { word: "willing", meaning: "いとわない，かまわないと思う" },
  { word: "urban", meaning: "都市の；都会的な（⇔ rural ⇒ 387）" },
  { word: "whereas", meaning: "～するのに（対し），～する一方" },
  { word: "predict", meaning: "を予言［予測］する" },
  { word: "examine", meaning: "を調べる；を診察する；を尋問する" },
  { word: "trust", meaning: "を信頼する；を（信頼して）託す" },
  { word: "stick", meaning: "を動けなくする；を突き刺す；（～に）くっつく（to / on）" },
  { word: "emerge", meaning: "現れる；明らかになる；台頭する" },
  { word: "vary", meaning: "さまざまである；変わる；を変える" },
  { word: "release", meaning: "を放出する；を解放する；を発表する" },
  { word: "divide", meaning: "を分ける；分かれる" },
  { word: "enable", meaning: "（人）が...できるようにする；を可能にする" },
  { word: "judge", meaning: "（を）判断する；に判決を下す" },
  { word: "rely", meaning: "頼る（≒ depend ⇒ 36）" },
  { word: "engage", meaning: "を従事させる；を（～として）雇う（as）；（～に）従事する（in / with）" },
  { word: "shift", meaning: "を変える，移す；変わる；移動する" },
  { word: "adopt", meaning: "を採用する；（態度など）をとる；を養子にする" },
  { word: "acquire", meaning: "を得る；を習得する" },
  { word: "expand", meaning: "（を）拡大する；（を）詳説する" },
  { word: "refuse", meaning: "を拒む；を断る；拒絶する" },
  { word: "strike", meaning: "の心を打つ；を襲う；を打つ；（に）ぶつかる" },
  { word: "repeat", meaning: "（を）繰り返す；を復唱する" },
  { word: "consume", meaning: "を消費する；を食べる，飲む" },
  { word: "confuse", meaning: "を混同する；を当惑させる" },
  { word: "select", meaning: "を選ぶ，えり抜く" },
  { word: "evolve", meaning: "（徐々に）発展する；進化する" },
  { word: "convince", meaning: "を納得［確信］させる" },
  { word: "recall", meaning: "を思い出す；を呼び戻す" },
  { word: "destroy", meaning: "を破壊する；（人）を破滅させる" },
  { word: "preserve", meaning: "を保存する；を保持する；を保護する" },
  { word: "organize", meaning: "を準備する；を組織する" },
  { word: "warn", meaning: "（人）に（～を）警告［注意］する（of / against）" },
  { word: "address", meaning: "（問題など）に対処する；に演説する；（手紙など）を（～宛てに）出す（to）" },
  { word: "operate", meaning: "を操作する；機能する；手術する" },
  { word: "participate", meaning: "参加する" },
  { word: "surround", meaning: "を取り巻く；にまつわる" },
  { word: "flow", meaning: "流れる；（～から）生じる（from）" },
  { word: "bore", meaning: "（人）を退屈させる，うんざりさせる" },
  { word: "complain", meaning: "（と）不平［苦情］を言う；訴える" },
  { word: "host", meaning: "を主催する；のホスト役を務める" },
  { word: "combine", meaning: "を（～と）結び付ける（with）；（～と）結び付く（with）" },
  { word: "extend", meaning: "を伸［延］ばす；伸びる；及ぶ" },
  { word: "appreciate", meaning: "を正当に評価する；を鑑賞する；を感謝する" },
  { word: "target", meaning: "（到達・攻撃）目標；的" },
  { word: "element", meaning: "要素，成分；元素；〔an / ofで〕少しの" },
  { word: "principle", meaning: "原則，原理；主義，信条" },
  { word: "phenomenon", meaning: "現象" },
  { word: "atmosphere", meaning: "〔the ～〕大気；雰囲気" },
  { word: "origin", meaning: "起源；源" },
  { word: "personality", meaning: "個性，性格" },
  { word: "capacity", meaning: "（最大）容量，収容能力；（潜在）能力" },
  { word: "profit", meaning: "利益；収益（率）；得" },
  { word: "circumstance", meaning: "〔通例～s〕状況，事情；境遇" },
  { word: "manner", meaning: "〔～s〕作法；方法；物腰" },
  { word: "threat", meaning: "脅威；（悪い）兆し；脅迫" },
  { word: "resident", meaning: "居住者；滞在者" },
  { word: "wealth", meaning: "富；資源；富裕" },
  { word: "institution", meaning: "機関；協会；施設；制度" },
  { word: "authority", meaning: "〔通例 the ～ties〕（関係）当局；権威；権限" },
  { word: "vote", meaning: "投票；投票結果；〔the ～〕選挙権" },
  { word: "sight", meaning: "光景；〔the ～s〕名所；見（え）ること；視野；視力" },
  { word: "campaign", meaning: "運動；軍事行動" },
  { word: "fund", meaning: "〔しばしば～s〕基金，資金" },
  { word: "web", meaning: "〔the W-〕ウェブ；（クモの）巣" },
  { word: "symbol", meaning: "象徴，シンボル；記号；標章" },
  { word: "analysis", meaning: "分析（結果）（⇔ synthesis ⇒ 1868）" },
  { word: "version", meaning: "（本・製品などの）版；解釈" },
  { word: "perspective", meaning: "観点，見方；大局観；遠近法" },
  { word: "crisis", meaning: "危機" },
  { word: "disaster", meaning: "災害；惨事" },
  { word: "lecture", meaning: "講義，講演；説教" },
  { word: "psychology", meaning: "心理学；心理（状態）" },
  { word: "gender", meaning: "（社会的・文化的）性，性別" },
  { word: "custom", meaning: "（社会的な）慣習；〔～s〕税関；〔～s〕関税" },
  { word: "court", meaning: "裁判所，法廷；裁判；宮廷；中庭" },
  { word: "desert", meaning: "砂漠；不毛の地" },
  { word: "soil", meaning: "土地，土壌；（悪事などの）温床" },
  { word: "agriculture", meaning: "農業；農学，畜産" },
  { word: "fossil", meaning: "化石；時代遅れの人［物］" },
  { word: "document", meaning: "（公）文書，書類；記録，資料" },
  { word: "vocabulary", meaning: "語彙" },
  { word: "intelligent", meaning: "聡明な；知能を有する" },
  { word: "conscious", meaning: "意識して，気づいて（≒ aware）" },
  { word: "capable", meaning: "能力がある；有能な" },
  { word: "accurate", meaning: "正確な；精密な" },
  { word: "fundamental", meaning: "基本的な；必須の" },
  { word: "artificial", meaning: "人工の（⇔ natural 自然の）；不自然な" },
  { word: "firm", meaning: "確固たる；堅固な；安定した" },
  { word: "overall", meaning: "総合的な；全体的な" },
  { word: "rural", meaning: "田舎の（⇔ urban ⇒ 299），田園の" },
  { word: "military", meaning: "軍の，軍事（用）の" },
  { word: "nuclear", meaning: "核の，原子力の" },
  { word: "biological", meaning: "生物学（上）の" },
  { word: "constant", meaning: "絶え間ない；一定の" },
  { word: "severe", meaning: "（人・規律・事態・天気などが）厳しい；猛烈な" },
  { word: "visual", meaning: "視覚の；目に見える" },
  { word: "enormous", meaning: "莫大な，巨大な" },
  { word: "convenient", meaning: "便利な，都合のいい" },
  { word: "domestic", meaning: "家庭の；国内の；（動物が）飼いならされた" },
  { word: "mass", meaning: "大規模な，大量の；大衆（向け）の" },
  { word: "typical", meaning: "典型的な；（～に）特有の（of）" },
  { word: "overseas", meaning: "海外へ［に，で］（≒ abroad）" },
  { word: "nevertheless", meaning: "それにもかかわらず（≒ nonetheless ⇒ 1000）" },
  { word: "demonstrate", meaning: "を論証［証明］する；デモをする" },
  { word: "behave", meaning: "振る舞う；作動する" },
  { word: "educate", meaning: "を教育する；に教える；（能力など）を養う" },
  { word: "purchase", meaning: "を購入する" },
  { word: "recommend", meaning: "を勧める" },
  { word: "admit", meaning: "（を）（しぶしぶ）認める；に（～への）入場［入学など］を認める（to / into）" },
  { word: "generate", meaning: "を生み出す；（電気など）を発生させる" },
  { word: "explore", meaning: "（を）調査［探究］する；（を）探検［探査］する" },
  { word: "amaze", meaning: "をびっくりさせる" },
  { word: "tear", meaning: "を引き裂く；裂ける" },
  { word: "settle", meaning: "を解決する；（に）移り住む；を落ち着かせる" },
  { word: "afford", meaning: "を持つ［する］余裕がある；を与える" },
  { word: "conclude", meaning: "と結論づける；を締めくくる；を締結する" },
  { word: "advertise", meaning: "を宣伝する；（～を求める）広告を出す（for）" },
  { word: "encounter", meaning: "に遭遇する；に（思いがけず）出会う" },
  { word: "remind", meaning: "に思い出させる" },
  { word: "locate", meaning: "〔受身形で〕位置する；の位置を探し当てる" },
  { word: "aid", meaning: "を援助する，助ける（≒ help）" },
  { word: "bite", meaning: "（を）かむ，（に）かみつく；（を）刺す" },
  { word: "deliver", meaning: "を配達する；（演説・講義）をする；子を産む" },
  { word: "perceive", meaning: "に気づく；を知覚する；を理解する" },
  { word: "distinguish", meaning: "を区別する" },
  { word: "imply", meaning: "を暗に意味する；を必然的に伴う" },
  { word: "handle", meaning: "を処理する，扱う；を論じる；を商う" },
  { word: "praise", meaning: "を（～のことで）賞賛する（for）；賛美する" },
  { word: "appeal", meaning: "訴える；抗議する；（上級審に）上訴する" },
  { word: "insist", meaning: "（を）強く主張する；要求する" },
  { word: "compete", meaning: "競う；〔通例否定文で〕（～に）匹敵する（with）" },
  { word: "rank", meaning: "を位置づける，評価する；（ある地位に）位置する" },
  { word: "deny", meaning: "を否定する；を拒む" },
  { word: "reject", meaning: "を拒否する" },
  { word: "intend", meaning: "を意図する" },
  { word: "expose", meaning: "をさらす；を暴露する；を露出する" },
  { word: "favor", meaning: "に賛成する；を好む；をひいきする" },
  { word: "inspire", meaning: "（人）を奮起させる；を喚起する" },
  { word: "propose", meaning: "を提案する；をもくろむ；結婚を申し込む" },
  { word: "spell", meaning: "（語）をつづる；という語になる" },
  { word: "breathe", meaning: "呼吸する；を吸う" },
  { word: "repair", meaning: "を修理する（≒ fix）；を修復する" },
  { word: "consist", meaning: "（～から）成る（of）；（～に）ある（in）" },
  { word: "comment", meaning: "意見，コメント；批判" },
  { word: "instruction", meaning: "〔通例～s〕指示；〔～s〕（製品の）使用書" },
  { word: "religion", meaning: "宗教；信条；信仰（心）" },
  { word: "neighborhood", meaning: "地域；近所" },
  { word: "laboratory", meaning: "実験室，研究室" },
  { word: "presence", meaning: "存在；出席；面前" },
  { word: "confidence", meaning: "自信；信頼；秘密" },
  { word: "harm", meaning: "害，損害" },
  { word: "instrument", meaning: "器具；楽器（≒ musical instrument）" },
  { word: "category", meaning: "部類，区分；範疇" },
  { word: "capital", meaning: "資本；首都；大文字（≒ capital letter）" },
  { word: "outcome", meaning: "結果（≒ result）；成果" },
  { word: "notion", meaning: "概念，観念；見解；意向" },
  { word: "review", meaning: "（書物などの）論評；再調査；【米】復習" },
  { word: "trait", meaning: "特性（≒ feature）" },
  { word: "diversity", meaning: "多様性；相違点" },
  { word: "victim", meaning: "犠牲（者），被害者" },
  { word: "occasion", meaning: "場合，時；行事；機会" },
  { word: "facility", meaning: "施設，設備；機能；才能" },
  { word: "stock", meaning: "在庫品；蓄え；株" },
  { word: "conference", meaning: "会議；協議" },
  { word: "humanity", meaning: "人類；人間性；人情；〔（the） ～ties〕人文科学" },
  { word: "dialect", meaning: "方言" },
  { word: "proportion", meaning: "割合；部分；釣り合い" },
  { word: "tip", meaning: "助言，秘訣；チップ；先端" },
  { word: "lawyer", meaning: "弁護士" },
  { word: "stuff", meaning: "（漠然と）物；素材；素質" },
  { word: "comfort", meaning: "快適さ；慰め" },
  { word: "philosophy", meaning: "哲学；原理；人生観" },
  { word: "mammal", meaning: "哺乳動物" },
  { word: "quantity", meaning: "量（⇔ quality ⇒ 69）；分量" },
  { word: "landscape", meaning: "風景；領域；状況" },
  { word: "tribe", meaning: "部族；仲間" },
  { word: "organ", meaning: "器官，臓器；組織；（パイプ）オルガン" },
  { word: "trial", meaning: "試み，（品質・性能などの）試験；裁判；試用期間" },
  { word: "norm", meaning: "規範；標準" },
  { word: "code", meaning: "規範；暗号；法典" },
  { word: "substance", meaning: "物質；実体；趣旨" },
  { word: "multiple", meaning: "多様な；種々雑多な" },
  { word: "numerous", meaning: "非常に数の多い" },
  { word: "narrow", meaning: "狭い；細い；限られた" },
  { word: "widespread", meaning: "広範囲にわたる；広く普及した" },
  { word: "sufficient", meaning: "（～に；...するのに）十分な（for；to do）" },
  { word: "proper", meaning: "適切な；正式の；〔名詞の後ろで〕主要な；（～に）固有の（to）" },
  { word: "linguistic", meaning: "言語の，言語学の" },
  { word: "annual", meaning: "年1回の，例年の；1年間の" },
  { word: "contemporary", meaning: "現代の；同時代の；同年輩の" },
  { word: "contrary", meaning: "（～と）反対の（to）" },
  { word: "strict", meaning: "（規則などが）厳しい；厳格な" },
  { word: "civil", meaning: "市民の；民間の；民事の（⇔ criminal 刑事の）" },
  { word: "odd", meaning: "奇妙な（≒ strange）；奇数の" },
  { word: "unknown", meaning: "不明の；（～に）知られていない（to），無名の" },
  { word: "superior", meaning: "よりすぐれた（⇔ inferior ⇒ 1092）" },
  { word: "sensitive", meaning: "敏感な；神経質な；微妙な" },
  { word: "violent", meaning: "（人・気質などが）激しい；暴力的な" },
  { word: "virtual", meaning: "仮想の；事実上の" },
  { word: "regardless", meaning: "（～に）かまわない，無頓着な（of）" },
  { word: "immediate", meaning: "即座の；当面の；すぐそばの；直接の" },
  { word: "crucial", meaning: "重要な" },
  { word: "somewhat", meaning: "いくぶん，多少" },
  { word: "interpret", meaning: "を解釈する；（を）通訳する" },
  { word: "translate", meaning: "を翻訳する；を（～に）変える（into）" },
  { word: "concentrate", meaning: "（を）集中する" },
  { word: "request", meaning: "に（...するように）頼む（to do）；を要請する" },
  { word: "criticize", meaning: "を批判する；を批評する" },
  { word: "overcome", meaning: "を克服する" },
  { word: "obtain", meaning: "を得る" },
  { word: "inform", meaning: "に知らせる；情報を提供する" },
  { word: "ensure", meaning: "を確実にする（≒ make sure）；を守る" },
  { word: "announce", meaning: "を発表［公表］する，知らせる；（物事が）を告げる" },
  { word: "grant", meaning: "（人）に（許可・権利など）を与える；を認める" },
  { word: "freeze", meaning: "凍る；を凍らせる；（計画・資金など）を凍結する" },
  { word: "oppose", meaning: "に反対する；を対抗［対比］させる" },
  { word: "differ", meaning: "異なる" },
  { word: "hate", meaning: "をひどく嫌う；を残念に思う" },
  { word: "emphasize", meaning: "を強調する；を重視する" },
  { word: "employ", meaning: "を雇う（≒ give ～ a job）；を使う（≒ use）" },
  { word: "credit", meaning: "（功績など）を（～に）帰する（to）；を信じる" },
  { word: "transform", meaning: "を変える；変わる" },
  { word: "construct", meaning: "を建設する（＝ build）；を構成する" },
  { word: "arise", meaning: "生じる" },
  { word: "beat", meaning: "を打ち負かす；（を）打つ，たたく" },
  { word: "regret", meaning: "を後悔する" },
  { word: "alter", meaning: "を変える；変わる（≒ change）" },
  { word: "absorb", meaning: "を吸収する；を併合する；を夢中にさせる" },
  { word: "disappoint", meaning: "を失望させる；（希望など）をくじく" },
  { word: "cure", meaning: "を治す；を取り除く；（病気が）治る" },
  { word: "transport", meaning: "を輸送する；を運ぶ" },
  { word: "rush", meaning: "急いで行く；性急に行動する；をせき立てる" },
  { word: "hang", meaning: "を掛ける；を絞首刑にする；垂れ（下が）る" },
  { word: "blame", meaning: "を責める；の責任を負わせる" },
  { word: "ban", meaning: "を（法的に）禁止する；を締め出す" },
  { word: "fascinate", meaning: "を魅了する" },
  { word: "recover", meaning: "回復する；を取り戻す" },
  { word: "celebrate", meaning: "を祝う；を挙行する" },
  { word: "manufacture", meaning: "を製造する；をでっち上げる" },
  { word: "interact", meaning: "影響し合う；相互に作用する" },
  { word: "arrange", meaning: "の段取りをつける；を手配する；を配置する" },
  { word: "adjust", meaning: "を調整する；を適合させる；順応する" },
  { word: "confirm", meaning: "を確認する；を裏づける" },
  { word: "insight", meaning: "見識，理解（力）；洞察力" },
  { word: "innovation", meaning: "革新；新機軸" },
  { word: "budget", meaning: "予算；経費" },
  { word: "fee", meaning: "料金；謝礼" },
  { word: "expense", meaning: "〔～s〕経費；費用；犠牲" },
  { word: "debt", meaning: "借金，負債；恩義" },
  { word: "loan", meaning: "貸付金，融資；貸すこと" },
  { word: "duty", meaning: "義務；〔しばしば～ties〕職務；関税" },
  { word: "alarm", meaning: "不安，恐れ；警報装置" },
  { word: "emergency", meaning: "緊急（事態）" },
  { word: "democracy", meaning: "民主主義，民主政治；民主国家" },
  { word: "minister", meaning: "大臣；（プロテスタント系の）聖職者" },
  { word: "fellow", meaning: "仲間，同僚；同級生；男" },
  { word: "candidate", meaning: "（～の）候補（者）（for）；志願者" },
  { word: "corporation", meaning: "（大）企業；法人" },
  { word: "stereotype", meaning: "固定観念；決まり文句" },
  { word: "route", meaning: "道（筋）；路線，ルート；（～の）手段（to）" },
  { word: "disorder", meaning: "障害，（心身の）不調；混乱" },
  { word: "depression", meaning: "憂うつ；うつ病；不況；低気圧" },
  { word: "weapon", meaning: "兵器，武器（≒ arms）" },
  { word: "immigration", meaning: "（他国からの）移民，移住；入国管理" },
  { word: "barrier", meaning: "（～に対する）障壁（against / to）；防壁" },
  { word: "disadvantage", meaning: "不利（な点）；障害；（信用などの）損失" },
  { word: "mood", meaning: "気分；機嫌；雰囲気" },
  { word: "motion", meaning: "動き，動作；運動；動議" },
  { word: "routine", meaning: "決まり切った仕事；いつもの手順" },
  { word: "discipline", meaning: "規律，しつけ；訓練；懲戒；学問分野" },
  { word: "myth", meaning: "作り話；神話" },
  { word: "hypothesis", meaning: "仮説；憶測" },
  { word: "physician", meaning: "【主に米】 医師（≒ doctor）；内科医" },
  { word: "client", meaning: "顧客（≒ customer）；（弁護士などの）依頼人" },
  { word: "colony", meaning: "植民地；集団居住地；（動植物の）コロニー" },
  { word: "statistics", meaning: "統計；統計学" },
  { word: "grain", meaning: "穀物；粒；きめ" },
  { word: "ingredient", meaning: "材料，成分；（成功の）要因" },
  { word: "treasure", meaning: "宝物，財宝；財産" },
  { word: "contract", meaning: "契約（書）；協定" },
  { word: "welfare", meaning: "福祉，幸福" },
  { word: "prime", meaning: "主要な，最も重要な；最適な；極上の" },
  { word: "curious", meaning: "好奇心の強い；奇妙な" },
  { word: "dramatic", meaning: "劇的な；演劇の" },
  { word: "distinct", meaning: "明らかに異なる；明瞭な" },
  { word: "anxious", meaning: "心配して；切望して" },
  { word: "vital", meaning: "必要不可欠な；活気のある；生命にかかわる" },
  { word: "conventional", meaning: "従来の；月並みな" },
  { word: "abstract", meaning: "抽象的な（⇔ concrete ⇒ 783）" },
  { word: "minor", meaning: "重要でない；小さい（⇔ major ⇒ 88）" },
  { word: "extraordinary", meaning: "並はずれた；異常な，驚くべき" },
  { word: "stable", meaning: "安定した（⇔ unstable 不安定な）；動じない" },
  { word: "flexible", meaning: "融通の利く，柔軟な" },
  { word: "brief", meaning: "簡潔な；短い" },
  { word: "aggressive", meaning: "攻撃的な；意欲的な" },
  { word: "visible", meaning: "（目に）見える（⇔ invisible 見えない）；明白な" },
  { word: "unexpected", meaning: "思いがけない，不意の" },
  { word: "ethnic", meaning: "民族の，人種の；民族特有の" },
  { word: "alien", meaning: "（～にとって）異質の（to）；外国の；宇宙人の" },
  { word: "initial", meaning: "初めの" },
  { word: "exact", meaning: "正確な；まさにその" },
  { word: "precise", meaning: "正確な（≒ exact）；精密な；まさにその" },
  { word: "latter", meaning: "後者の（⇔ former 前者の），後半の" },
  { word: "commit", meaning: "〔commit oneselfまたは受身形で〕献身する；（罪など）を犯す；を投入する" },
  { word: "stimulate", meaning: "を刺激する" },
  { word: "enhance", meaning: "（価値など）を高める，増す" },
  { word: "pursue", meaning: "を追求する；に従事する" },
  { word: "react", meaning: "反応する；化学反応を起こす" },
  { word: "disagree", meaning: "不賛成である；意見が食い違う" },
  { word: "stare", meaning: "じっと見る；を見つめる" },
  { word: "abandon", meaning: "を捨てる；を放棄する，断念する" },
  { word: "quit", meaning: "をやめる；（場所）を去る" },
  { word: "capture", meaning: "をとらえる；をとりこにする" },
  { word: "transfer", meaning: "を移す；を伝える；移る；乗り換える" },
  { word: "bother", meaning: "を悩ます；（～を）気にかける（about / with）" },
  { word: "persuade", meaning: "を説得する；に確信させる" },
  { word: "rent", meaning: "を賃借りする；を賃貸しする" },
  { word: "breed", meaning: "を繁殖させる，育てる；繁殖する" },
  { word: "invest", meaning: "（を）投資する；に（～を）与える（with）" },
  { word: "reserve", meaning: "を予約する；を取っておく；（判断など）を保留する" },
  { word: "trace", meaning: "（足跡・起源など）をたどる；を捜し出す" },
  { word: "illustrate", meaning: "を説明する；に挿絵を入れる" },
  { word: "advise", meaning: "に忠告［助言］する；（を）助言する" },
  { word: "convey", meaning: "を伝える；を運ぶ，運搬する" },
  { word: "attach", meaning: "を（取り）付ける；を付与する" },
  { word: "stretch", meaning: "を伸ばす；を広げる；伸びる；及ぶ" },
  { word: "puzzle", meaning: "を当惑させる" },
  { word: "disturb", meaning: "をかき乱す；を妨害する；を動揺させる" },
  { word: "crash", meaning: "衝突する，墜落する；をぶつけて壊す" },
  { word: "cope", meaning: "うまく処理する" },
  { word: "permit", meaning: "を許可する（≒ allow）（⇔ forbid ⇒ 1013）" },
  { word: "impress", meaning: "を感動させる；に印象を与える" },
  { word: "suspect", meaning: "ではないかと思う；（人）を疑う" },
  { word: "upset", meaning: "を動揺させる；をだめにする" },
  { word: "frighten", meaning: "（人）を怖がらせる" },
  { word: "import", meaning: "を輸入する（⇔ export （を）輸出する）；を取り込む" },
  { word: "export", meaning: "（を）輸出する（⇔ import を輸入する）" },
  { word: "investigate", meaning: "を調査する；を究明する；（～を）調査する（into）" },
  { word: "monitor", meaning: "を監視する；を傍受する" },
  { word: "calculate", meaning: "を計算する；を予測する" },
  { word: "eliminate", meaning: "を取り除く" },
  { word: "ease", meaning: "を軽減する；和らぐ；緩む" },
  { word: "launch", meaning: "を開始する；を売り出す；を発射する" },
  { word: "sequence", meaning: "連続；一連（のもの）" },
  { word: "therapy", meaning: "療法；心理療法" },
  { word: "symptom", meaning: "症状；兆候（≒ sign）" },
  { word: "incident", meaning: "出来事，事件；紛争" },
  { word: "witness", meaning: "目撃者（≒ eyewitness）；証人；証拠，証言" },
  { word: "sum", meaning: "（金）額；合計；要点" },
  { word: "burden", meaning: "負担；（重い）義務；積み荷" },
  { word: "tone", meaning: "口調；音色；雰囲気；色調" },
  { word: "honor", meaning: "光栄；名誉（⇔ dishonor 不名誉）；敬意" },
  { word: "award", meaning: "（～の）賞（for）；（証書などの）授与" },
  { word: "priority", meaning: "優先（事項）" },
  { word: "logic", meaning: "論理；道理；論理学" },
  { word: "minimum", meaning: "最小限度（⇔ maximum ⇒ 965）" },
  { word: "exception", meaning: "（～の）例外（to）" },
  { word: "clue", meaning: "（～の）手がかり（to / about）；（パズルの）ヒント" },
  { word: "bond", meaning: "絆；債券；束縛；接着剤" },
  { word: "virus", meaning: "ウイルス；（感染症の）病原体" },
  { word: "surgery", meaning: "（外科）手術；外科，外科医学" },
  { word: "insurance", meaning: "保険；保険料；保険金" },
  { word: "frame", meaning: "枠，（額）縁；骨組み；体格" },
  { word: "shelter", meaning: "避難（所），保護" },
  { word: "territory", meaning: "領土；（活動の）領域；（動物の）テリトリー" },
  { word: "boundary", meaning: "境界（線）；〔通例～ries〕限界" },
  { word: "habitat", meaning: "生息地；（人の）居住地" },
  { word: "district", meaning: "地区；行政区" },
  { word: "conservation", meaning: "（動植物などの）保護；保存" },
  { word: "harvest", meaning: "収穫（物）；収穫期；漁獲高" },
  { word: "predator", meaning: "捕食動物；略奪者" },
  { word: "trap", meaning: "わな；苦境" },
  { word: "trick", meaning: "こつ；策略；いたずら；芸当" },
  { word: "fault", meaning: "〔通例one's ～〕責任；欠点；誤り" },
  { word: "discount", meaning: "割引" },
  { word: "bias", meaning: "偏見；傾向" },
  { word: "cooperation", meaning: "協力，共同" },
  { word: "patent", meaning: "特許（権）；特許品" },
  { word: "dialogue", meaning: "対話，会話；意見の交換" },
  { word: "component", meaning: "構成要素；部品" },
  { word: "reputation", meaning: "評判；名声" },
  { word: "verbal", meaning: "言葉の；口頭での；動詞の" },
  { word: "internal", meaning: "内部の（⇔ external ⇒ 989）；国内の；内面的な" },
  { word: "solid", meaning: "しっかりした；硬い；固体の" },
  { word: "remote", meaning: "（～から）遠く離れた（from）；かけ離れた" },
  { word: "principal", meaning: "主要な；資本金の" },
  { word: "sophisticated", meaning: "高性能の，精巧な；洗練された" },
  { word: "equivalent", meaning: "等しい，相当する" },
  { word: "rational", meaning: "理性的な；合理的な" },
  { word: "relevant", meaning: "関係がある；適切な" },
  { word: "absolute", meaning: "絶対的な（⇔ relative 相対的な）" },
  { word: "frequent", meaning: "頻繁な" },
  { word: "permanent", meaning: "永続的な（⇔ temporary ⇒ 793）" },
  { word: "intense", meaning: "強烈な；熱烈な" },
  { word: "meaningful", meaning: "意味のある" },
  { word: "evil", meaning: "邪悪な；有害な" },
  { word: "extinct", meaning: "絶滅した；廃止された" },
  { word: "random", meaning: "無作為の；手当たり次第の" },
  { word: "raw", meaning: "生の；未加工の" },
  { word: "rude", meaning: "無礼な（⇔ polite 礼儀正しい）；粗野な" },
  { word: "mere", meaning: "単なる，ほんの" },
  { word: "tropical", meaning: "熱帯の" },
  { word: "forth", meaning: "前へ，先へ；それ以降" },
  { word: "possess", meaning: "を所有している；の心をとらえる" },
  { word: "dominate", meaning: "を支配する；（～より）優勢である（over）" },
  { word: "guarantee", meaning: "を保証する" },
  { word: "melt", meaning: "溶ける；なごむ；を溶かす" },
  { word: "embarrass", meaning: "に恥ずかしい思いをさせる" },
  { word: "discourage", meaning: "（人）にやる気をなくさせる；を落胆させる（⇔ encourage ⇒ 30）" },
  { word: "detect", meaning: "を感知する；を見つけ出す；に気づく" },
  { word: "devote", meaning: "をささげる" },
  { word: "urge", meaning: "に（強く）促す；を強く主張する；を駆り立てる" },
  { word: "lend", meaning: "を貸す（⇔ borrow を借りる）；（人）に（助言・援助など）を与える" },
  { word: "restrict", meaning: "を制限する" },
  { word: "isolate", meaning: "を孤立させる" },
  { word: "accompany", meaning: "に同行する；に付随する" },
  { word: "exhaust", meaning: "を疲れ果てさせる；を使い尽くす；排気する" },
  { word: "annoy", meaning: "を悩ます；〔受身形で〕腹が立つ" },
  { word: "endanger", meaning: "を危険にさらす" },
  { word: "acknowledge", meaning: "（事実など）を認める（≒ admit ⇒ 406）；に謝意を表す" },
  { word: "admire", meaning: "に（～のことで）敬服［感心］する（for）" },
  { word: "evaluate", meaning: "を評価する；を査定する" },
  { word: "declare", meaning: "を宣言する；を申告する" },
  { word: "secure", meaning: "を確保する；を守る" },
  { word: "specialize", meaning: "専門とする；【英】（～を）専攻する（in）（≒ 【米】major）" },
  { word: "attribute", meaning: "（結果など）を（～に）帰する（to）" },
  { word: "pretend", meaning: "（の）ふりをする" },
  { word: "bury", meaning: "を埋める；を埋葬する；を隠す" },
  { word: "reverse", meaning: "を逆転させる；を反対にする" },
  { word: "resist", meaning: "に抵抗する；〔通例否定文で〕を我慢する" },
  { word: "scare", meaning: "をおびえさせる；を脅す" },
  { word: "imitate", meaning: "をまねる；を模造する" },
  { word: "assist", meaning: "（を）援助する；を手伝う" },
  { word: "resemble", meaning: "に似ている" },
  { word: "retire", meaning: "（～から）引退する，退職する（from）；退く" },
  { word: "neglect", meaning: "をおろそかにする，怠る；を無視する" },
  { word: "collapse", meaning: "崩壊する；（人が）倒れる；を折り畳む" },
  { word: "reform", meaning: "を改革する；を改心させる" },
  { word: "protest", meaning: "（に）抗議する；を主張する" },
  { word: "owe", meaning: "に借りがある；のおかげである" },
  { word: "sustain", meaning: "を持続させる；を支える" },
  { word: "assign", meaning: "を割り当てる；を（～に）配属する（to）" },
  { word: "accomplish", meaning: "を成し遂げる" },
  { word: "wisdom", meaning: "知恵；賢明さ；学識" },
  { word: "literacy", meaning: "読み書きの能力；（特定分野の）知識" },
  { word: "heritage", meaning: "遺産" },
  { word: "mission", meaning: "使命；（外交）使節団；布教" },
  { word: "license", meaning: "免許（証）；許可" },
  { word: "elite", meaning: "〔通例the ～〕〔集合的に〕エリート" },
  { word: "layer", meaning: "層" },
  { word: "motor", meaning: "モーター；原動力" },
  { word: "protein", meaning: "たんぱく質" },
  { word: "profession", meaning: "職業；専門職；同業者仲間" },
  { word: "editor", meaning: "編集者；編集長" },
  { word: "agent", meaning: "仲介者，代理人；薬剤" },
  { word: "globe", meaning: "地球（≒ earth）；世界；球" },
  { word: "haven", meaning: "避難所，保護区；港" },
  { word: "row", meaning: "列；（建物が並ぶ）通り" },
  { word: "sacrifice", meaning: "犠牲；いけにえ" },
  { word: "means", meaning: "〔単数・複数扱い〕手段；〔複数扱い〕資力，収入" },
  { word: "session", meaning: "集まり；（議会の）会期；（開会中の）議会" },
  { word: "league", meaning: "（競技）連盟；同盟" },
  { word: "contest", meaning: "コンテスト，競技（会）；争い" },
  { word: "guard", meaning: "警備員；警備隊；監視，警戒" },
  { word: "opponent", meaning: "（試合・論争などの）相手；反対者" },
  { word: "glance", meaning: "（～を）ちらっと見ること（at）" },
  { word: "divorce", meaning: "離婚；分離" },
  { word: "tissue", meaning: "（生物の）組織；ティッシュペーパー" },
  { word: "liquid", meaning: "液体" },
  { word: "inequality", meaning: "不平等；不公平な事柄" },
  { word: "prejudice", meaning: "（～に対する）偏見（against）（≒ bias）" },
  { word: "justice", meaning: "公正，正義；司法" },
  { word: "guideline", meaning: "指針，ガイドライン；指導基準" },
  { word: "platform", meaning: "プラットフォーム；演壇；舞台" },
  { word: "sector", meaning: "（社会・経済などの）部門，セクター；（都市内の）地域" },
  { word: "channel", meaning: "チャンネル；伝達経路；海峡" },
  { word: "glacier", meaning: "氷河" },
  { word: "primate", meaning: "霊長目の動物" },
  { word: "usage", meaning: "（使）用法；語法；習慣" },
  { word: "fortune", meaning: "財産；幸運（≒ luck）；運命" },
  { word: "correlation", meaning: "相互関係，相関（関係）" },
  { word: "artistic", meaning: "芸術的な" },
  { word: "literary", meaning: "文学の；文語の（⇔ colloquial 口語体の）" },
  { word: "classic", meaning: "第一級の；典型的な；定番の" },
  { word: "liberal", meaning: "自由主義の；寛大な；一般教養の" },
  { word: "concrete", meaning: "具体的な（⇔ abstract ⇒ 586）；有形の" },
  { word: "slight", meaning: "わずかな；取るに足らない" },
  { word: "federal", meaning: "連邦（政府）の" },
  { word: "primitive", meaning: "原始的な；未開の" },
  { word: "unfamiliar", meaning: "（～に）不慣れな（with）；（～に）（よく）知られていない（to）" },
  { word: "subtle", meaning: "微妙な；（気体などが）希薄な" },
  { word: "plain", meaning: "明らかな；平易な；飾りのない；率直な" },
  { word: "marine", meaning: "海の；船舶の" },
  { word: "apparent", meaning: "明白な；一見～らしい" },
  { word: "reluctant", meaning: "気が進まない，嫌がる（⇔ willing ⇒ 298）" },
  { word: "temporary", meaning: "一時的な（⇔ permanent ⇒ 690）" },
  { word: "guilty", meaning: "罪悪感のある；（～について）有罪の（of）" },
  { word: "royal", meaning: "王の" },
  { word: "pure", meaning: "純粋な；潔白な；まったくの" },
  { word: "incredible", meaning: "信じられない；すばらしい" },
  { word: "eager", meaning: "（～を）熱望して（for）；熱心な" },
  { word: "adequate", meaning: "十分な；適切な（⇔ inadequate 不適切な）" },
  { word: "via", meaning: "～経由で；～の媒介で" },
  { word: "assess", meaning: "を評価する；を査定する" },
  { word: "approve", meaning: "賛成する；を承認する" },
  { word: "remark", meaning: "と述べる；（～について）意見を述べる（on / upon）" },
  { word: "pose", meaning: "（危険）を引き起こす；（問題など）を提起する；ポーズをとる；（～を）装う（as）" },
  { word: "yield", meaning: "をもたらす；を（～に）譲る（to）；（～に）屈する（to）" },
  { word: "exhibit", meaning: "を示す，見せる；を展示する" },
  { word: "distribute", meaning: "を（～に）分配する（to）；〔受身形で〕分布する" },
  { word: "command", meaning: "を命じる；を指揮する；（景色）を見渡せる" },
  { word: "occupy", meaning: "（空間・時間）を占める；を占領する" },
  { word: "pop", meaning: "ひょいと動く；不意に現れる；ポンとはじける" },
  { word: "pile", meaning: "を積み重ねる；積み重なる" },
  { word: "greet", meaning: "に挨拶する；を迎える" },
  { word: "apologize", meaning: "（～に；～のことで）謝る（to；for）；弁明する" },
  { word: "frustrate", meaning: "をいら立たせる；（計画・希望など）を挫折させる" },
  { word: "relieve", meaning: "を和らげる；〔受身形で〕（...して）安心する（to do）；を解放する" },
  { word: "derive", meaning: "由来する；を引き出す；を推論する" },
  { word: "deserve", meaning: "に値する" },
  { word: "peer", meaning: "（～を）じっと見る（at / into）" },
  { word: "defeat", meaning: "を負かす（≒ beat）；を失敗させる" },
  { word: "convert", meaning: "を変える；を改宗［転向］させる；を交換する" },
  { word: "wed", meaning: "と結婚する；を（～と）結婚させる（to）" },
  { word: "delight", meaning: "を喜ばせる；（～を）大いに喜ぶ（in）" },
  { word: "boost", meaning: "を押し上げる；を増加させる" },
  { word: "endure", meaning: "に耐える（≒ put up with）；（に）持ちこたえる" },
  { word: "correspond", meaning: "一致する；（～に）相当する（to）；文通する" },
  { word: "impose", meaning: "を課す；を押しつける" },
  { word: "rescue", meaning: "を救う" },
  { word: "resolve", meaning: "を解決する；を決意する；を議決する" },
  { word: "register", meaning: "を記録する，登録する；（～に）登録する（for）" },
  { word: "interrupt", meaning: "を中断させる；（の）邪魔をする" },
  { word: "rid", meaning: "から（～を）取り除く，除去する（of）" },
  { word: "prohibit", meaning: "を禁止する" },
  { word: "compose", meaning: "を構成する；を創作する；を鎮静する" },
  { word: "misunderstand", meaning: "（を）誤解する" },
  { word: "punish", meaning: "を罰する；に損傷を与える" },
  { word: "ruin", meaning: "をだめにする；を破滅させる；破滅する" },
  { word: "defend", meaning: "を防御する；を弁護する" },
  { word: "embrace", meaning: "を受け入れる；（を）抱擁する；を包含する" },
  { word: "modify", meaning: "を修正する；を緩和する" },
  { word: "qualify", meaning: "（人）に資格を与える；資格がある" },
  { word: "passion", meaning: "情熱；熱中；激怒" },
  { word: "enthusiasm", meaning: "（～への）熱情，熱意（for）" },
  { word: "phase", meaning: "段階，局面；側面" },
  { word: "mode", meaning: "方式；気分；形態；流行" },
  { word: "span", meaning: "期間；範囲" },
  { word: "gravity", meaning: "重力，引力；重量；重大さ" },
  { word: "orbit", meaning: "軌道；（活動・勢力などの）範囲" },
  { word: "asteroid", meaning: "小惑星（≒ minor planet）；ヒトデ（＝ starfish）" },
  { word: "core", meaning: "核心；芯" },
  { word: "soul", meaning: "精神；魂，霊魂；生気" },
  { word: "nerve", meaning: "神経；〔～s〕神経過敏；（...する）度胸（to do）" },
  { word: "infection", meaning: "感染（症）" },
  { word: "mall", meaning: "【主に米】 モール，ショッピングセンター" },
  { word: "grocery", meaning: "〔～ies〕食料雑貨；食料雑貨店" },
  { word: "humor", meaning: "ユーモア；気分，機嫌；気質" },
  { word: "instinct", meaning: "本能；勘，直感；（自然に起こる）衝動" },
  { word: "faith", meaning: "（～への）信頼（in）；信仰（心）" },
  { word: "courage", meaning: "勇気" },
  { word: "incentive", meaning: "動機（づけ）；報奨金" },
  { word: "prospect", meaning: "見込み；〔～s〕（未来への）展望；有望な人" },
  { word: "obstacle", meaning: "（～に対する）障害（物）（to）" },
  { word: "architecture", meaning: "建築；建築様式；構造" },
  { word: "stem", meaning: "（草木の）茎，幹" },
  { word: "illusion", meaning: "錯覚，思い違い；幻想" },
  { word: "discrimination", meaning: "（～に対する）差別（against）；区別" },
  { word: "shame", meaning: "恥；残念なこと" },
  { word: "drought", meaning: "干ばつ；（慢性的な）不足" },
  { word: "flavor", meaning: "風味；特色" },
  { word: "portion", meaning: "部分；1人前；割り当て" },
  { word: "recipe", meaning: "調理法，レシピ；手順；秘訣" },
  { word: "luxury", meaning: "ぜいたく（品）；〔形容詞的に〕豪華な" },
  { word: "chip", meaning: "小片，破片；欠けた箇所；集積回路" },
  { word: "ritual", meaning: "儀式；（日常の）習慣的行為" },
  { word: "sake", meaning: "〔for the ～ ofで〕のために，の目的で；に免じて" },
  { word: "prefecture", meaning: "（日本の）県，府；（フランスなどの）県" },
  { word: "council", meaning: "（地方）議会；評議会；（公の）会議" },
  { word: "administration", meaning: "管理（部）；行政；政府（機関）" },
  { word: "curriculum", meaning: "教育課程，カリキュラム" },
  { word: "precious", meaning: "貴重な；高価な（≒ valuable）" },
  { word: "generous", meaning: "寛大な；気前のよい（⇔ stingy けちな）；豊富な" },
  { word: "casual", meaning: "何気ない；形式ばらない" },
  { word: "optimistic", meaning: "楽観的な（⇔ pessimistic ⇒ 1593）" },
  { word: "rough", meaning: "粗い；大まかな；乱暴な" },
  { word: "unpleasant", meaning: "不愉快な；不親切な，無礼な" },
  { word: "Arctic", meaning: "北極の（⇔ Antarctic 南極の）" },
  { word: "ultimate", meaning: "究極の" },
  { word: "deaf", meaning: "耳が聞こえない（≒ hard of hearing）" },
  { word: "genuine", meaning: "\"本物の（≒ authentic ⇒ 1580, real）；偽りのない\"" },
  { word: "manual", meaning: "体［手］を使う；手の；手動式の" },
  { word: "mechanical", meaning: "機械の；機械的な" },
  { word: "instant", meaning: "即時の，すぐの；即席の" },
  { word: "spare", meaning: "余分の，予備の" },
  { word: "immune", meaning: "（～に対して）免疫を持つ（to）；（～を）免れた（from）" },
  { word: "harsh", meaning: "厳しい；（光・色・味などが）不快な" },
  { word: "collective", meaning: "集団の，共同の" },
  { word: "inevitable", meaning: "避けられない" },
  { word: "profound", meaning: "重大な；深い；難解な" },
  { word: "steady", meaning: "着実な，一定の；安定した" },
  { word: "mature", meaning: "成熟した（⇔ immature 未熟な）；熟した" },
  { word: "likewise", meaning: "同様に（≒ in the same way）" },
  { word: "chase", meaning: "（を）追跡する；（を）追求する" },
  { word: "sue", meaning: "を告訴する；（～を求めて）訴訟を起こす（for）" },
  { word: "gaze", meaning: "じっと見る" },
  { word: "slip", meaning: "滑る；滑り落ちる；そっと動く" },
  { word: "load", meaning: "に積む；に負わせる" },
  { word: "overwhelm", meaning: "を圧倒する；を（精神的に）打ちのめす" },
  { word: "wander", meaning: "歩き回る；それる；はぐれる" },
  { word: "float", meaning: "漂う，浮かぶ；を浮かべる" },
  { word: "pour", meaning: "を注ぐ；激しく降る；押し寄せる" },
  { word: "substitute", meaning: "を代わりに使う；（～の）代理をする（for）" },
  { word: "pronounce", meaning: "を発音する；を宣言する" },
  { word: "shrink", meaning: "縮む，縮小する；減少する；ひるむ" },
  { word: "restore", meaning: "を回復させる；を修復する" },
  { word: "trigger", meaning: "を引き起こす；のきっかけとなる" },
  { word: "grab", meaning: "をつかむ；を横取りする；を急いで食べる" },
  { word: "retain", meaning: "を保持する；を覚えている" },
  { word: "reproduce", meaning: "を複製する；を繁殖させる；繁殖する" },
  { word: "bob", meaning: "上下に動く；急に動く；を上下に動かす" },
  { word: "entertain", meaning: "を楽しませる；をもてなす" },
  { word: "interfere", meaning: "干渉する，介入する；邪魔する" },
  { word: "cultivate", meaning: "を養う；を耕す；を栽培する" },
  { word: "underlie", meaning: "の根底にある" },
  { word: "anticipate", meaning: "を予期する；楽しみに待つ" },
  { word: "justify", meaning: "を正当化する" },
  { word: "regulate", meaning: "を規制する；を調整する" },
  { word: "scan", meaning: "を走査［スキャン］する；をざっと見る；を注意深く調べる" },
  { word: "classify", meaning: "を分類する；を機密扱いにする" },
  { word: "submit", meaning: "を提出する；〔submit oneselfで〕（～に）従う（to）" },
  { word: "pause", meaning: "（一時的に）中止する；（一瞬）立ち止まる" },
  { word: "lean", meaning: "傾く；寄りかかる；をもたせかける" },
  { word: "bump", meaning: "ぶつかる；をぶつける" },
  { word: "fold", meaning: "を折り畳む；（両腕）を組む；（折り）畳める" },
  { word: "hesitate", meaning: "躊躇する，ためらう" },
  { word: "pump", meaning: "（液体・気体）をポンプで送り込む；をくみ出す；を注ぎ込む" },
  { word: "mount", meaning: "を据えつける；に着手する；（自転車など）に乗る；増える" },
  { word: "exceed", meaning: "を超える；に勝る" },
  { word: "undergo", meaning: "を経験する；（手術など）を受ける；に耐える" },
  { word: "confront", meaning: "に立ち向かう；（困難などが）に立ちはだかる" },
  { word: "consult", meaning: "（に）相談する；を参照する" },
  { word: "fulfill", meaning: "を実現させる；を果たす；を満たす" },
  { word: "privilege", meaning: "特権，特典" },
  { word: "formation", meaning: "形成；構成（物）；隊列" },
  { word: "dimension", meaning: "側面，局面；次元；寸法" },
  { word: "neuron", meaning: "ニューロン，神経単位" },
  { word: "sensation", meaning: "感覚；大評判" },
  { word: "chart", meaning: "図，グラフ；海図；ヒットチャート" },
  { word: "geography", meaning: "〔the ～〕地理；地理学" },
  { word: "panel", meaning: "（専門家の）一団；討論者一同；羽目板" },
  { word: "semester", meaning: "【主に米】 （2学期制の）学期" },
  { word: "workforce", meaning: "労働人口，総労働力；全従業員（数）" },
  { word: "mill", meaning: "製造工場；製粉所；粉ひき機" },
  { word: "abuse", meaning: "乱用；虐待" },
  { word: "vice", meaning: "（道徳上の）悪（⇔ virtue ⇒ 1078）；欠点" },
  { word: "fate", meaning: "運命；結末；最期" },
  { word: "tragedy", meaning: "悲劇（的な事態）（⇔ comedy 喜劇）" },
  { word: "scenario", meaning: "（予想される）筋書き，事態；脚本" },
  { word: "allergy", meaning: "アレルギー" },
  { word: "wound", meaning: "（銃弾・刃物などによる）傷；痛手" },
  { word: "antibiotic", meaning: "〔通例～s〕抗生物質" },
  { word: "vaccine", meaning: "ワクチン" },
  { word: "metaphor", meaning: "隠喩；比喩" },
  { word: "folk", meaning: "人々；〔～s〕皆さん；〔one's ～s〕家族" },
  { word: "fare", meaning: "（乗り物の）料金" },
  { word: "transition", meaning: "移り変わり；過渡期" },
  { word: "maximum", meaning: "最大限（⇔ minimum ⇒ 653）" },
  { word: "galaxy", meaning: "星雲，銀河；〔the G～〕銀河系" },
  { word: "mineral", meaning: "鉱物；ミネラル" },
  { word: "skeleton", meaning: "骨格；骨組み；概略" },
  { word: "counterpart", meaning: "相当する物［人］" },
  { word: "stroke", meaning: "脳卒中；（ボールを）打つこと；（雷などの）一撃" },
  { word: "pedestrian", meaning: "歩行者" },
  { word: "trail", meaning: "（野山などの）小道；跡；手がかり" },
  { word: "ecology", meaning: "生態学；生態系；環境保護" },
  { word: "sibling", meaning: "きょうだい（の1人）" },
  { word: "ratio", meaning: "比率" },
  { word: "mixture", meaning: "混合（物）" },
  { word: "charm", meaning: "魅力；お守り" },
  { word: "ambition", meaning: "（～に対する）願望，野望（for）；野心" },
  { word: "prominent", meaning: "卓越した；目立つ" },
  { word: "radical", meaning: "急進的な；根本的な" },
  { word: "prompt", meaning: "即座の，迅速な" },
  { word: "informal", meaning: "形式ばらない，略式の（⇔ formal 正式の）；（言葉が）くだけた" },
  { word: "mutual", meaning: "相互の；共通の" },
  { word: "neutral", meaning: "中立の；（特徴・表情などが）はっきりしない" },
  { word: "alert", meaning: "警戒して；敏速な" },
  { word: "magnetic", meaning: "磁気の；磁石の；人を引きつける" },
  { word: "polar", meaning: "極地の；電極の" },
  { word: "fluent", meaning: "流ちょうな" },
  { word: "external", meaning: "外部の（⇔ internal ⇒ 680）；対外的な" },
  { word: "passive", meaning: "受動的な；消極的な" },
  { word: "awful", meaning: "ひどい；嫌な；ものすごい" },
  { word: "unrelated", meaning: "無関係の；血縁関係がない" },
  { word: "cruel", meaning: "残酷な；むごい" },
  { word: "fake", meaning: "偽の；見せかけだけの" },
  { word: "vulnerable", meaning: "（攻撃などに）弱い，もろい；傷つきやすい" },
  { word: "urgent", meaning: "緊急の" },
  { word: "spiritual", meaning: "精神の（⇔ material ⇒ 73）；霊的な" },
  { word: "modest", meaning: "謙虚な（≒ humble）；適度な；質素な" },
  { word: "keen", meaning: "熱心な；鋭敏な；（感情・関心などが）強い" },
  { word: "nonetheless", meaning: "それにもかかわらず，それでもなお（≒ nevertheless）" },
  { word: "negotiate", meaning: "交渉する；を（交渉して）取り決める" },
  { word: "grasp", meaning: "を把握［理解］する；をしっかり握る" },
  { word: "donate", meaning: "を寄付する；（臓器・血液）を提供する" },
  { word: "arrest", meaning: "を逮捕する；を止める；（注意）を引く" },
  { word: "crack", meaning: "ひびが入る；にひびを入れる" },
  { word: "tap", meaning: "を軽くたたく；（液体）を出す；を盗聴する" },
  { word: "split", meaning: "を分割する；を分担する；分裂する" },
  { word: "forecast", meaning: "を予想［予測］する" },
  { word: "exclude", meaning: "を除外する（⇔include を含む）" },
  { word: "overlook", meaning: "を見落とす；を大目に見る；を見渡す" },
  { word: "burst", meaning: "破裂する；（～を）突然始める（into）" },
  { word: "heal", meaning: "（人・傷など）を治す；治る" },
  { word: "forbid", meaning: "を禁じる（⇔permit 許可する）" },
  { word: "install", meaning: "をインストールする；を設置する；を就任させる" },
  { word: "diminish", meaning: "を減らす；減少する（≒decrease）" },
  { word: "cite", meaning: "を引き合いに出す；を引用する" },
  { word: "quote", meaning: "を引用する；を引き合いに出す" },
  { word: "dispute", meaning: "に異議を唱える；（を）議論する" },
  { word: "highlight", meaning: "を目立たせる、強調する" },
  { word: "distract", meaning: "（注意など）をそらす" },
  { word: "cheat", meaning: "をだます；不正をする" },
  { word: "foster", meaning: "をはぐくむ；を養育する；を心に抱く" },
  { word: "obey", meaning: "に従う；に服従する" },
  { word: "bend", meaning: "を曲げる；を屈服させる；曲がる" },
  { word: "deprive", meaning: "から（権利などを）奪う" },
  { word: "govern", meaning: "（を）統治する、支配する" },
  { word: "log", meaning: "〔log onで〕ログオンする；を記録する" },
  { word: "transmit", meaning: "を伝える；（電波・信号など）を送る" },
  { word: "bully", meaning: "をいじめる；を脅す" },
  { word: "leap", meaning: "跳ぶ；さっと動く；急上昇する" },
  { word: "astonish", meaning: "を驚かす" },
  { word: "thrill", meaning: "をぞくぞくさせる；わくわくする" },
  { word: "nod", meaning: "うなずく；会釈する；うとうとする" },
  { word: "bow", meaning: "おじぎする；屈服する" },
  { word: "blend", meaning: "を混ぜる；を調和させる；（～に）溶け込む（into）" },
  { word: "complicate", meaning: "を複雑にする" },
  { word: "pitch", meaning: "を投げる；倒れる；縦揺れする" },
  { word: "persist", meaning: "続く；固執する" },
  { word: "dedicate", meaning: "をささげる；を献呈する" },
  { word: "equip", meaning: "に備えつける" },
  { word: "premise", meaning: "前提；〔～s〕（建物を含めた）構内、敷地" },
  { word: "input", meaning: "入力（情報）、投入；（情報・時間などの）提供" },
  { word: "merit", meaning: "利点（⇔demerit 欠点）；功績；真価" },
  { word: "sympathy", meaning: "同情；（～に対する）共感（with/for）" },
  { word: "compliment", meaning: "賛辞；表敬" },
  { word: "infrastructure", meaning: "インフラ、基本的施設；（経済）基盤" },
  { word: "ray", meaning: "光線；ひらめき、一筋の光明" },
  { word: "distress", meaning: "苦悩；苦痛；困窮" },
  { word: "joint", meaning: "関節；接合（部）" },
  { word: "expedition", meaning: "遠征（隊）、探検（隊）" },
  { word: "adolescent", meaning: "青年；青年期の" },
  { word: "shade", meaning: "（日）陰；色合い；日よけ；微妙な相違" },
  { word: "jury", meaning: "陪審（員団）；審査員団" },
  { word: "ethic", meaning: "倫理、道徳；〔～s〕倫理［道徳］規範" },
  { word: "penalty", meaning: "（刑）罰；罰金；ペナルティー" },
  { word: "faculty", meaning: "能力、機能；学部；教授陣" },
  { word: "scheme", meaning: "計画（≒plan）；体系；陰謀" },
  { word: "nutrition", meaning: "栄養（の摂取）" },
  { word: "particle", meaning: "（微）粒子；ほんのわずか" },
  { word: "molecule", meaning: "分子；微粒子" },
  { word: "nationality", meaning: "国籍；国民；国民性" },
  { word: "poll", meaning: "世論調査；投票（数）" },
  { word: "clinic", meaning: "診療所、クリニック；（病院内の）～科" },
  { word: "dementia", meaning: "認知症" },
  { word: "fatigue", meaning: "疲労（≒exhaustion）" },
  { word: "dilemma", meaning: "ジレンマ、板ばさみ" },
  { word: "queue", meaning: "【英】（順番を待つ）列" },
  { word: "curve", meaning: "（道路などの）カーブ；曲線" },
  { word: "narrative", meaning: "物語、話；（小説の）叙述部分、地の文" },
  { word: "fingerprint", meaning: "指紋" },
  { word: "file", meaning: "ファイル；（書類の）とじ込み" },
  { word: "wilderness", meaning: "荒野；（庭・町などの）放置された部分" },
  { word: "pesticide", meaning: "殺虫剤；除草剤（≒herbicide）" },
  { word: "panic", meaning: "パニック（状態）；狼狽" },
  { word: "fabric", meaning: "織物、布（地）；構造" },
  { word: "fantasy", meaning: "空想；幻想；幻想的作品" },
  { word: "fancy", meaning: "（気まぐれな）好み；空想；思いつき" },
  { word: "virtue", meaning: "美徳（⇔vice 悪）；長所；効能" },
  { word: "grateful", meaning: "感謝している" },
  { word: "valid", meaning: "妥当な；有効な" },
  { word: "elaborate", meaning: "入念な；凝った" },
  { word: "moderate", meaning: "適度な；穏健な" },
  { word: "dynamic", meaning: "活動的な、精力的な；動的な（⇔static 静的な）" },
  { word: "brave", meaning: "勇敢な（⇔cowardly 臆病な）；見事な" },
  { word: "brilliant", meaning: "すばらしい；才能にあふれた；きらめく" },
  { word: "tremendous", meaning: "途方もない、莫大な；すばらしい" },
  { word: "oral", meaning: "口頭の" },
  { word: "innocent", meaning: "無罪の（⇔guilty 有罪の）；無邪気な；無知の" },
  { word: "subsequent", meaning: "その後の" },
  { word: "shallow", meaning: "浅い（⇔deep 深い）；浅薄な" },
  { word: "indifferent", meaning: "無関心な（≒uninterested）" },
  { word: "inferior", meaning: "より劣った（⇔superior よりすぐれた）" },
  { word: "awkward", meaning: "気まずい；ぎこちない；厄介な" },
  { word: "obese", meaning: "肥満した" },
  { word: "pregnant", meaning: "妊娠した；（～で）満ちている（with）" },
  { word: "intimate", meaning: "親密な；密接な" },
  { word: "medieval", meaning: "中世の；時代遅れの" },
  { word: "sacred", meaning: "神聖な（≒holy）；宗教的な；厳粛な" },
  { word: "simultaneously", meaning: "（～と）同時に（with）；一斉に" },
  { word: "versus", meaning: "〔A ～ Bで〕A対B；AかBか" },
  { word: "proceed", meaning: "進む，進行する；（～を）続行する（with）" },
  { word: "orient", meaning: "（人）を（環境などに）慣らす（to）；〔受身形で〕（関心などが）（～に）向いている（to / toward）" },
  { word: "surf", meaning: "（インターネット上の情報など）を見て回る；サーフィンをする" },
  { word: "filter", meaning: "をろ過する；を取り除く" },
  { word: "bind", meaning: "を縛る；を束縛する；を結び付ける" },
  { word: "resort", meaning: "（好ましくない手段に）訴える，頼る（to）" },
  { word: "reinforce", meaning: "を強化する；を補強する" },
  { word: "accumulate", meaning: "を蓄積する，集める；積もる" },
  { word: "bet", meaning: "と確信する，断言する；（金などを）かける" },
  { word: "advocate", meaning: "を主張する；を擁護する" },
  { word: "constitute", meaning: "を構成する；になる，に等しい" },
  { word: "undertake", meaning: "を引き受ける；を保証する；に着手する" },
  { word: "grip", meaning: "を握る；をとらえる" },
  { word: "dismiss", meaning: "（意見など）を退ける；を解雇する" },
  { word: "fade", meaning: "薄れる；衰える" },
  { word: "conceal", meaning: "を隠す（≒ hide）；を秘密にする（⇔uncover ⇒ 1236）" },
  { word: "chew", meaning: "（を）かむ；をかみ砕く" },
  { word: "swallow", meaning: "（を）飲み込む；をうのみにする；に耐える" },
  { word: "seal", meaning: "を密閉する；に封をする" },
  { word: "migrate", meaning: "移住する；（鳥などが）渡る" },
  { word: "exaggerate", meaning: "（を）誇張する；を強調する" },
  { word: "accuse", meaning: "を非難する；を告訴する" },
  { word: "vanish", meaning: "消える（≒ disappear）" },
  { word: "polish", meaning: "を磨く；を洗練させる" },
  { word: "wipe", meaning: "を拭く；を拭き取る；を消し去る" },
  { word: "sweep", meaning: "（を）掃く；を一掃する；さっと通過する" },
  { word: "mislead", meaning: "を誤解させる，欺く；（人）を間違った方向に導く" },
  { word: "spoil", meaning: "を台無しにする；を甘やかす；だめになる" },
  { word: "compound", meaning: "を悪化させる；を合成する；を混合する" },
  { word: "explode", meaning: "爆発する；急増する；を論破する" },
  { word: "disgust", meaning: "をむかつかせる；に愛想を尽かせる" },
  { word: "commute", meaning: "通勤［通学］する" },
  { word: "decorate", meaning: "を装飾する" },
  { word: "postpone", meaning: "を延期する（≒ put off）" },
  { word: "cease", meaning: "をやめる；終わる" },
  { word: "compromise", meaning: "妥協する；を危うくする" },
  { word: "elect", meaning: "を選出する" },
  { word: "extract", meaning: "を取り［搾り］出す；を抜粋する" },
  { word: "inherit", meaning: "を受け継ぐ；を相続する" },
  { word: "rear", meaning: "（人・動物・植物）を育てる（≒ raise）" },
  { word: "empathy", meaning: "感情移入，共感" },
  { word: "cue", meaning: "合図；手がかり；（次の演技の）キュー" },
  { word: "enterprise", meaning: "企業，事業；企画；進取の気性" },
  { word: "output", meaning: "生産（高）；出力；排出（量）" },
  { word: "congress", meaning: "（米国などの）議会；会議" },
  { word: "millennium", meaning: "千年間，千年紀" },
  { word: "mankind", meaning: "人類" },
  { word: "Muslim", meaning: "イスラム教徒" },
  { word: "estate", meaning: "（動産・不動産などの）財産；私有地" },
  { word: "landmine", meaning: "地雷" },
  { word: "caution", meaning: "用心；警告" },
  { word: "controversy", meaning: "論争" },
  { word: "consensus", meaning: "総意；（意見の）一致" },
  { word: "retail", meaning: "小売り（⇔ wholesale 卸売り）" },
  { word: "fiber", meaning: "繊維（質）；本質；精神力" },
  { word: "scent", meaning: "（よい）香り；香水" },
  { word: "beverage", meaning: "（水以外の）飲み物，飲料" },
  { word: "supplement", meaning: "栄養補助剤，サプリメント；補足" },
  { word: "diabetes", meaning: "糖尿病" },
  { word: "province", meaning: "州，省；〔the ～s〕地方；分野" },
  { word: "reef", meaning: "（岩や砂の）礁；暗礁" },
  { word: "microbe", meaning: "微生物；細菌" },
  { word: "excess", meaning: "過剰，超過" },
  { word: "gallery", meaning: "美術館，画廊；観客，ギャラリー；回廊" },
  { word: "fame", meaning: "名声" },
  { word: "deadline", meaning: "締め切り" },
  { word: "undergraduate", meaning: "学部学生" },
  { word: "slavery", meaning: "奴隷制度；苦役" },
  { word: "prey", meaning: "獲物；犠牲者" },
  { word: "mess", meaning: "散らかった状態［物］；混乱状態" },
  { word: "recession", meaning: "不況；後退" },
  { word: "retreat", meaning: "後退，退却；（計画・決定などの）撤回" },
  { word: "grave", meaning: "墓；〔通例the ～〕死" },
  { word: "column", meaning: "コラム；（新聞などの）欄；円柱；（縦）列" },
  { word: "scenery", meaning: "〔集合的に〕景色；背景" },
  { word: "plot", meaning: "（小説などの）筋；陰謀" },
  { word: "sculpture", meaning: "彫刻（作品）" },
  { word: "tablet", meaning: "タブレット（型情報端末）；錠剤；平板" },
  { word: "dense", meaning: "密集した，密度の高い；（霧などが）濃い" },
  { word: "exotic", meaning: "外来の；異国風の" },
  { word: "acid", meaning: "酸性の；酸っぱい；辛辣な" },
  { word: "bitter", meaning: "苦い，つらい；辛辣な；怒りっぽい" },
  { word: "sensible", meaning: "賢明な；実用的な；顕著な" },
  { word: "noble", meaning: "高貴な；堂々とした；高潔な" },
  { word: "vague", meaning: "漠然とした，あいまいな；おぼろげな" },
  { word: "parallel", meaning: "（～と）平行［並行］の（to）；類似した" },
  { word: "tense", meaning: "張り詰めた，緊張した" },
  { word: "vertical", meaning: "垂直の（⇔ horizontal 水平な）；縦方向の" },
  { word: "indigenous", meaning: "原産の，先住の；（その土地に）固有の" },
  { word: "aboriginal", meaning: "〔通例A～〕アボリジニの；原生の，先住の" },
  { word: "seasonal", meaning: "季節の，季節的な" },
  { word: "abundant", meaning: "豊富な；（～に）富む（in）" },
  { word: "hybrid", meaning: "ハイブリッドの；雑種の；混成の" },
  { word: "irrelevant", meaning: "（～にとって）無関係の（to）；見当違いの" },
  { word: "ridiculous", meaning: "ばかげた；法外な" },
  { word: "fairy", meaning: "妖精の（ような）" },
  { word: "sensory", meaning: "感覚の" },
  { word: "chronic", meaning: "慢性の（⇔ acute ⇒ 1486）；長引く；常習の" },
  { word: "voluntary", meaning: "自発的な（⇔ compulsory ⇒ 1384）；無償の" },
  { word: "inclined", meaning: "傾向がある；傾いた" },
  { word: "infer", meaning: "を推論する，推測する" },
  { word: "esteem", meaning: "を尊敬する；を見なす" },
  { word: "tackle", meaning: "に取り組む；と（～のことで）話をつける（about / on）" },
  { word: "venture", meaning: "危険を冒して進む；を思い切ってする" },
  { word: "accelerate", meaning: "を加速させる，促進する；加速する" },
  { word: "accustom", meaning: "（人）を慣れさせる" },
  { word: "amuse", meaning: "をおもしろがらせる，楽しませる" },
  { word: "flourish", meaning: "繁栄する；繁茂する；を振りかざす" },
  { word: "thrive", meaning: "繁栄する，うまくいく；繁茂する" },
  { word: "nurture", meaning: "をはぐくむ；を養成する" },
  { word: "click", meaning: "（を）クリックする；をカチッと鳴らす；カチッと音がする" },
  { word: "spin", meaning: "回転する；を回転させる；（糸）を紡ぐ" },
  { word: "clip", meaning: "を切り抜く；を（はさみで）切り取る；をクリップで留める" },
  { word: "drag", meaning: "を引きずる；ぐずぐずする" },
  { word: "cast", meaning: "を投じる；に役を当てる" },
  { word: "scatter", meaning: "をまき散らす；分散する" },
  { word: "tempt", meaning: "を（...する）気にさせる（to do）；を引きつける" },
  { word: "withdraw", meaning: "を引き出す；を撤回する；撤退する" },
  { word: "yawn", meaning: "あくびをする" },
  { word: "blink", meaning: "まばたきする；点滅する；（目）をまたたく" },
  { word: "dye", meaning: "を染める；染まる" },
  { word: "spill", meaning: "をこぼす；こぼれる" },
  { word: "irritate", meaning: "をいらいらさせる；をひりひりさせる" },
  { word: "insult", meaning: "を侮辱する（≒ affront）" },
  { word: "enforce", meaning: "を施行［実施］する；を（～に）強制する（on / upon）" },
  { word: "rob", meaning: "から（金品を）奪う" },
  { word: "drain", meaning: "（液体）を流出させる；（液体が）流れ出る" },
  { word: "suspend", meaning: "を停職［停学，出場停止］にする；を一時的に中断する" },
  { word: "drift", meaning: "漂う；さまよう；を押し流す" },
  { word: "forgive", meaning: "を許す；を免除する" },
  { word: "revise", meaning: "を修正する；を改訂する" },
  { word: "recruit", meaning: "を募る；に新人を補充する" },
  { word: "twist", meaning: "をねじる，ひねる；を歪曲する" },
  { word: "crush", meaning: "を押しつぶす；を弾圧する；を絞り出す" },
  { word: "pin", meaning: "をピンで留める；を突き刺す" },
  { word: "uncover", meaning: "を暴く（⇔ conceal ⇒ 1116）；を 発掘する" },
  { word: "exploit", meaning: "を活用する；を搾取する，につけ込む" },
  { word: "implement", meaning: "を実行［実施］する" },
  { word: "integrate", meaning: "を統合する；融合する" },
  { word: "incorporate", meaning: "を取り入れる；を法人にする；合併する" },
  { word: "profile", meaning: "人物の紹介；横顔；輪郭" },
  { word: "appetite", meaning: "食欲；欲求" },
  { word: "impulse", meaning: "衝動；刺激" },
  { word: "script", meaning: "台本；筆跡" },
  { word: "anniversary", meaning: "（～周年）記念日" },
  { word: "pension", meaning: "年金" },
  { word: "temper", meaning: "気質，気性；機嫌；かんしゃく" },
  { word: "cortex", meaning: "皮質；樹皮" },
  { word: "syndrome", meaning: "症候群；～現象" },
  { word: "chamber", meaning: "（特定の目的の）部屋；議場；〔the ～〕議院" },
  { word: "utility", meaning: "公共事業；公共料金；実用性" },
  { word: "cattle", meaning: "〔集合的に〕牛" },
  { word: "herd", meaning: "（牛などの）群れ；群衆" },
  { word: "fluid", meaning: "流動体，液体" },
  { word: "pity", meaning: "残念なこと；哀れみ" },
  { word: "priest", meaning: "聖職者" },
  { word: "acquaintance", meaning: "知人；面識；知識" },
  { word: "offspring", meaning: "子孫，子；成果" },
  { word: "famine", meaning: "飢饉；（食糧・物資の）ひどい不足" },
  { word: "deforestation", meaning: "森林伐採" },
  { word: "jail", meaning: "刑務所，拘置所（≒ prison）" },
  { word: "commodity", meaning: "商品；有用なもの" },
  { word: "format", meaning: "書式，形式；（本などの）型" },
  { word: "recipient", meaning: "受け取る人；（臓器などの）被提供者" },
  { word: "drill", meaning: "訓練；（反復）練習；ドリル，錐" },
  { word: "inability", meaning: "無能，無力" },
  { word: "republic", meaning: "共和国；共和制" },
  { word: "combat", meaning: "戦闘；対立" },
  { word: "debris", meaning: "（破壊された後の）残骸，瓦礫；がらくた" },
  { word: "bug", meaning: "病原菌（が起こす病気）；虫；盗聴器；（機械・プログラムの）欠陥" },
  { word: "fraction", meaning: "わずか（≒ bit），一部；分数" },
  { word: "index", meaning: "指標；索引；指数" },
  { word: "intuition", meaning: "直観（力），直感" },
  { word: "motive", meaning: "動機" },
  { word: "consent", meaning: "同意，承諾" },
  { word: "hierarchy", meaning: "（社会の）階層制；〔the ～〕支配層" },
  { word: "monument", meaning: "記念碑，遺跡；金字塔" },
  { word: "asset", meaning: "〔通例～s〕資産；価値のあるもの；利点" },
  { word: "decent", meaning: "まずまずの；きちんとした；上品な" },
  { word: "competent", meaning: "有能な；適任の；満足できる" },
  { word: "straightforward", meaning: "単純な；率直な" },
  { word: "cosmetic", meaning: "化粧の，美容の；うわべの" },
  { word: "delicate", meaning: "繊細な；扱いにくい；もろい" },
  { word: "interior", meaning: "室内の；内部の（⇔ exterior 外部の）" },
  { word: "transparent", meaning: "透明な；明快な" },
  { word: "aesthetic", meaning: "美的な；美学の" },
  { word: "deliberate", meaning: "故意の；慎重な" },
  { word: "demographic", meaning: "人口統計学の" },
  { word: "prehistoric", meaning: "有史以前の；旧式な" },
  { word: "innate", meaning: "生まれながらの；固有の" },
  { word: "mild", meaning: "穏やかな；（程度が）軽い" },
  { word: "toxic", meaning: "有毒な；中毒性の" },
  { word: "ashamed", meaning: "恥じて" },
  { word: "humble", meaning: "謙虚な；質素な；身分が低い" },
  { word: "peculiar", meaning: "特有の；特異な" },
  { word: "steep", meaning: "（傾斜が）急な；急激な；法外な" },
  { word: "trivial", meaning: "ささいな，取るに足りない" },
  { word: "magnificent", meaning: "壮大な；見事な" },
  { word: "wireless", meaning: "無線（電信）の，ラジオの" },
  { word: "ongoing", meaning: "継続している，進行中の" },
  { word: "assure", meaning: "に自信を持って言う；を保証する" },
  { word: "precede", meaning: "に先行する；に優先する" },
  { word: "revive", meaning: "を復活させる；復活する" },
  { word: "compel", meaning: "に強いる" },
  { word: "blossom", meaning: "花が咲く（≒ bloom）；発展する" },
  { word: "terrify", meaning: "を怖がらせる；を脅かす" },
  { word: "violate", meaning: "（法律・規則など）に違反する；を侵害する" },
  { word: "suppress", meaning: "を抑える；を抑圧する" },
  { word: "deceive", meaning: "をだます（≒ take in）" },
  { word: "manipulate", meaning: "を（巧みに）操る；を改ざんする" },
  { word: "starve", meaning: "飢える；（～を）渇望する（for）；を飢えさせる" },
  { word: "flee", meaning: "（から）逃げる" },
  { word: "whisper", meaning: "（を）ささやく" },
  { word: "yell", meaning: "叫ぶ，どなる" },
  { word: "deposit", meaning: "を置く；を預ける；を堆積させる" },
  { word: "confine", meaning: "を限定する；〔通例受身形で〕閉じ込められる" },
  { word: "swing", meaning: "を揺らす，振る；揺れる；（行動に）さっと移る" },
  { word: "prolong", meaning: "を長引かせる" },
  { word: "depict", meaning: "を描く" },
  { word: "outline", meaning: "の要点を述べる；の輪郭を描く" },
  { word: "shed", meaning: "を捨て去る；（光など）を放つ；（涙・血）を流す" },
  { word: "emit", meaning: "（光・熱など）を出す，排出する；（信号）を送る" },
  { word: "renew", meaning: "を更新する；（資源）を再生する" },
  { word: "utilize", meaning: "を利用する（≒ make use of）" },
  { word: "assert", meaning: "を主張する" },
  { word: "strain", meaning: "に負担をかける；を緊張させる；を漉す" },
  { word: "strive", meaning: "努力する；争う" },
  { word: "dare", meaning: "あえて［思い切って］...する" },
  { word: "boast", meaning: "を誇る；（を）自慢する" },
  { word: "startle", meaning: "をびっくりさせる（≒ surprise）" },
  { word: "offend", meaning: "の気分を害する；（に）違反する" },
  { word: "compute", meaning: "（を）計算する；コンピューターを使う" },
  { word: "assemble", meaning: "を集める；を組み立てる；集まる" },
  { word: "worsen", meaning: "を悪化させる；悪化する（≒ deteriorate）" },
  { word: "flip", meaning: "を（ぱっと）裏返す；を軽くはじく" },
  { word: "rub", meaning: "（を）こする；（～に）を塗る（on / over）" },
  { word: "descend", meaning: "（を）降りる（⇔ ascend ⇒ 1839）；受け継がれる" },
  { word: "compensate", meaning: "補償する（≒ make up）；に償う" },
  { word: "comprise", meaning: "から成る；を構成する" },
  { word: "prevail", meaning: "普及している；支配的である；（～に）打ち勝つ（over）" },
  { word: "quest", meaning: "探究" },
  { word: "dignity", meaning: "尊厳；威厳" },
  { word: "criterion", meaning: "（判断・評価の）基準" },
  { word: "paradox", meaning: "逆説；矛盾" },
  { word: "parliament", meaning: "（英国などの）議会；国会議員（団）" },
  { word: "legislation", meaning: "法律；立法" },
  { word: "agenda", meaning: "協議事項（リスト）；議事日程（表）；（政治上の）課題" },
  { word: "mainstream", meaning: "（活動・思潮などの）主流；大勢" },
  { word: "troop", meaning: "〔～s〕軍隊；集団" },
  { word: "epidemic", meaning: "流行（病）；蔓延" },
  { word: "outbreak", meaning: "発生，勃発" },
  { word: "chaos", meaning: "混沌，大混乱" },
  { word: "nightmare", meaning: "悪夢（のような状況）；不安感" },
  { word: "horror", meaning: "恐怖；強い嫌悪；嫌な物［人］" },
  { word: "cluster", meaning: "集団；（植物の）房，束" },
  { word: "pollen", meaning: "花粉" },
  { word: "hive", meaning: "ミツバチの巣（箱）；人の集まる所" },
  { word: "irrigation", meaning: "灌漑" },
  { word: "dose", meaning: "（薬の1回分の）服用量；放射線の1回の照射量" },
  { word: "suicide", meaning: "自殺；自殺的行為" },
  { word: "feast", meaning: "祝宴；大ごちそう；楽しみ" },
  { word: "cuisine", meaning: "（独特の）料理，料理法" },
  { word: "rumor", meaning: "うわさ" },
  { word: "proverb", meaning: "ことわざ（≒ saying）" },
  { word: "signature", meaning: "署名；特徴" },
  { word: "formula", meaning: "方法，解決策；公式" },
  { word: "tuition", meaning: "【主に米】 授業料（＝ 【英】tuition fees）；（個人）指導" },
  { word: "intake", meaning: "摂取量；受け入れ数；取り入れること" },
  { word: "spectrum", meaning: "スペクトル；（波動・変動の）範囲" },
  { word: "kidney", meaning: "腎臓" },
  { word: "gear", meaning: "用具（一式），器具；歯車；ギア" },
  { word: "aisle", meaning: "（座席間などの）通路" },
  { word: "grief", meaning: "深い悲しみ" },
  { word: "destiny", meaning: "運命" },
  { word: "skull", meaning: "頭骨，頭蓋骨；頭脳" },
  { word: "tomb", meaning: "墓" },
  { word: "monk", meaning: "修道士，僧（⇔ nun 修道女，尼）" },
  { word: "worship", meaning: "崇拝，礼拝（式）；賛美" },
  { word: "outstanding", meaning: "際立った；未払いの；未解決の" },
  { word: "unprecedented", meaning: "前例のない；空前の" },
  { word: "infinite", meaning: "無限の（⇔ finite 有限の）；無数の" },
  { word: "worthwhile", meaning: "価値がある；立派な" },
  { word: "indispensable", meaning: "不可欠な（⇔ dispensable なくてもすむ）" },
  { word: "compulsory", meaning: "義務的な，強制的な（⇔ voluntary ⇒ 1199）" },
  { word: "probable", meaning: "十分にありそうな" },
  { word: "ambiguous", meaning: "あいまいな；多義的な" },
  { word: "obscure", meaning: "（世に）知られていない；不明瞭な" },
  { word: "skeptical", meaning: "（～に）懐疑的な（of ⇒ about）" },
  { word: "fragile", meaning: "壊れやすい；虚弱な" },
  { word: "static", meaning: "静的な（⇔ dynamic ⇒ 1083）；動きのない" },
  { word: "gradual", meaning: "徐々の，緩やかな" },
  { word: "vocal", meaning: "声の，発声の；はっきりものを言う" },
  { word: "vivid", meaning: "鮮やかな；生き生きとした" },
  { word: "imperial", meaning: "帝国の；皇帝の" },
  { word: "hostile", meaning: "敵意のある（⇔friendly 友好的な）" },
  { word: "superficial", meaning: "表面的な" },
  { word: "scarce", meaning: "乏しい；珍しい" },
  { word: "gross", meaning: "総計の；甚だしい；粗野な" },
  { word: "inherent", meaning: "生来の，本来的に備わっている" },
  { word: "notable", meaning: "注目に値する；著名な" },
  { word: "update", meaning: "を最新のものにする；をアップデートする" },
  { word: "refresh", meaning: "（気分）をさわやかにする；（記憶など）を新たにする；を最新のものにする" },
  { word: "bloom", meaning: "花が咲く；栄える" },
  { word: "conquer", meaning: "を征服する；を克服する" },
  { word: "induce", meaning: "を引き起こす；を説得する" },
  { word: "attain", meaning: "を獲得する，達成する；に達する" },
  { word: "spray", meaning: "を吹きかける，に吹きつける" },
  { word: "retrieve", meaning: "（情報）を検索する；を取り戻す；を回復する" },
  { word: "portray", meaning: "を描く；（の役）を演じる" },
  { word: "scratch", meaning: "を引っかく；を取り消す，削除する" },
  { word: "designate", meaning: "を指定する；を任命する" },
  { word: "contradict", meaning: "と矛盾する；に反対意見を言う" },
  { word: "sigh", meaning: "ため息をつく" },
  { word: "disrupt", meaning: "を混乱させる；を分裂させる" },
  { word: "depart", meaning: "出発する；（～から）それる（from）" },
  { word: "navigate", meaning: "（を）誘導する；（を）操縦する；（を）航行する" },
  { word: "beg", meaning: "に（～を）切に頼む（for）；（を）懇願する" },
  { word: "inhabit", meaning: "に住んでいる；に宿る，存する" },
  { word: "diagnose", meaning: "（を）診断する" },
  { word: "comprehend", meaning: "を理解する" },
  { word: "oblige", meaning: "に義務づける；に恩恵を施す" },
  { word: "cram", meaning: "に詰め込む；詰め込み勉強をする" },
  { word: "flock", meaning: "群がる，集まる" },
  { word: "underestimate", meaning: "（を）過小評価する（⇔ overestimate （を）過大評価する）；（を）軽く見る；を少なく見積もる" },
  { word: "clarify", meaning: "を明確にする" },
  { word: "spark", meaning: "を引き起こす；を刺激する；スパークする" },
  { word: "seize", meaning: "をつかむ；を奪い取る；を没収する" },
  { word: "soar", meaning: "急上昇する；空高く飛ぶ" },
  { word: "glow", meaning: "光り［照り］輝く；赤く燃える；紅潮する" },
  { word: "disguise", meaning: "を（～に）変装させる（as）；を偽る" },
  { word: "distort", meaning: "を歪める；歪む" },
  { word: "undermine", meaning: "を徐々にむしばむ；を侵食する" },
  { word: "abolish", meaning: "を廃止する（≒ do away with）" },
  { word: "strip", meaning: "を［から］取り去る；を裸にする" },
  { word: "dispose", meaning: "〔dispose ofで〕を処分する；を（...する）気にさせる（to do）；を配置する" },
  { word: "dump", meaning: "を投棄する；をどさっと落とす" },
  { word: "weave", meaning: "を織る；（計画・物語など）を作り上げる" },
  { word: "refine", meaning: "を洗練する；を精製する" },
  { word: "enrich", meaning: "を豊かにする；（物質）を濃縮化する" },
  { word: "coordinate", meaning: "を調整する；を組織する；（服など）をコーディネートする" },
  { word: "headline", meaning: "（新聞などの）見出し" },
  { word: "internship", meaning: "【米】 実務［医学］研修；研修期間" },
  { word: "outlet", meaning: "直売店，特売店；はけ口；【米】（電気の）コンセント（≒ 【英】socket）" },
  { word: "remedy", meaning: "治療（法）；治療薬；解決法" },
  { word: "pill", meaning: "錠剤，丸薬；〔the ～〕ピル，経口避妊薬" },
  { word: "reception", meaning: "反応；宴会；受付；受信（状態）" },
  { word: "transaction", meaning: "（商）取引；（人と人との）交流" },
  { word: "mutation", meaning: "突然変異（体）；変化" },
  { word: "dairy", meaning: "〔集合的に〕乳製品；乳製品加工所［販売者］" },
  { word: "compassion", meaning: "同情" },
  { word: "posture", meaning: "姿勢；心構え" },
  { word: "curse", meaning: "悪態，ののしりの言葉；呪い；〔通例a ～〕災い" },
  { word: "funeral", meaning: "葬式" },
  { word: "census", meaning: "国勢調査；交通調査" },
  { word: "encyclopedia", meaning: "百科事典" },
  { word: "cereal", meaning: "〔通例～s〕穀物；シリアル（穀物加工食品）" },
  { word: "fragment", meaning: "断片" },
  { word: "patch", meaning: "（～の）部分，斑点；継ぎ；貼り薬" },
  { word: "rubbish", meaning: "【英】 ごみ（≒ 【米】garbage）；つまらないもの" },
  { word: "maze", meaning: "迷路（≒ labyrinth）；複雑に込み入ったもの" },
  { word: "outlook", meaning: "見解；見通し；眺め" },
  { word: "breakthrough", meaning: "大発見，飛躍的進歩" },
  { word: "triumph", meaning: "勝利；勝利の喜び；偉業" },
  { word: "ally", meaning: "同盟国；提携者；援助者；盟友" },
  { word: "spectator", meaning: "（試合などの）観客" },
  { word: "sphere", meaning: "領域；球体；天体" },
  { word: "county", meaning: "【米】 郡；【英】州" },
  { word: "behalf", meaning: "利益，味方" },
  { word: "interval", meaning: "（時間の）間隔；合間；隔たり；小休止" },
  { word: "circulation", meaning: "循環；流通；（新聞・雑誌の）発行部数" },
  { word: "blade", meaning: "刃；（プロペラなどの）羽根；（草などの）葉" },
  { word: "theft", meaning: "窃盗（罪）" },
  { word: "vacuum", meaning: "真空；空虚" },
  { word: "collision", meaning: "衝突；対立" },
  { word: "bargain", meaning: "買い得品；取引；契約" },
  { word: "landmark", meaning: "（ある場所の）目印；画期的な出来事" },
  { word: "revenue", meaning: "歳入（⇔ expenditure 歳出）；収益" },
  { word: "treaty", meaning: "（国家間の）条約；協定" },
  { word: "supreme", meaning: "最高の" },
  { word: "thorough", meaning: "徹底的な；まったくの" },
  { word: "naked", meaning: "裸の" },
  { word: "sincere", meaning: "心からの；誠実な" },
  { word: "tame", meaning: "飼いならされた，人に慣れた；退屈な" },
  { word: "insufficient", meaning: "不十分な；不適当な" },
  { word: "dim", meaning: "薄暗い；ぼんやりした" },
  { word: "acute", meaning: "（痛み・感情などが）激しい；（知覚などが）鋭い；急性の（⇔ chronic ⇒ 1198）" },
  { word: "disabled", meaning: "障害のある；障害者用の" },
  { word: "metropolitan", meaning: "大都市の，首都圏の" },
  { word: "monetary", meaning: "金銭的な；金融の" },
  { word: "alternate", meaning: "代わりの（≒ alternative）；交互の" },
  { word: "partial", meaning: "部分的な；不公平な（⇔impartial 公平な）" },
  { word: "divine", meaning: "神の；神にささげる" },
  { word: "drastic", meaning: "徹底的な，抜本的な；極端な" },
  { word: "fierce", meaning: "猛烈な；どう猛な" },
  { word: "sole", meaning: "唯一の；単独の；独占的な" },
  { word: "spontaneous", meaning: "自然発生的な；自発的な" },
  { word: "spatial", meaning: "空間の" },
  { word: "neat", meaning: "きちんとした；見事な" },
  { word: "tidy", meaning: "きちんとした，整頓された；相当の" },
  { word: "loyal", meaning: "（～に）忠実な（to）；誠実な" },
  { word: "bless", meaning: "に恩恵を与える；に感謝する" },
  { word: "regain", meaning: "を取り戻す" },
  { word: "conform", meaning: "順応する；一致する" },
  { word: "enroll", meaning: "登録する，入会する；を登録させる" },
  { word: "entitle", meaning: "に権利を与える；に題名をつける" },
  { word: "halt", meaning: "を止める；止まる" },
  { word: "provoke", meaning: "（感情・行動など）を引き起こす；を挑発する" },
  { word: "invade", meaning: "を侵略する；を侵害する；（場所）に殺到する" },
  { word: "squeeze", meaning: "押し入る；を押し込む；（を）搾る；（を）強く押す" },
  { word: "crawl", meaning: "はう；ゆっくり進む" },
  { word: "digest", meaning: "を消化する；を理解する；を要約する" },
  { word: "utter", meaning: "（声）を発する；（考えなど）を述べる" },
  { word: "refrain", meaning: "控える" },
  { word: "populate", meaning: "に住む，の住民である；に人を住まわせる" },
  { word: "accommodate", meaning: "を収容する；を（～に）適応させる（to）" },
  { word: "steer", meaning: "（を）操縦する；を（～へ）向ける（to）" },
  { word: "drown", meaning: "溺死する；を水浸しにする" },
  { word: "dip", meaning: "を浸す；（手など）を（～に）突っ込む（into / in）；下がる" },
  { word: "soak", meaning: "を浸す；をずぶぬれにする；浸る" },
  { word: "stir", meaning: "をかき回す；を揺り動かす" },
  { word: "transplant", meaning: "を移植する；を移住させる" },
  { word: "reassure", meaning: "を安心させる" },
  { word: "resume", meaning: "（を）再開する；を取り戻す" },
  { word: "speculate", meaning: "（と）推測する；投機する" },
  { word: "surpass", meaning: "を上回る" },
  { word: "appoint", meaning: "を任命する；（日時・場所など）を指定する" },
  { word: "intrigue", meaning: "に興味を持たせる；陰謀を企てる" },
  { word: "decay", meaning: "腐敗する（≒ rot）；（徐々に）衰える" },
  { word: "contaminate", meaning: "を汚染する；を堕落させる" },
  { word: "swell", meaning: "膨張する，腫れる；を膨らませる" },
  { word: "delete", meaning: "を削除する，消す" },
  { word: "tolerate", meaning: "を許容する，我慢する（≒ put up with）" },
  { word: "envy", meaning: "をうらやむ" },
  { word: "pray", meaning: "（を）祈る" },
  { word: "confess", meaning: "（を）告白する" },
  { word: "resign", meaning: "（を）辞任する；を放棄する" },
  { word: "dissolve", meaning: "（を）溶かす；（議会など）を解散する；（契約など）を解消する；溶ける" },
  { word: "unfold", meaning: "（閉じたもの）を開く；を明らかにする；開く；明らかになる" },
  { word: "awaken", meaning: "を目覚めさせる；（～から）覚める（from）" },
  { word: "conceive", meaning: "（を）思いつく；と想像する；（を）妊娠する" },
  { word: "entrepreneur", meaning: "起業家，事業家" },
  { word: "stake", meaning: "利害関係；〔通例～s〕賭け金；杭" },
  { word: "surplus", meaning: "余剰（⇔ shortage 不足），過剰；黒字" },
  { word: "inflation", meaning: "インフレ（ーション）；（物価の）高騰" },
  { word: "sweatshop", meaning: "搾取工場" },
  { word: "clash", meaning: "衝突；対立；かち合うこと；ガチャンという音" },
  { word: "sociology", meaning: "社会学" },
  { word: "ideology", meaning: "イデオロギー，思想傾向" },
  { word: "margin", meaning: "余白；差；利ざや" },
  { word: "realm", meaning: "領域；領土" },
  { word: "domain", meaning: "分野；領域；ドメイン（＝ domain name）" },
  { word: "algorithm", meaning: "アルゴリズム；問題解決の手順" },
  { word: "prairie", meaning: "大草原" },
  { word: "frontier", meaning: "〔通例the ～s〕最先端；〔the ～〕 【米】辺境地；国境" },
  { word: "bullet", meaning: "銃弾" },
  { word: "shield", meaning: "盾，防御物" },
  { word: "despair", meaning: "絶望" },
  { word: "radiation", meaning: "放射能，放射線" },
  { word: "placebo", meaning: "偽薬，プラシーボ；気休め" },
  { word: "nursery", meaning: "託児所；苗床" },
  { word: "spouse", meaning: "配偶者" },
  { word: "makeup", meaning: "化粧；化粧品；構成；性質" },
  { word: "mummy", meaning: "ミイラ；【英】ママ，お母さん（＝ 【米】mommy）" },
  { word: "flesh", meaning: "（人・動物の）肉；果肉" },
  { word: "limb", meaning: "手足" },
  { word: "odor", meaning: "におい；気配" },
  { word: "laundry", meaning: "洗濯（物）；クリーニング店" },
  { word: "tide", meaning: "潮（の干満）；動向" },
  { word: "questionnaire", meaning: "アンケート" },
  { word: "nonsense", meaning: "ばかげた物［話，考え］；無意味な言葉" },
  { word: "revenge", meaning: "復讐" },
  { word: "intellect", meaning: "知性；〔the ～（s）〕知識人" },
  { word: "hospitality", meaning: "親切なもてなし，歓待；受容性" },
  { word: "librarian", meaning: "司書，図書館員" },
  { word: "manuscript", meaning: "（手書きの）原稿；写本" },
  { word: "obsession", meaning: "（考えなどに）取りつかれること；妄想；強迫観念" },
  { word: "hygiene", meaning: "衛生（状態）；健康法" },
  { word: "paradigm", meaning: "理論的枠組み，パラダイム；模範" },
  { word: "legitimate", meaning: "合法的な；妥当な" },
  { word: "authentic", meaning: "本物の；信頼できる" },
  { word: "empirical", meaning: "経験的な；経験主義の" },
  { word: "immense", meaning: "膨大な" },
  { word: "absurd", meaning: "ばかげた；不合理な" },
  { word: "weird", meaning: "異様な（≒ bizarre），奇妙な" },
  { word: "accidental", meaning: "偶然の；過失による" },
  { word: "uneasy", meaning: "不安な；落ち着かない；ぎこちない" },
  { word: "jealous", meaning: "嫉妬深い；用心深い" },
  { word: "feminine", meaning: "女らしい（⇔ masculine ⇒ 1681）" },
  { word: "swift", meaning: "素早い" },
  { word: "hollow", meaning: "空洞の；空虚な；うわべだけの" },
  { word: "crude", meaning: "大まかな；粗野な；未精製の" },
  { word: "sore", meaning: "痛い；腹が立って" },
  { word: "pessimistic", meaning: "悲観的な（⇔ optimistic ⇒ 882）" },
  { word: "vain", meaning: "無駄な；うぬぼれた" },
  { word: "susceptible", meaning: "（～の）影響を受けやすい（to）；感染しやすい" },
  { word: "edible", meaning: "食用の，食べられる" },
  { word: "sheer", meaning: "純然たる，真の；すごい；（布が）薄地の" },
  { word: "explicit", meaning: "明白な（⇔ implicit ⇒ 1795）；率直な" },
  { word: "prone", meaning: "（～に）なりやすい（to）；（...する）傾向がある（to do）" },
  { word: "affluent", meaning: "裕福な；豊富な" },
  { word: "collaborate", meaning: "共同して働く；（～に）協力する（with）" },
  { word: "exert", meaning: "を及ぼす；（力など）を行使する" },
  { word: "excel", meaning: "（～で）秀でている（in / at）；に勝る" },
  { word: "prosper", meaning: "栄える，成功する；繁殖する" },
  { word: "surge", meaning: "殺到する；（感情が）こみ上げる；急騰する" },
  { word: "intervene", meaning: "（～に）介入する（in）；介在する" },
  { word: "insert", meaning: "を挿入する" },
  { word: "overtake", meaning: "を追い抜く；に追いつく（≒ catch up with）；（災難・強い感情などが）を襲う" },
  { word: "snap", meaning: "をパチンと鳴らす；をポキッと折る；ポキッと折れる；パチンと音を立てる" },
  { word: "carve", meaning: "を彫る；を切り開く；（肉）を切り分ける" },
  { word: "addict", meaning: "〔受身形で〕（～の）中毒になる（to）；（～に）凝る" },
  { word: "condemn", meaning: "を非難する；〔受身形で〕（～の刑を）宣告される（to）" },
  { word: "convict", meaning: "に有罪を宣告する" },
  { word: "dictate", meaning: "を指図する；を書き取らせる；を規定する" },
  { word: "prescribe", meaning: "（薬など）を処方する；を規定する" },
  { word: "inhibit", meaning: "を抑制する；を妨げる" },
  { word: "stray", meaning: "はぐれる，（道に）迷う" },
  { word: "roam", meaning: "（を）歩き回る；放浪する" },
  { word: "enclose", meaning: "を同封する；を取り囲む" },
  { word: "execute", meaning: "を実行する；を処刑する" },
  { word: "coincide", meaning: "同時に起こる；一致する" },
  { word: "lag", meaning: "遅れる；徐々に弱まる" },
  { word: "cling", meaning: "しがみつく；くっつく" },
  { word: "erase", meaning: "を消す" },
  { word: "grind", meaning: "（穀物など）をひく" },
  { word: "knit", meaning: "を編む；を結合する；編み物をする" },
  { word: "inquire", meaning: "（を）尋ねる" },
  { word: "betray", meaning: "をうっかり表す；を裏切る" },
  { word: "leak", meaning: "漏れる；を漏らす" },
  { word: "smash", meaning: "を粉砕する；を強打する；粉々に壊れる；激突する" },
  { word: "bounce", meaning: "跳ねる；反射する；を弾ませる；（Ｅメールが）（宛先不明で）返送される" },
  { word: "sprawl", meaning: "（都市などが）不規則に広がる；だらしなく手足を伸ばす" },
  { word: "converse", meaning: "（～と）会話をする（with）" },
  { word: "recite", meaning: "を暗唱する；を詳述する" },
  { word: "disregard", meaning: "を無視する；を軽視する" },
  { word: "frown", meaning: "眉をひそめる" },
  { word: "evoke", meaning: "を呼び起こす" },
  { word: "pledge", meaning: "を誓う，約束する；を与えることを約束する" },
  { word: "aspire", meaning: "（～を）熱望する（to）" },
  { word: "contemplate", meaning: "（を）熟考する；を予想する" },
  { word: "grace", meaning: "優美，優雅；分別；（神の）恩寵" },
  { word: "enlightenment", meaning: "啓蒙，啓発" },
  { word: "commerce", meaning: "商業；貿易" },
  { word: "draft", meaning: "下書き；為替手形；隙間風" },
  { word: "barrel", meaning: "バレル（液量の単位）；たる" },
  { word: "timber", meaning: "【英】 木材（≒ 【米】lumber）；樹木" },
  { word: "garment", meaning: "衣服" },
  { word: "thread", meaning: "糸；（議論などの）筋道" },
  { word: "cabinet", meaning: "〔しばしばthe C-〕内閣；戸棚" },
  { word: "bureau", meaning: "（官庁の）局；事務局；案内所" },
  { word: "autonomy", meaning: "（個人の）自律；自治（権）；自治体" },
  { word: "toll", meaning: "損害（の程度）；死傷者数；通行料" },
  { word: "discourse", meaning: "話し合い，会話；講演；論説" },
  { word: "superstition", meaning: "迷信" },
  { word: "glimpse", meaning: "ちらりと見えること" },
  { word: "arithmetic", meaning: "計算；算数" },
  { word: "glossary", meaning: "用語小辞典；用語集" },
  { word: "archive", meaning: "〔しばしば～s〕記録文書，公文書；公文書保管所；（コンピューターの）アーカイブ" },
  { word: "legacy", meaning: "遺産" },
  { word: "anthropology", meaning: "人類学" },
  { word: "rage", meaning: "激怒；猛威" },
  { word: "sorrow", meaning: "悲しみ" },
  { word: "psychiatrist", meaning: "精神科医" },
  { word: "ward", meaning: "行政区；病棟" },
  { word: "stall", meaning: "露店；エンスト；失速" },
  { word: "flame", meaning: "炎；情熱" },
  { word: "moisture", meaning: "水分；湿気" },
  { word: "irony", meaning: "皮肉" },
  { word: "warrior", meaning: "戦士" },
  { word: "astronomy", meaning: "天文学" },
  { word: "probe", meaning: "（無人）宇宙探査機；（～の）精査（into）；探り針" },
  { word: "altitude", meaning: "高度，標高" },
  { word: "tumor", meaning: "腫瘍；腫れ物" },
  { word: "defect", meaning: "欠陥；不足" },
  { word: "sanitation", meaning: "公衆衛生（学）；下水［衛生］設備" },
  { word: "longevity", meaning: "長寿；寿命；長年勤続" },
  { word: "scope", meaning: "（活動・能力などの）範囲；余地" },
  { word: "sentiment", meaning: "感情；感想；感傷" },
  { word: "plausible", meaning: "もっともらしい" },
  { word: "vigorous", meaning: "精力的な；激しい；活力のある" },
  { word: "masculine", meaning: "男らしい（⇔ feminine ⇒ 1588）" },
  { word: "rigid", meaning: "厳しい；硬直した" },
  { word: "adverse", meaning: "不都合な；逆の" },
  { word: "coherent", meaning: "一貫した，筋の通った；結束した" },
  { word: "literal", meaning: "文字どおりの；逐語的な；散文的な" },
  { word: "arbitrary", meaning: "恣意的な；独断的な" },
  { word: "anonymous", meaning: "匿名の" },
  { word: "antique", meaning: "骨董の，アンティークの；古風な" },
  { word: "eternal", meaning: "永遠の；不変の" },
  { word: "intermediate", meaning: "中級の；中間の" },
  { word: "subordinate", meaning: "（～より）下位の（to）；副次的な" },
  { word: "gloomy", meaning: "陰気な；薄暗い；悲観的な" },
  { word: "thermal", meaning: "熱の，熱による；保温用の" },
  { word: "faint", meaning: "かすかな；めまいがする；弱々しい" },
  { word: "naive", meaning: "お人よしの，愚直な；純朴な" },
  { word: "apt", meaning: "（...する）傾向がある（to do）；適切な；利発な" },
  { word: "arrogant", meaning: "横柄な，傲慢な" },
  { word: "extrovert", meaning: "外向的な；社交的な" },
  { word: "conspicuous", meaning: "目立つ" },
  { word: "intact", meaning: "損なわれていない，手つかずの" },
  { word: "embody", meaning: "を具現する；を包含する" },
  { word: "illuminate", meaning: "を照らす；を解明する" },
  { word: "console", meaning: "を慰める" },
  { word: "verify", meaning: "の正しさを証明［確認］する" },
  { word: "disclose", meaning: "を公表する，暴く" },
  { word: "stack", meaning: "を積む，積み重ねる；〔～ upで〕（車が）渋滞する" },
  { word: "rotate", meaning: "回転する；循環する；を回転させる" },
  { word: "constrain", meaning: "に（...することを）強いる（to do）；を抑える" },
  { word: "hinder", meaning: "を妨げる" },
  { word: "withstand", meaning: "に耐える" },
  { word: "tweet", meaning: "（を）ツイートする，つぶやく" },
  { word: "sneeze", meaning: "くしゃみをする" },
  { word: "erupt", meaning: "（火山が）噴火する；勃発する" },
  { word: "blur", meaning: "をぼかす；を曇らせる；をあいまいにする" },
  { word: "overlap", meaning: "（一部）重なる；（と）重複［共通］する" },
  { word: "embed", meaning: "〔通例受身形で〕埋め込まれる，はめ込まれる" },
  { word: "displace", meaning: "に取って代わる（≒ replace）；を移動させる" },
  { word: "render", meaning: "を（ある状態に）する；（援助など）を与える" },
  { word: "plunge", meaning: "（～に）（を）突っ込む（into）；没頭する；陥る" },
  { word: "surrender", meaning: "を放棄する，引き渡す；（～に）屈する（to）" },
  { word: "plug", meaning: "〔plug inで〕のプラグを電源に差し込む；を（～で）ふさぐ（with）" },
  { word: "suck", meaning: "（を）吸う；（を）しゃぶる" },
  { word: "mock", meaning: "をばかにする（≒ make fun of）；のまねをしてからかう" },
  { word: "tease", meaning: "（を）からかう；をいじめる" },
  { word: "soothe", meaning: "をなだめる；を和らげる" },
  { word: "stain", meaning: "を汚す；に着色する" },
  { word: "shun", meaning: "を避ける" },
  { word: "stumble", meaning: "よろけながら歩く；（～に）つまずく（on / over）" },
  { word: "flush", meaning: "を紅潮させる；を水で流す；紅潮する" },
  { word: "impair", meaning: "を損なう" },
  { word: "presume", meaning: "と思う；と推定する；を前提とする" },
  { word: "contend", meaning: "と主張する；競う" },
  { word: "roar", meaning: "うなる，ほえる；大笑いする" },
  { word: "haunt", meaning: "（記憶・考えなどが）につきまとう；（幽霊などが）に出る；によく行く" },
  { word: "divert", meaning: "（注意など）をそらす；を迂回させる；（資金など）を転用する" },
  { word: "await", meaning: "を待つ（≒ wait for）" },
  { word: "fetch", meaning: "を（行って）持って［連れて］くる" },
  { word: "unify", meaning: "を統合［統一］する；統一される" },
  { word: "inspect", meaning: "を点検する；を視察する" },
  { word: "entail", meaning: "を伴う，引き起こす；（...すること）を含む（doing）" },
  { word: "tactics", meaning: "作戦，方策；戦術，戦法" },
  { word: "feat", meaning: "偉業，功績；妙技" },
  { word: "prestige", meaning: "名声；〔形容詞的に〕名声のある" },
  { word: "analogy", meaning: "類推；類似" },
  { word: "conscience", meaning: "良心；分別" },
  { word: "textile", meaning: "織物；繊維（産業）" },
  { word: "deficit", meaning: "赤字，不足；欠陥" },
  { word: "plague", meaning: "疫病；（害虫などの）異常発生" },
  { word: "hazard", meaning: "危険（要素）；偶然" },
  { word: "metabolism", meaning: "（新陳）代謝，代謝作用" },
  { word: "paralysis", meaning: "麻痺；〔比喩的に〕麻痺（状態）" },
  { word: "grid", meaning: "（電気などの）供給網；格子（模様）；碁盤目" },
  { word: "carriage", meaning: "馬車；車両（＝ 【米】car）；立ち居振舞い；【英】輸送" },
  { word: "friction", meaning: "不和；摩擦" },
  { word: "rebel", meaning: "反逆者" },
  { word: "regime", meaning: "政権，政体；体制" },
  { word: "monopoly", meaning: "独占（権）" },
  { word: "staple", meaning: "必需食品；主要産物" },
  { word: "merchandise", meaning: "商品" },
  { word: "vendor", meaning: "物売り，行商人；自動販売機" },
  { word: "supervisor", meaning: "監督者；指導教員" },
  { word: "predecessor", meaning: "前任者（⇔ successor 後継者）；前のもの" },
  { word: "personnel", meaning: "〔集合的に〕職員，社員" },
  { word: "vessel", meaning: "船舶；容器；（体液が通る）脈管" },
  { word: "liver", meaning: "肝臓" },
  { word: "duration", meaning: "（時間の）継続，持続（時間）" },
  { word: "certificate", meaning: "証明書；免許状" },
  { word: "geometry", meaning: "幾何学" },
  { word: "symmetry", meaning: "（左右）対称（⇔ asymmetry 非対称）；調和" },
  { word: "biography", meaning: "伝記" },
  { word: "masterpiece", meaning: "傑作" },
  { word: "rhyme", meaning: "押韻詩；韻；〔通例～s〕詩歌" },
  { word: "premium", meaning: "保険料；プレミア；景品" },
  { word: "breakdown", meaning: "崩壊；（神経）衰弱；故障；内訳" },
  { word: "courtesy", meaning: "礼儀正しさ；好意；優遇" },
  { word: "protocol", meaning: "（条約）議定書；外交儀礼；プロトコル" },
  { word: "specimen", meaning: "標本；実例" },
  { word: "thesis", meaning: "論文；命題，テーゼ" },
  { word: "eligible", meaning: "適格の，資格のある；（結婚相手として）望ましい" },
  { word: "intrinsic", meaning: "固有の，本質的な（⇔ extrinsic 非本質的な）" },
  { word: "diligent", meaning: "勤勉な；入念な" },
  { word: "vocational", meaning: "職業の，職業訓練の（ための）" },
  { word: "bankrupt", meaning: "破産宣告を受けた；破綻している" },
  { word: "stern", meaning: "厳しい；いかめしい" },
  { word: "stubborn", meaning: "頑固な，強情な（≒ obstinate）；手に負えない" },
  { word: "maternal", meaning: "母の，母親らしい（⇔ paternal 父の）；妊婦の" },
  { word: "fertile", meaning: "肥沃な（⇔ barren 不毛の）；多産の" },
  { word: "ripe", meaning: "熟した；成熟した" },
  { word: "stiff", meaning: "硬直した，凝った；堅い" },
  { word: "obsolete", meaning: "廃れた，使われなくなった；古くなった" },
  { word: "vacant", meaning: "空いている" },
  { word: "acoustic", meaning: "音響の；聴覚の；（楽器が）アコースティックの" },
  { word: "preliminary", meaning: "予備の，準備の" },
  { word: "approximate", meaning: "おおよその" },
  { word: "implicit", meaning: "暗黙の（⇔ explicit ⇒ 1598）；内在する" },
  { word: "punctual", meaning: "時間を守る" },
  { word: "compatible", meaning: "矛盾しない；互換性のある；気が合う" },
  { word: "ample", meaning: "十分すぎるほどの；広い" },
  { word: "pervasive", meaning: "隅々に広がった；浸透する；充満する" },
  { word: "ubiquitous", meaning: "至る所にある" },
  { word: "deduce", meaning: "を推測する，演繹する" },
  { word: "simulate", meaning: "を模擬実験する；を装う；をまねる" },
  { word: "merge", meaning: "（を）合併する；を融合させる；溶け込む" },
  { word: "penetrate", meaning: "（に）浸透する；（に）進出する；（を）貫く；（を）見抜く" },
  { word: "cater", meaning: "（の）料理をまかなう；（要望などに）応える" },
  { word: "assault", meaning: "に暴行する；を攻撃する" },
  { word: "torture", meaning: "を拷問にかける；を苦しめる" },
  { word: "bleed", meaning: "出血する" },
  { word: "erect", meaning: "を建てる；を直立させる" },
  { word: "cherish", meaning: "を大切にする；を心に抱く" },
  { word: "arouse", meaning: "（感情など）を引き起こす；を目覚めさせる" },
  { word: "doom", meaning: "〔通例受身形で〕運命にある" },
  { word: "mourn", meaning: "（を）悼む（≒ grieve）；（を）嘆く" },
  { word: "dread", meaning: "をひどく恐れる" },
  { word: "nourish", meaning: "に栄養を与える；をはぐくむ" },
  { word: "inject", meaning: "（人）に注射する，を注入する；を導入する" },
  { word: "swear", meaning: "（～を）ののしる（at）；（を）誓う（≒ vow）" },
  { word: "bid", meaning: "（～に）の値をつける（for ⇒ on）；（挨拶）を述べる" },
  { word: "corrupt", meaning: "を堕落させる；を買収する；堕落する" },
  { word: "preoccupy", meaning: "の心を奪う，を夢中にさせる" },
  { word: "browse", meaning: "（を）拾い読みする；（を）閲覧する；（商品など）を見て歩く" },
  { word: "compile", meaning: "を編集する；（資料など）をまとめる" },
  { word: "allocate", meaning: "を割り当てる，分配する" },
  { word: "offset", meaning: "を相殺する，埋め合わせる；をオフセット印刷にする" },
  { word: "restrain", meaning: "を制止する；を規制する" },
  { word: "comply", meaning: "従う，応じる" },
  { word: "expire", meaning: "期限が切れる" },
  { word: "embark", meaning: "（～に）乗り出す（on）；乗船［搭乗］する" },
  { word: "flap", meaning: "パタパタ動く；羽ばたく（≒ flutter）；をパタパタ動かす" },
  { word: "furnish", meaning: "に（～を）備えつける（with）" },
  { word: "forge", meaning: "を偽造する；（関係など）を築く；を鍛造する" },
  { word: "thrust", meaning: "を押しつける；を突き刺す；押し進む" },
  { word: "dispatch", meaning: "を派遣する；を発送する；を処理する" },
  { word: "resent", meaning: "に憤慨する" },
  { word: "reconcile", meaning: "を（～と）一致させる（with）；を和解させる" },
  { word: "allege", meaning: "を主張する" },
  { word: "oppress", meaning: "を抑圧［迫害］する；を悩ませる" },
  { word: "expel", meaning: "を追放する；を吐き出す" },
  { word: "ascend", meaning: "（を）上がる（⇔ descend ⇒ 1337）" },
  { word: "commence", meaning: "始まる；を開始する；...し始める（to do / doing）⇒ commence work 仕事［作業］を始める" },
  { word: "advent", meaning: "〔the ～〕出現，到来" },
  { word: "reign", meaning: "治世；統治" },
  { word: "diplomacy", meaning: "外交（的手腕）" },
  { word: "embassy", meaning: "大使館；大使一行" },
  { word: "exile", meaning: "亡命（者）；（国外）追放" },
  { word: "refuge", meaning: "避難（所）；保護" },
  { word: "plight", meaning: "窮状（＝ predicament）；（悪い）状態" },
  { word: "solitude", meaning: "ひとりでいること；孤独" },
  { word: "fallacy", meaning: "誤った考え，誤信；錯誤" },
  { word: "latitude", meaning: "緯度；（行動・思想などの）許容範囲" },
  { word: "eclipse", meaning: "（日食・月食などの）食；（名声などの）失墜" },
  { word: "basin", meaning: "流域；盆地，海盆；洗面器［台］" },
  { word: "erosion", meaning: "浸食；衰退" },
  { word: "archaeology", meaning: "考古学" },
  { word: "errand", meaning: "（人の）使い，使い走り；用件" },
  { word: "mercy", meaning: "慈悲；〔通例a ～〕幸運" },
  { word: "rhetoric", meaning: "修辞（法）；美辞麗句" },
  { word: "verse", meaning: "韻文（⇔ prose 散文）；詩" },
  { word: "congestion", meaning: "混雑" },
  { word: "sewage", meaning: "下水" },
  { word: "complement", meaning: "（～の）補完物，補足（to）；（文法の）補語" },
  { word: "subsidy", meaning: "補助金；報奨金" },
  { word: "mortgage", meaning: "住宅ローン；抵当（権）" },
  { word: "attorney", meaning: "【米】 弁護士；代理人" },
  { word: "outfit", meaning: "衣装一式；装備［道具］一式；組織" },
  { word: "bulk", meaning: "〔the ～〕（～の）大半（of）；大きさ；大量" },
  { word: "reunion", meaning: "再会（の集い）；再結合" },
  { word: "synthesis", meaning: "合成；総合（⇔ analysis ⇒ 363）" },
  { word: "mold", meaning: "鋳型；鋳物；性格；かび" },
  { word: "thirst", meaning: "（のどの）渇き；（～に対する）渇望（for）" },
  { word: "greed", meaning: "強欲" },
  { word: "bribe", meaning: "賄賂" },
  { word: "contempt", meaning: "軽蔑；恥辱" },
  { word: "texture", meaning: "感触，手触り；本質；質感" },
  { word: "orphan", meaning: "孤児" },
  { word: "harassment", meaning: "嫌がらせ，ハラスメント" },
  { word: "hay", meaning: "干し草" },
  { word: "doctrine", meaning: "教義；【米】（政策上の）主義" },
  { word: "holistic", meaning: "全体論の；（医療が）ホリスティックの" },
  { word: "liable", meaning: "しがちな；（～を）受けやすい（to）；責任がある" },
  { word: "earnest", meaning: "まじめな，熱心な" },
  { word: "intelligible", meaning: "（簡単に）理解できる" },
  { word: "abrupt", meaning: "突然の（≒ sudden）" },
  { word: "reckless", meaning: "無謀な；（～を）顧みない（of）" },
  { word: "furious", meaning: "激怒した；猛烈な" },
  { word: "eloquent", meaning: "雄弁な；説得力のある" },
  { word: "juvenile", meaning: "青少年の" },
  { word: "notorious", meaning: "悪名高い（≒ infamous）" },
  { word: "timid", meaning: "臆病な；内気な" },
  { word: "humid", meaning: "湿気のある（≒ muggy 蒸し暑い）" },
  { word: "contagious", meaning: "感染（性）の；病気を伝染する" },
  { word: "cynical", meaning: "冷笑的な，皮肉な" },
  { word: "dumb", meaning: "ばかげた；口のきけない；無言の" },
  { word: "monotonous", meaning: "単調な" },
  { word: "perpetual", meaning: "永続的な；ひっきりなしの" },
  { word: "dizzy", meaning: "目まいがする；当惑した" },
  { word: "weary", meaning: "疲れ果てた；（～に）うんざりした（of）" },
  { word: "numb", meaning: "麻痺した，無感覚な；ぼう然とした" },
  { word: "mortal", meaning: "致命的な（≒ fatal）；死すべき（運命の）（⇔ immortal 不死の）" },
  { word: "zealous", meaning: "熱心な；熱狂的な" },
];

export default words;