const words = [
  { word: "last", meaning: "続く、持続する、(天候・体力・食品などが)持ちこたえる" },
  { word: "affect", meaning: "に影響を及ぼす；を感動させる" },
  { word: "claim", meaning: "と主張する；を（自分のものとして）要求する" },
  { word: "ship", meaning: "を出荷する、を輸送する" },
  { word: "issue", meaning: "問題（点）；発行（物）；発表" },
  { word: "purchase", meaning: "を購入する" },
  { word: "occur", meaning: "起こる；心に浮かぶ；現れる" },
  { word: "deal", meaning: "を処理する；を商う；を分配する" },
  { word: "consume", meaning: "を消費する；を食べる，飲む" },
  { word: "present", meaning: "を提示する、を進呈する" },
  { word: "fire", meaning: "を解雇する、を首にする" },
  { word: "regard", meaning: "を見なす；を見る；を評価する" },
  { word: "fine", meaning: "に罰金を科す" },
  { word: "transfer", meaning: "を移す；を伝える；移る；乗り換える" },
  { word: "decline", meaning: "減少する；衰退する；を断る" },
  { word: "eliminate", meaning: "を取り除く" },
  { word: "indicate", meaning: "を指し示す；を述べる" },
  { word: "ensure", meaning: "を確実にする（≒make sure）；を守る" },
  { word: "expand", meaning: "（を）拡大する；（を）詳説する" },
  { word: "address", meaning: "（問題など）に対処する；に演説する；（手紙など）を（～宛てに）出す（to）" },
  { word: "identify", meaning: "を特定する；を（～と）同一視する（with）" },
  { word: "construct", meaning: "を建設する（＝build）；を構成する" },
  { word: "invest", meaning: "（を）投資する；に（～を）与える（with）" },
  { word: "obtain", meaning: "を得る" },
  { word: "struggle", meaning: "闘い；懸命の努力" },
  { word: "counter", meaning: "～と反論する、～に反対する" },
  { word: "associate", meaning: "を結び付けて考える；（～と）交際する（with）" },
  { word: "register", meaning: "を記録する，登録する；（～に）登録する（for）" },
  { word: "reveal", meaning: "を明らかにする；を見せる" },
  { word: "species", meaning: "（生物の）種；種類" },
  { word: "diet", meaning: "(日常の)食べ物、療養食" },
  { word: "site", meaning: "用地，場所；跡地；（ウェブ）サイト" },
  { word: "cell", meaning: "細胞；独房；電池" },
  { word: "facility", meaning: "施設，設備；機能；才能" },
  { word: "practice", meaning: "実践，実行；（社会の）慣習；練習" },
  { word: "resident", meaning: "居住者；滞在者" },
  { word: "option", meaning: "選択（の自由）；選択肢" },
  { word: "organ", meaning: "器官，臓器；組織；（パイプ）オルガン" },
  { word: "critic", meaning: "批判する人、批評家" },
  { word: "region", meaning: "地域；領域；部位" },
  { word: "tax", meaning: "税金、税" },
  { word: "access", meaning: "利用，入手；接近（の機会・方法・権利）" },
  { word: "virus", meaning: "ウイルス；（感染症の）病原体" },
  { word: "bill", meaning: "請求書；【英】勘定書（≒【米】check）；法案" },
  { word: "evidence", meaning: "証拠" },
  { word: "attempt", meaning: "を試みる，企てる" },
  { word: "account", meaning: "説明；勘定；口座" },
  { word: "theory", meaning: "学説；理論；原理；推測" },
  { word: "factor", meaning: "要因、要素" },
  { word: "stock", meaning: "在庫品；蓄え；株" },
  { word: "chemical", meaning: "化学の，化学的な" },
  { word: "media", meaning: "マスメディア、マスコミ" },
  { word: "income", meaning: "収入；所得" },
  { word: "supply", meaning: "を供給する" },
  { word: "shortage", meaning: "不足、欠如" },
  { word: "poverty", meaning: "貧困、欠乏" },
  { word: "criminal", meaning: "犯人、犯罪者" },
  { word: "budget", meaning: "予算；経費" },
  { word: "authority", meaning: "〔通例 the ～ties〕（関係）当局；権威；権限" },
  { word: "genome", meaning: "ゲノム" },
  { word: "atmosphere", meaning: "〔the ～〕大気；雰囲気" },
  { word: "aid", meaning: "を援助する，助ける（≒help）" },
  { word: "measure", meaning: "措置、程度、基準" },
  { word: "subject", meaning: "話題；科目；主題；被験者" },
  { word: "decade", meaning: "10年間" },
  { word: "weapon", meaning: "兵器，武器（≒arms）" },
  { word: "nutrient", meaning: "栄養分、栄養になるもの" },
  { word: "expense", meaning: "〔～s〕経費；費用；犠牲" },
  { word: "structure", meaning: "構造；体系；構造物" },
  { word: "adolescent", meaning: "青年" },
  { word: "procedure", meaning: "手順、手続き" },
  { word: "minimum", meaning: "最小限度" },
  { word: "fuel", meaning: "燃料；勢いを増加させるもの" },
  { word: "resource", meaning: "〔通例～s〕資源；〔通例～s〕資金；才覚" },
  { word: "regulation", meaning: "規則、規制" },
  { word: "contract", meaning: "契約（書）；協定" },
  { word: "insurance", meaning: "保険；保険料；保険金" },
  { word: "employment", meaning: "雇用、職" },
  { word: "ban", meaning: "を（法的に）禁止する；を締め出す" },
  { word: "vehicle", meaning: "車、(特に陸上の)乗り物、輸送機関、伝達手段" },
  { word: "soil", meaning: "土地，土壌；（悪事などの）温床" },
  { word: "cargo", meaning: "(主に船・飛行機の)積荷、貨物" },
  { word: "aircraft", meaning: "航空機、飛行機" },
  { word: "current", meaning: "現在の；現代の；通用している" },
  { word: "political", meaning: "政治（上）の" },
  { word: "significant", meaning: "重要な，重大な；意義深い" },
  { word: "effective", meaning: "効果的な、有効な" },
  { word: "military", meaning: "軍の，軍事（用）の" },
  { word: "due", meaning: "予定された；（支払）期日で；しかるべき" },
  { word: "essential", meaning: "（～に）必要不可欠な（to/for）；本質的な" },
  { word: "illegal", meaning: "違法の、非合法の" },
  { word: "immune", meaning: "（～に対して）免疫を持つ（to）；（～を）免れた（from）" },
  { word: "numerous", meaning: "非常に数の多い" },
  { word: "extreme", meaning: "極端な；極度の，過激な" },
  { word: "general", meaning: "全体の、一般的な" },
  { word: "agricultural", meaning: "農業の、農耕の" },
  { word: "overall", meaning: "総合的な；全体的な" },
  { word: "additional", meaning: "追加の、付加的な" },
  { word: "entire", meaning: "全体の，全部の（≒whole）；完全な" },
  { word: "severe", meaning: "（人・規律・事態・天気などが）厳しい；猛烈な" },
  { word: "alter", meaning: "を変える；変わる（≒change）" },
  { word: "adopt", meaning: "を採用する；（態度など）をとる；を養子にする" },
  { word: "vote", meaning: "投票；投票結果；〔the ～〕選挙権" },
  { word: "determine", meaning: "を決定する；を正確に知る" },
  { word: "enable", meaning: "（人）が...できるようにする；を可能にする" },
  { word: "conduct", meaning: "（調査・実験など）を実施する；を導く" },
  { word: "direct", meaning: "を案内する、を指揮する" },
  { word: "absorb", meaning: "を吸収する；を併合する；を夢中にさせる" },
  { word: "imply", meaning: "を暗に意味する；を必然的に伴う" },
  { word: "operate", meaning: "を操作する；機能する；手術する" },
  { word: "demonstrate", meaning: "を論証［証明］する；デモをする" },
  { word: "boost", meaning: "を押し上げる；を増加させる" },
  { word: "prove", meaning: "を証明する；判明する，わかる" },
  { word: "monitor", meaning: "を監視する；を傍受する" },
  { word: "defeat", meaning: "を負かす（≒beat）；を失敗させる" },
  { word: "protest", meaning: "（に）抗議する；を主張する" },
  { word: "target", meaning: "（到達・攻撃）目標；的" },
  { word: "preserve", meaning: "を保存する；を保持する；を保護する" },
  { word: "oppose", meaning: "に反対する；を対抗［対比］させる" },
  { word: "migrate", meaning: "移住する；（鳥などが）渡る" },
  { word: "analyze", meaning: "を分析する" },
  { word: "discourage", meaning: "（人）にやる気をなくさせる；を落胆させる" },
  { word: "confirm", meaning: "を確認する；を裏づける" },
  { word: "intend", meaning: "を意図する" },
  { word: "predict", meaning: "を予言［予測］する" },
  { word: "extend", meaning: "を伸［延］ばす；伸びる；及ぶ" },
  { word: "figure", meaning: "数字；姿；人物；図表" },
  { word: "transportation", meaning: "交通[輸送]機関、輸送" },
  { word: "institution", meaning: "機関；協会；施設；制度" },
  { word: "theft", meaning: "窃盗（罪）" },
  { word: "candidate", meaning: "（～の）候補（者）（for）；志願者" },
  { word: "mammal", meaning: "哺乳動物" },
  { word: "economist", meaning: "経済学者" },
  { word: "protein", meaning: "たんぱく質" },
  { word: "immigrant", meaning: "(外国からの)移住者、移民" },
  { word: "property", meaning: "不動産、財産、特性" },
  { word: "fund", meaning: "〔しばしば～s〕基金，資金" },
  { word: "habitat", meaning: "生息地；（人の）居住地" },
  { word: "symptom", meaning: "症状；兆候（≒sign）" },
  { word: "eruption", meaning: "勃発、噴火" },
  { word: "quantity", meaning: "量；分量" },
  { word: "ad", meaning: "広告" },
  { word: "saving", meaning: "節約、倹約、預金(額)、蓄え" },
  { word: "territory", meaning: "領土；（活動の）領域；（動物の）テリトリー" },
  { word: "threat", meaning: "脅威；（悪い）兆し；脅迫" },
  { word: "sufferer", meaning: "苦しむ人、被災者、病人" },
  { word: "emission", meaning: "排気、放出(物)" },
  { word: "executive", meaning: "重役、幹部、経営者" },
  { word: "strategy", meaning: "戦略" },
  { word: "riot", meaning: "暴動" },
  { word: "district", meaning: "地区；行政区" },
  { word: "election", meaning: "選挙" },
  { word: "medication", meaning: "(医師が処方した)薬、医薬品、薬物治療" },
  { word: "breed", meaning: "を繁殖させる，育てる；繁殖する" },
  { word: "conflict", meaning: "争い；論争；不一致" },
  { word: "productivity", meaning: "生産性" },
  { word: "organism", meaning: "有機体、生物" },
  { word: "representative", meaning: "代表者、代理人" },
  { word: "warehouse", meaning: "倉庫" },
  { word: "refund", meaning: "返金、払い戻し(金)" },
  { word: "tuition", meaning: "【主に米】 授業料；（個人）指導" },
  { word: "range", meaning: "範囲、領域" },
  { word: "victim", meaning: "犠牲（者），被害者" },
  { word: "dose", meaning: "（薬の1回分の）服用量；放射線の1回の照射量" },
  { word: "mainland", meaning: "本土" },
  { word: "waterfall", meaning: "滝" },
  { word: "satellite", meaning: "人工衛星、衛星" },
  { word: "evolution", meaning: "進化、発展、展開" },
  { word: "prey", meaning: "獲物；犠牲者" },
  { word: "bystander", meaning: "傍観者" },
  { word: "creature", meaning: "生き物、(特に人以外の)動物" },
  { word: "civilization", meaning: "文明" },
  { word: "tribe", meaning: "部族；仲間" },
  { word: "permission", meaning: "許可、承認" },
  { word: "barrier", meaning: "（～に対する）障壁（against/to）；防壁" },
  { word: "wage", meaning: "賃金、給料" },
  { word: "drone", meaning: "ドローン、(無線操作の)無人機" },
  { word: "appearance", meaning: "外観、出現" },
  { word: "embassy", meaning: "大使館；大使一行" },
  { word: "skeleton", meaning: "骨格；骨組み；概略" },
  { word: "wildlife", meaning: "野生生物" },
  { word: "potential", meaning: "潜在的な；可能性を秘めた" },
  { word: "limited", meaning: "限定された、わずかの" },
  { word: "rural", meaning: "田舎の（⇔urban），田園の" },
  { word: "advanced", meaning: "進歩した、前進した、上級の" },
  { word: "beneficial", meaning: "有益な、有利な" },
  { word: "genetic", meaning: "遺伝子の" },
  { word: "radical", meaning: "急進的な；根本的な" },
  { word: "hostile", meaning: "敵意のある（⇔friendly 友好的な）" },
  { word: "fit", meaning: "健康な、元気な、ふさわしい" },
  { word: "long-term", meaning: "長期にわたる、長期的な" },
  { word: "Arctic", meaning: "北極の" },
  { word: "minor", meaning: "重要でない；小さい" },
  { word: "risky", meaning: "危険な" },
  { word: "complex", meaning: "複雑な、複合(体)の" },
  { word: "competitive", meaning: "競争力のある、格安の、競争の" },
  { word: "immediate", meaning: "即座の；当面の；すぐそばの；直接の" },
  { word: "religious", meaning: "宗教(上)の、信仰があつい" },
  { word: "related", meaning: "関連した、関係のある" },
  { word: "affordable", meaning: "手頃な、安価な" },
  { word: "donate", meaning: "を寄付する；（臓器・血液）を提供する" },
  { word: "lessen", meaning: "を減らす" },
  { word: "manufacture", meaning: "を製造する；をでっち上げる" },
  { word: "commute", meaning: "通勤［通学］する" },
  { word: "exaggerate", meaning: "（を）誇張する；を強調する" },
  { word: "suspect", meaning: "ではないかと思う；（人）を疑う" },
  { word: "acquire", meaning: "を得る；を習得する" },
  { word: "reintroduce", meaning: "(動植物など)をかつての分布域に再導入する、(制度など)を復活させる" },
  { word: "reschedule", meaning: "の日時を変更する" },
  { word: "adapt", meaning: "適応する；を（～に）適合させる（to）" },
  { word: "generate", meaning: "を生み出す；（電気など）を発生させる" },
  { word: "guarantee", meaning: "を保証する" },
  { word: "dump", meaning: "を投棄する；をどさっと落とす" },
  { word: "update", meaning: "を最新のものにする；をアップデートする" },
  { word: "classify", meaning: "を分類する；を機密扱いにする" },
  { word: "acknowledge", meaning: "（事実など）を認める（≒admit)" },
  { word: "enforce", meaning: "を施行［実施］する；を（～に）強制する（on/upon）" },
  { word: "renew", meaning: "を更新する；（資源）を再生する" },
  { word: "overlook", meaning: "を見落とす；を大目に見る；を見渡す" },
  { word: "evaluate", meaning: "を評価する；を査定する" },
  { word: "commit", meaning: "献身する；（罪など）を犯す；を投入する" },
  { word: "argument", meaning: "議論、口論" },
  { word: "archaeologist", meaning: "考古学者" },
  { word: "reputation", meaning: "評判；名声" },
  { word: "fossil", meaning: "化石；時代遅れの人［物］" },
  { word: "status", meaning: "地位；状態" },
  { word: "contrast", meaning: "（～との）対照（with/to）" },
  { word: "workplace", meaning: "職場" },
  { word: "equality", meaning: "平等" },
  { word: "colleague", meaning: "（職場の）同僚" },
  { word: "assistance", meaning: "援助、支援" },
  { word: "luxury", meaning: "ぜいたく（品）；〔形容詞的に〕豪華な" },
  { word: "outbreak", meaning: "発生，勃発" },
  { word: "council", meaning: "（地方）議会；評議会；（公の）会議" },
  { word: "pottery", meaning: "陶器類、焼き物類" },
  { word: "assignment", meaning: "任務、宿題、割り当て" },
  { word: "particle", meaning: "（微）粒子；ほんのわずか" },
  { word: "radiation", meaning: "放射能，放射線" },
  { word: "priority", meaning: "優先（事項）" },
  { word: "content", meaning: "内容，中身；コンテンツ" },
  { word: "destination", meaning: "(旅行などの)目的地、行き先" },
  { word: "mine", meaning: "鉱山、地雷" },
  { word: "injury", meaning: "傷害、けが" },
  { word: "lottery", meaning: "宝くじ、抽選" },
  { word: "feature", meaning: "特徴、特集記事" },
  { word: "labor", meaning: "労働、労働力" },
  { word: "diabetes", meaning: "糖尿病" },
  { word: "bulb", meaning: "電球、球根" },
  { word: "résumé", meaning: "履歴書[≒CV]、要約" },
  { word: "mud", meaning: "ぬかるみ、泥" },
  { word: "psychology", meaning: "心理学；心理（状態）" },
  { word: "corporation", meaning: "（大）企業；法人" },
  { word: "ecosystem", meaning: "生態系" },
  { word: "promotion", meaning: "昇進、促進、販売促進" },
  { word: "administration", meaning: "管理（部）；行政；政府（機関）" },
  { word: "complaint", meaning: "苦情、不平" },
  { word: "debt", meaning: "借金，負債；恩義" },
  { word: "requirement", meaning: "必要条件、必需品" },
  { word: "workforce", meaning: "労働人口，総労働力；全従業員（数）" },
  { word: "preference", meaning: "他より好むこと、好み" },
  { word: "refugee", meaning: "難民、亡命者" },
  { word: "inhabitant", meaning: "居住者、住民" },
  { word: "subscription", meaning: "予約購読(料)、寄付(金)" },
  { word: "recipient", meaning: "受け取る人；（臓器などの）被提供者" },
  { word: "shift", meaning: "を変える，移す；変わる；移動する" },
  { word: "vessel", meaning: "船舶；容器；（体液が通る）脈管" },
  { word: "ingredient", meaning: "材料，成分；（成功の）要因" },
  { word: "qualified", meaning: "有能な、資格のある、適任の" },
  { word: "widespread", meaning: "広範囲にわたる；広く普及した" },
  { word: "alternative", meaning: "代替の、どちらか一方の" },
  { word: "harsh", meaning: "厳しい；（光・色・味などが）不快な" },
  { word: "enormous", meaning: "莫大な，巨大な" },
  { word: "specific", meaning: "明確な、特定の" },
  { word: "artificial", meaning: "人工の（⇔natural 自然の）；不自然な" },
  { word: "toxic", meaning: "有毒な；中毒性の" },
  { word: "flexible", meaning: "融通の利く，柔軟な" },
  { word: "latest", meaning: "最新の、最近の" },
  { word: "former", meaning: "以前の、元の" },
  { word: "capable", meaning: "能力がある；有能な" },
  { word: "practical", meaning: "実践的な、実際的な" },
  { word: "mechanical", meaning: "機械の；機械的な" },
  { word: "federal", meaning: "連邦（政府）の" },
  { word: "aggressive", meaning: "攻撃的な；意欲的な" },
  { word: "adequate", meaning: "十分な；適切な" },
  { word: "unexpected", meaning: "思いがけない，不意の" },
  { word: "attractive", meaning: "魅力的な" },
  { word: "sufficient", meaning: "十分な（for ～に" },
  { word: "costly", meaning: "費用のかかる、高価な、犠牲[損失、労力]の大きな" },
  { word: "eventually", meaning: "ついに(は)、結局(は)" },
  { word: "otherwise", meaning: "そうでなければ、そのほかの点では" },
  { word: "previously", meaning: "以前に" },
  { word: "relatively", meaning: "比較的(に)、相対的に" },
  { word: "consequently", meaning: "その結果(として)、従って" },
  { word: "constantly", meaning: "絶えず、常に" },
  { word: "typically", meaning: "通常、概して、典型的に" },
  { word: "barely", meaning: "かろうじて、ほとんど～ない" },
  { word: "despite", meaning: "～にもかかわらず" },
  { word: "per", meaning: "～につき、～ごとに" },
  { word: "beneath", meaning: "～の下に[の]" },
  { word: "whereas", meaning: "～するのに（対し），～する一方" },
  { word: "post", meaning: "(インターネットで)(情報・メッセージ)を投稿する、(ビラなど)を張る" },
  { word: "reject", meaning: "を拒否する" },
  { word: "consult", meaning: "（に）相談する；を参照する" },
  { word: "obey", meaning: "に従う；に服従する" },
  { word: "engage", meaning: "を従事させる；を（～として）雇う（as）；（～に）従事する（in/with）" },
  { word: "restore", meaning: "を回復させる；を修復する" },
  { word: "colonize", meaning: "を植民地化する、を入植させる" },
  { word: "interact", meaning: "影響し合う；相互に作用する" },
  { word: "inspire", meaning: "（人）を奮起させる；を喚起する" },
  { word: "sue", meaning: "を告訴する；（～を求めて）訴訟を起こす（for）" },
  { word: "estimate", meaning: "～と推定する、を見積もる" },
  { word: "strengthen", meaning: "を(より)強くする" },
  { word: "carve", meaning: "を彫る；を切り開く；（肉）を切り分ける" },
  { word: "convince", meaning: "を納得［確信］させる" },
  { word: "propose", meaning: "を提案する；をもくろむ；結婚を申し込む" },
  { word: "blame", meaning: "を責める；の責任を負わせる" },
  { word: "collapse", meaning: "崩壊する；（人が）倒れる；を折り畳む" },
  { word: "import", meaning: "を輸入する；を取り込む" },
  { word: "load", meaning: "に積む；に負わせる" },
  { word: "pollute", meaning: "を汚染する" },
  { word: "spot", meaning: "(特定の)場所、斑点、しみ" },
  { word: "prescription", meaning: "処方箋、処方" },
  { word: "duty", meaning: "義務；〔しばしば～ties〕職務；関税" },
  { word: "union", meaning: "組合、統合、団結" },
  { word: "concept", meaning: "概念" },
  { word: "root", meaning: "根本、源、(植物の)根" },
  { word: "survival", meaning: "生き残ること、生き延びること" },
  { word: "maintenance", meaning: "保守、整備、維持" },
  { word: "formation", meaning: "形成；構成（物）；隊列" },
  { word: "educator", meaning: "教育者、教師" },
  { word: "kidney", meaning: "腎臓" },
  { word: "nutrition", meaning: "栄養（の摂取）" },
  { word: "brand", meaning: "ブランド、銘柄" },
  { word: "storage", meaning: "保管、貯蔵(法)、収容力" },
  { word: "firm", meaning: "確固たる；堅固な；安定した" },
  { word: "statistics", meaning: "統計；統計学" },
  { word: "toll", meaning: "損害（の程度）；死傷者数；通行料" },
  { word: "tip", meaning: "助言，秘訣；チップ；先端" },
  { word: "CEO", meaning: "最高経営責任者" },
  { word: "circumstance", meaning: "〔通例～s〕状況，事情；境遇" },
  { word: "outsider", meaning: "部外者、門外漢" },
  { word: "reduction", meaning: "減少、削減" },
  { word: "settlement", meaning: "開拓地、解決、合意" },
  { word: "divorce", meaning: "離婚；分離" },
  { word: "likelihood", meaning: "可能性、見込み" },
  { word: "livestock", meaning: "(牛・羊・豚などの)家畜(類)" },
  { word: "possession", meaning: "所有物、財産、所有" },
  { word: "plot", meaning: "（小説などの）筋；陰謀" },
  { word: "category", meaning: "部類，区分；範疇" },
  { word: "welfare", meaning: "福祉，幸福" },
  { word: "moisture", meaning: "水分；湿気" },
  { word: "obesity", meaning: "（病的な)肥満" },
  { word: "grant", meaning: "（人）に（許可・権利など）を与える；を認める" },
  { word: "layer", meaning: "層" },
  { word: "secretary", meaning: "秘書" },
  { word: "anxiety", meaning: "不安、心配" },
  { word: "ownership", meaning: "所有権、所有者であること" },
  { word: "foundation", meaning: "基礎、基盤" },
  { word: "division", meaning: "不和、分割、部門、仕切り" },
  { word: "establishment", meaning: "設立、制定、組織" },
  { word: "conservation", meaning: "（動植物などの）保護；保存" },
  { word: "murder", meaning: "殺人" },
  { word: "presence", meaning: "存在；出席；面前" },
  { word: "paradox", meaning: "逆説；矛盾" },
  { word: "prisoner", meaning: "囚人" },
  { word: "surgeon", meaning: "外科医" },
  { word: "frequency", meaning: "頻度、しばしば起こること" },
  { word: "port", meaning: "港" },
  { word: "reception", meaning: "反応；宴会；受付；受信（状態）" },
  { word: "coworker", meaning: "同僚、仕事仲間" },
  { word: "rust", meaning: "さび" },
  { word: "athletics", meaning: "スポーツ、運動競技" },
  { word: "voyage", meaning: "(ゆったりした長い)旅、船旅" },
  { word: "ecologist", meaning: "生態学者、環境保護論者" },
  { word: "soul", meaning: "精神；魂，霊魂；生気" },
  { word: "isolated", meaning: "孤立した、孤独な" },
  { word: "biased", meaning: "偏った、偏見を持った" },
  { word: "multiple", meaning: "多様な；種々雑多な" },
  { word: "critical", meaning: "批判的な、重大な" },
  { word: "remote", meaning: "（～から）遠く離れた（from）；かけ離れた" },
  { word: "encouraging", meaning: "勇気づける、望みを持たせる" },
  { word: "underground", meaning: "地下の、秘密の" },
  { word: "stable", meaning: "安定した；動じない" },
  { word: "domestic", meaning: "家庭の；国内の；（動物が）飼いならされた" },
  { word: "shallow", meaning: "浅い（⇔deep 深い）；浅薄な" },
  { word: "willing", meaning: "～するのをいとわない、快く～する" },
  { word: "superior", meaning: "よりすぐれた" },
  { word: "profitable", meaning: "利益になる、有益な" },
  { word: "solid", meaning: "しっかりした；硬い；固体の" },
  { word: "tremendous", meaning: "途方もない，莫大な；すばらしい" },
  { word: "intellectual", meaning: "知的な、知性の" },
  { word: "chief", meaning: "主な、最高位の" },
  { word: "steady", meaning: "着実な，一定の；安定した" },
  { word: "evil", meaning: "邪悪な；有害な" },
  { word: "coastal", meaning: "沿岸(地方)の" },
  { word: "dairy", meaning: "〔集合的に〕乳製品；乳製品加工所［販売者］" },
  { word: "digestive", meaning: "消化の" },
  { word: "loyal", meaning: "（～に）忠実な（to）；誠実な" },
  { word: "sensory", meaning: "感覚の" },
  { word: "fancy", meaning: "（気まぐれな）好み；空想；思いつき" },
  { word: "spoil", meaning: "を台無しにする；を甘やかす；だめになる" },
  { word: "stimulate", meaning: "を刺激する" },
  { word: "distract", meaning: "（注意など）をそらす" },
  { word: "bargain", meaning: "買い得品；取引；契約" },
  { word: "emerge", meaning: "明らかになる、現れる" },
  { word: "browse", meaning: "（を）拾い読みする；（を）閲覧する；（商品など）を見て歩く" },
  { word: "define", meaning: "を定義する、を明確に示す" },
  { word: "adjust", meaning: "を調整する；を適合させる；順応する" },
  { word: "deserve", meaning: "に値する" },
  { word: "undergo", meaning: "を経験する；（手術など）を受ける；に耐える" },
  { word: "contradict", meaning: "と矛盾する；に反対意見を言う" },
  { word: "withdraw", meaning: "を引き出す；を撤回する；撤退する" },
  { word: "accompany", meaning: "に同行する；に付随する" },
  { word: "infect", meaning: "(人)を感染させる、を汚染する" },
  { word: "rebel", meaning: "反逆者" },
  { word: "convert", meaning: "を変える；を改宗［転向］させる；を交換する" },
  { word: "calculate", meaning: "を計算する；を予測する" },
  { word: "utilize", meaning: "を利用する（≒make use of）" },
  { word: "admit", meaning: "～と(しぶしぶ)認める、を中に入れる" },
  { word: "punish", meaning: "を罰する；に損傷を与える" },
  { word: "approve", meaning: "賛成する；を承認する" },
  { word: "owe", meaning: "に借りがある；のおかげである" },
  { word: "proceed", meaning: "進む，進行する；（～を）続行する（with）" },
  { word: "navigate", meaning: "（を）誘導する；（を）操縦する；（を）航行する" },
  { word: "postpone", meaning: "を延期する（≒put off）" },
  { word: "swallow", meaning: "（を）飲み込む；をうのみにする；に耐える" },
  { word: "tailor", meaning: "を合わせて作る" },
  { word: "overhear", meaning: "を偶然耳にする" },
  { word: "consequence", meaning: "結果、重要さ" },
  { word: "application", meaning: "申請書、申し込み、適用" },
  { word: "workout", meaning: "運動、(運動競技の)練習" },
  { word: "obstacle", meaning: "（～に対する）障害（物）（to）" },
  { word: "treaty", meaning: "（国家間の）条約；協定" },
  { word: "deforestation", meaning: "森林伐採" },
  { word: "infrastructure", meaning: "基本的施設；（経済）基盤" },
  { word: "contribution", meaning: "貢献、寄付(金)" },
  { word: "congestion", meaning: "混雑" },
  { word: "exposure", meaning: "身をさらすこと、暴露" },
  { word: "blow", meaning: "強打、打撃、災難" },
  { word: "participation", meaning: "参加" },
  { word: "crisis", meaning: "危機、難局" },
  { word: "ancestor", meaning: "先祖、祖先" },
  { word: "architect", meaning: "建築家、設計者" },
  { word: "existence", meaning: "存在、生存" },
  { word: "deposit", meaning: "を置く；を預ける；を堆積させる" },
  { word: "finance", meaning: "金融、財政(学)" },
  { word: "awareness", meaning: "認識、意識" },
  { word: "intake", meaning: "摂取量；受け入れ数；取り入れること" },
  { word: "witness", meaning: "目撃者；証人；証拠，証言" },
  { word: "coverage", meaning: "報道、(保険の)補償範囲、適用範囲" },
  { word: "lawsuit", meaning: "(民事)訴訟" },
  { word: "session", meaning: "集まり；（議会の）会期；（開会中の）議会" },
  { word: "means", meaning: "〔単数・複数扱い〕手段；〔複数扱い〕資力，収入" },
  { word: "pioneer", meaning: "先駆者、草分け、(未開地の)開拓者" },
  { word: "satisfaction", meaning: "満足" },
  { word: "basis", meaning: "根拠、基礎" },
  { word: "element", meaning: "(構成)要素、成分" },
  { word: "phenomenon", meaning: "現象、事象" },
  { word: "scale", meaning: "規模、程度" },
  { word: "journal", meaning: "(専門)雑誌、日刊[週刊]新聞" },
  { word: "grain", meaning: "穀物；粒；きめ" },
  { word: "continent", meaning: "大陸、(イギリスから見て)ヨーロッパ大陸" },
  { word: "headquarters", meaning: "本社、(軍・警察・会社などの)本部" },
  { word: "globalization", meaning: "国際化" },
  { word: "brochure", meaning: "パンフレット、小冊子" },
  { word: "inspection", meaning: "検査、点検" },
  { word: "attendance", meaning: "出席[入場]者数、出席" },
  { word: "copper", meaning: "銅" },
  { word: "dozen", meaning: "12(個)、１ダース" },
  { word: "flu", meaning: "インフルエンザ" },
  { word: "burial", meaning: "埋葬" },
  { word: "mold", meaning: "鋳型；鋳物；性格；かび" },
  { word: "patch", meaning: "（～の）部分，斑点；継ぎ；貼り薬" },
  { word: "diagram", meaning: "図(表)" },
  { word: "placement", meaning: "(就職先・学校・里親などの)斡旋、配置" },
  { word: "shame", meaning: "恥；残念なこと" },
  { word: "wheelchair", meaning: "車椅子" },
  { word: "experienced", meaning: "熟練した" },
  { word: "initial", meaning: "初めの" },
  { word: "mainstream", meaning: "（活動・思潮などの）主流；大勢" },
  { word: "appropriate", meaning: "適切な" },
  { word: "fake", meaning: "偽の；見せかけだけの" },
  { word: "alert", meaning: "警戒して；敏速な" },
  { word: "fatal", meaning: "致命的な、破滅的な" },
  { word: "nutritious", meaning: "栄養になる" },
  { word: "sophisticated", meaning: "高性能の，精巧な；洗練された" },
  { word: "automatic", meaning: "自動の" },
  { word: "raw", meaning: "生の；未加工の" },
  { word: "slight", meaning: "わずかな；取るに足らない" },
  { word: "man-made", meaning: "(物質などが)合成の、人工の" },
  { word: "aging", meaning: "高齢化が進む、老朽化している" },
  { word: "spiritual", meaning: "精神の（⇔material）；霊的な" },
  { word: "endangered", meaning: "(動植物が)絶滅の危機にある" },
  { word: "sticky", meaning: "ねばねばの、粘着性の" },
  { word: "fertile", meaning: "肥沃な（⇔barren 不毛の）；多産の" },
  { word: "elsewhere", meaning: "どこかほかのところへ[に、へ]" },
  { word: "altogether", meaning: "完全に" },
  { word: "strictly", meaning: "厳格に、厳しく" },
  { word: "beforehand", meaning: "前もって、あらかじめ" },
  { word: "likewise", meaning: "同様に（≒in the same way）" },
  { word: "detect", meaning: "を感知する；を見つけ出す；に気づく" },
  { word: "combat", meaning: "戦闘；対立" },
  { word: "pose", meaning: "（危険）を引き起こす；（問題など）を提起する；（～を）装う（as）" },
  { word: "emphasize", meaning: "を強調する；を重視する" },
  { word: "highlight", meaning: "を目立たせる，強調する" },
  { word: "resist", meaning: "に抵抗する；〔通例否定文で〕を我慢する" },
  { word: "exceed", meaning: "を超える；に勝る" },
  { word: "relocate", meaning: "(住居・事務所・住民など)を移転[移動]させる" },
  { word: "disprove", meaning: "の誤りを証明する、の反証を挙げる" },
  { word: "crawl", meaning: "はう；ゆっくり進む" },
  { word: "foster", meaning: "をはぐくむ；を養育する；を心に抱く" },
  { word: "harass", meaning: "を絶えず悩ます、を苦しめる" },
  { word: "magnify", meaning: "を拡大する、を誇張する" },
  { word: "sneak", meaning: "こっそり動く" },
  { word: "stray", meaning: "はぐれる，（道に）迷う" },
  { word: "worsen", meaning: "を悪化させる；悪化する（≒deteriorate）" },
  { word: "advocate", meaning: "を主張する；を擁護する" },
  { word: "evacuate", meaning: "を避難させる、から立ち退く" },
  { word: "verify", meaning: "の正しさを証明［確認］する" },
  { word: "abuse", meaning: "乱用；虐待" },
  { word: "scatter", meaning: "をまき散らす；分散する" },
  { word: "endorse", meaning: "を推奨する" },
  { word: "modify", meaning: "を修正する；を緩和する" },
  { word: "penetrate", meaning: "（に）浸透する；（に）進出する；（を）貫く；（を）見抜く" },
  { word: "conform", meaning: "順応する；一致する" },
  { word: "leave", meaning: "休暇" },
  { word: "tissue", meaning: "（生物の）組織" },
  { word: "gut", meaning: "腸、消化管、内臓" },
  { word: "lightning", meaning: "雷、稲妻" },
  { word: "camel", meaning: "ラクダ、黄褐色" },
  { word: "antioxidant", meaning: "抗酸化物質、酸化防止剤" },
  { word: "disorder", meaning: "障害，（心身の）不調；混乱" },
  { word: "cattle", meaning: "〔集合的に〕牛" },
  { word: "oath", meaning: "誓い、誓約" },
  { word: "monument", meaning: "記念碑，遺跡；金字塔" },
  { word: "heating", meaning: "暖房(装置)" },
  { word: "germ", meaning: "細菌、病原菌" },
  { word: "legend", meaning: "伝説、言い伝え、伝説的な人物" },
  { word: "auditorium", meaning: "(学校の)講堂、公会堂" },
  { word: "therapy", meaning: "療法；心理療法" },
  { word: "heritage", meaning: "遺産" },
  { word: "invasion", meaning: "侵害、侵入" },
  { word: "instruction", meaning: "(製品の)使用書、指示、教育" },
  { word: "extinction", meaning: "(家系・種などの)絶滅、消滅" },
  { word: "creativity", meaning: "創造性、独創性" },
  { word: "plantation", meaning: "(熱帯・亜熱帯の)(大)農園" },
  { word: "drought", meaning: "干ばつ；（慢性的な）不足" },
  { word: "wealth", meaning: "財産、富、豊富" },
  { word: "reminder", meaning: "思い出させるもの、記念物[品]" },
  { word: "inquiry", meaning: "問い合わせ、質問、調査" },
  { word: "investigation", meaning: "(詳しい)調査、研究" },
  { word: "boundary", meaning: "境界（線）；〔通例～ries〕限界" },
  { word: "compartment", meaning: "(列車・客室などの仕切った)区画[部屋]" },
  { word: "substitute", meaning: "を代わりに使う；（～の）代理をする（for）" },
  { word: "hybrid", meaning: "雑種の；混成の" },
  { word: "characteristic", meaning: "特徴" },
  { word: "routine", meaning: "決まり切った仕事；いつもの手順" },
  { word: "edge", meaning: "優勢、刃、端" },
  { word: "incident", meaning: "出来事，事件；紛争" },
  { word: "clue", meaning: "（～の）手がかり（to/about）；（パズルの）ヒント" },
  { word: "removal", meaning: "除去、移動" },
  { word: "outcome", meaning: "結果" },
  { word: "altitude", meaning: "高度，標高" },
  { word: "closure", meaning: "(工場・学校などの)閉鎖" },
  { word: "compound", meaning: "を悪化させる；を合成する；を混合する" },
  { word: "surplus", meaning: "余剰（⇔shortage 不足），過剰；黒字" },
  { word: "vaccine", meaning: "ワクチン" },
  { word: "reference", meaning: "言及、参照" },
  { word: "obligation", meaning: "義務、責任" },
  { word: "ritual", meaning: "儀式；（日常の）習慣的行為" },
  { word: "mean", meaning: "意地の悪い、不親切な" },
  { word: "coral", meaning: "サンゴ(製)の" },
  { word: "novel", meaning: "斬新な、目新しい" },
  { word: "relevant", meaning: "関係がある；適切な" },
  { word: "efficient", meaning: "効率的な、有能な" },
  { word: "fragile", meaning: "壊れやすい；虚弱な" },
  { word: "impressive", meaning: "印象的な、感動的な" },
  { word: "offensive", meaning: "不快な、攻撃的な" },
  { word: "distinct", meaning: "明らかに異なる；明瞭な" },
  { word: "temporary", meaning: "一時的な（⇔permanent）" },
  { word: "arrogant", meaning: "横柄な，傲慢な" },
  { word: "spacious", meaning: "広々とした" },
  { word: "reasonable", meaning: "筋の通った、分別のある、(値段などが)手ごろな" },
  { word: "substantial", meaning: "(数量などが)かなりの、重要な、実質的な" },
  { word: "disabled", meaning: "障害のある；障害者用の" },
  { word: "straightforward", meaning: "単純な；率直な" },
  { word: "tame", meaning: "飼いならされた，人に慣れた；退屈な" },
  { word: "mandatory", meaning: "義務的な、強制的な、命令の" },
  { word: "edible", meaning: "食用の，食べられる" },
  { word: "outstanding", meaning: "際立った；未払いの；未解決の" },
  { word: "deadly", meaning: "致命的な、命にかかわる" },
  { word: "petty", meaning: "低級の、心の狭い、取るに足らない" },
  { word: "definitely", meaning: "間違いなく、確かに" },
  { word: "roughly", meaning: "おおよそ、乱暴に" },
  { word: "virtually", meaning: "ほとんど、実質的に" },
  { word: "apparently", meaning: "(真偽のほどはともかく)聞いた[見た]ところでは、どうやら" },
  { word: "unfairly", meaning: "不当に、不公平に" },
  { word: "briefly", meaning: "少しの間に、簡潔に" },
  { word: "aside", meaning: "わきに、別にして、考慮に入れないで" },
  { word: "legally", meaning: "法的に、合法的に" },
  { word: "resort", meaning: "（好ましくない手段に）訴える，頼る（to）" },
  { word: "submit", meaning: "を提出する；（～に）従う（to）" },
  { word: "originate", meaning: "由来する、生じる、始まる" },
  { word: "regret", meaning: "を後悔する、を遺憾に思う" },
  { word: "cooperate", meaning: "協力する" },
  { word: "revise", meaning: "を修正する；を改訂する" },
  { word: "restrict", meaning: "を制限する" },
  { word: "occupy", meaning: "（空間・時間）を占める；を占領する" },
  { word: "fade", meaning: "薄れる；衰える" },
  { word: "relieve", meaning: "を和らげる；〔受身形で〕（...して）安心する（to do）；を解放する" },
  { word: "suppress", meaning: "を抑える；を抑圧する" },
  { word: "starve", meaning: "飢える；（～を）渇望する（for）；を飢えさせる" },
  { word: "scratch", meaning: "を引っかく；を取り消す，削除する" },
  { word: "unite", meaning: "団結する、一体化する" },
  { word: "grip", meaning: "を握る；をとらえる" },
  { word: "surrender", meaning: "を放棄する，引き渡す；（～に）屈する（to）" },
  { word: "twist", meaning: "をねじる，ひねる；を歪曲する" },
  { word: "remodel", meaning: "を改装する、を改造する" },
  { word: "triple", meaning: "３倍になる、を３倍にする" },
  { word: "drown", meaning: "溺死する；を水浸しにする" },
  { word: "lean", meaning: "傾く；寄りかかる；をもたせかける" },
  { word: "soak", meaning: "を浸す；をずぶぬれにする；浸る" },
  { word: "hover", meaning: "(鳥・昆虫・ヘリコプターなどが)空中(の一点)に止まる" },
  { word: "interrupt", meaning: "を中断させる；（の）邪魔をする" },
  { word: "socialize", meaning: "(社会的に)交際する" },
  { word: "termite", meaning: "シロアリ" },
  { word: "microbe", meaning: "微生物；細菌" },
  { word: "beverage", meaning: "（水以外の）飲み物，飲料" },
  { word: "paperwork", meaning: "(必要)書類、書類事務" },
  { word: "descendant", meaning: "子孫" },
  { word: "sculpture", meaning: "彫刻（作品）" },
  { word: "handout", meaning: "(講演・授業などの)配布物、プリント" },
  { word: "replacement", meaning: "交換、交替、代わりの人[もの]" },
  { word: "minister", meaning: "大臣" },
  { word: "stream", meaning: "小川" },
  { word: "predator", meaning: "捕食動物；略奪者" },
  { word: "observer", meaning: "監視員、観察者" },
  { word: "commission", meaning: "代理手数料、歩合、委員会" },
  { word: "committee", meaning: "委員会" },
  { word: "junk", meaning: "がらくた、つまらないもの" },
  { word: "departure", meaning: "出発" },
  { word: "description", meaning: "描写、説明" },
  { word: "supervisor", meaning: "監督者；指導教員" },
  { word: "guidance", meaning: "指導、案内" },
  { word: "landscape", meaning: "眺め、風景、景色" },
  { word: "crew", meaning: "(船の)乗組員、(飛行機・列車などの)乗務員" },
  { word: "drain", meaning: "（液体）を流出させる；（液体が）流れ出る" },
  { word: "stereotype", meaning: "固定観念、ステレオタイプ" },
  { word: "edition", meaning: "(刊行物の)版" },
  { word: "graphic", meaning: "図、挿絵" },
  { word: "pathway", meaning: "小道、細道" },
  { word: "reunion", meaning: "再会（の集い）；再結合" },
  { word: "cliff", meaning: "崖、絶壁" },
  { word: "coordinator", meaning: "コーディネーター、取りまとめ役、責任者" },
  { word: "depth", meaning: "深さ、深み" },
  { word: "liver", meaning: "肝臓" },
  { word: "monopoly", meaning: "独占（権）" },
  { word: "usage", meaning: "（使）用法；語法；習慣" },
  { word: "chart", meaning: "図，グラフ；海図；ヒットチャート" },
  { word: "expectancy", meaning: "期待、見込み" },
  { word: "nowhere", meaning: "どの場所も～ない" },
  { word: "courthouse", meaning: "裁判所(の建物)" },
  { word: "cove", meaning: "入江、小湾" },
  { word: "dock", meaning: "埠頭、波止場、(艦船の)ドック" },
  { word: "ministry", meaning: "省" },
  { word: "inflammation", meaning: "炎症、点火、引火" },
  { word: "cholesterol", meaning: "コレステロール" },
  { word: "gender", meaning: "(社会的・文化的)性別、ジェンダー" },
  { word: "depression", meaning: "うつ病、意気消沈、不景気" },
  { word: "stem", meaning: "（草木の）茎，幹" },
  { word: "personnel", meaning: "〔集合的に〕職員，社員" },
  { word: "controversy", meaning: "論争" },
  { word: "recognition", meaning: "(人・物が)それと分かること、認めること、認識" },
  { word: "applicant", meaning: "応募者、志願者" },
  { word: "anthropologist", meaning: "人類学者" },
  { word: "sewage", meaning: "下水" },
  { word: "acceptable", meaning: "受け入れられる、容認できる" },
  { word: "nuclear", meaning: "原子力利用の、核エネルギーの" },
  { word: "moral", meaning: "道徳(上)の、倫理的な" },
  { word: "marine", meaning: "海の；船舶の" },
  { word: "conventional", meaning: "伝統的な、型にはまった" },
  { word: "awful", meaning: "ひどい；嫌な；ものすごい" },
  { word: "consistent", meaning: "着実な、安定した、首尾一貫した" },
  { word: "primitive", meaning: "原始的な；未開の" },
  { word: "mature", meaning: "成熟した；熟した" },
  { word: "unfamiliar", meaning: "（～に）不慣れな（with）；（～に）（よく）知られていない（to）" },
  { word: "impractical", meaning: "実用的ではない、非現実的な" },
  { word: "unpredictable", meaning: "変わりやすい、予測できない" },
  { word: "misleading", meaning: "誤解させる、紛らわしい" },
  { word: "plentiful", meaning: "豊富な、十分な" },
  { word: "Mediterranean", meaning: "地中海(沿岸地域)の" },
  { word: "unsafe", meaning: "安全でない、危険な" },
  { word: "bare", meaning: "露出した、裸の" },
  { word: "feeble", meaning: "病弱な、(体が)弱々しい" },
  { word: "horrible", meaning: "実にひどい、ぞっとする" },
  { word: "scenic", meaning: "景色の良い" },
  { word: "supplementary", meaning: "補足の、追加の" },
  { word: "nosy", meaning: "詮索好きな、おせっかいな" },
  { word: "intermediate", meaning: "中級の；中間の" },
  { word: "universal", meaning: "(あらゆる人に)共通の、全員の、普遍的な" },
  { word: "capture", meaning: "を捕らえる、を捕虜にする" },
  { word: "arise", meaning: "起こる、出現する" },
  { word: "implement", meaning: "を実行［実施］する" },
  { word: "reproduce", meaning: "を複製する；を繁殖させる；繁殖する" },
  { word: "seize", meaning: "をつかむ；を奪い取る；を没収する" },
  { word: "dominate", meaning: "を支配する、優勢である" },
  { word: "complicate", meaning: "を複雑にする" },
  { word: "scan", meaning: "を走査する；をざっと見る；を注意深く調べる" },
  { word: "negotiate", meaning: "交渉する；を（交渉して）取り決める" },
  { word: "illustrate", meaning: "を説明する、を例示する" },
  { word: "encounter", meaning: "に遭遇する" },
  { word: "confine", meaning: "を限定する；〔通例受身形で〕閉じ込められる" },
  { word: "transmit", meaning: "を伝える；（電波・信号など）を送る" },
  { word: "administer", meaning: "を管理する、を経営する、を治める、(治療)を施す" },
  { word: "ease", meaning: "を和らげる、緩和する" },
  { word: "resume", meaning: "（を）再開する；を取り戻す" },
  { word: "pursue", meaning: "を追跡する、を追求する" },
  { word: "decay", meaning: "腐敗する（≒rot）；（徐々に）衰える" },
  { word: "shrink", meaning: "縮む，縮小する；減少する；ひるむ" },
  { word: "cherish", meaning: "を大切にする；を心に抱く" },
  { word: "launch", meaning: "を売り出す、を開始する、(ロケットなど)を発射する" },
  { word: "accommodate", meaning: "を収容する；を（～に）適応させる（to）" },
  { word: "withstand", meaning: "に耐える" },
  { word: "halt", meaning: "を止める；止まる" },
  { word: "transform", meaning: "を大きく変える" },
  { word: "transplant", meaning: "を移植する；を移住させる" },
  { word: "retail", meaning: "小売り（⇔wholesale 卸売り）" },
  { word: "abandon", meaning: "を捨てる、を放棄する" },
  { word: "developer", meaning: "宅地造成業者、開発者" },
  { word: "circulation", meaning: "循環；流通；（新聞・雑誌の）発行部数" },
  { word: "appliance", meaning: "(特に家庭用の)器具" },
  { word: "bond", meaning: "きずな、債券、契約" },
  { word: "circuit", meaning: "周回すること、回路、巡回" },
  { word: "innovation", meaning: "(技術)革新、新機軸" },
  { word: "infant", meaning: "幼児、乳児" },
  { word: "transaction", meaning: "（商）取引；（人と人との）交流" },
  { word: "celebrity", meaning: "有名人、著名人" },
  { word: "checkup", meaning: "健康診断、検査" },
  { word: "makeup", meaning: "化粧；化粧品；構成；性質" },
  { word: "respondent", meaning: "(調査・アンケートなどの)回答者" },
  { word: "well-being", meaning: "健康、幸福" },
  { word: "flaw", meaning: "欠点、傷、ひび" },
  { word: "strain", meaning: "に負担をかける；を緊張させる；を漉す" },
  { word: "rivalry", meaning: "ライバル意識、競争" },
  { word: "publicity", meaning: "一般に知られること、評判、宣伝" },
  { word: "consent", meaning: "同意，承諾" },
  { word: "addiction", meaning: "依存" },
  { word: "profession", meaning: "職業；専門職；同業者仲間" },
  { word: "sacrifice", meaning: "犠牲；いけにえ" },
  { word: "nerve", meaning: "神経；〔～s〕神経過敏；（...する）度胸（to do）" },
  { word: "assumption", meaning: "(確証のない)仮定、想定、思い込み" },
  { word: "context", meaning: "文脈、背景、状況" },
  { word: "era", meaning: "時代" },
  { word: "trait", meaning: "特徴、特色" },
  { word: "voucher", meaning: "クーポン券、商品券" },
  { word: "draft", meaning: "下書き；為替手形；隙間風" },
  { word: "blaze", meaning: "炎、強いか輝き" },
  { word: "currency", meaning: "通貨、普及" },
  { word: "stance", meaning: "立場、対処の姿勢" },
  { word: "fluid", meaning: "流動体，液体" },
  { word: "dispute", meaning: "に異議を唱える；（を）議論する" },
  { word: "counterpart", meaning: "相当する物［人］" },
  { word: "perception", meaning: "認識、知覚" },
  { word: "custody", meaning: "親権、保護、管理、拘留" },
  { word: "venue", meaning: "会場、開催地" },
  { word: "dread", meaning: "をひどく恐れる" },
  { word: "incentive", meaning: "動機（づけ）；報奨金" },
  { word: "disgust", meaning: "をむかつかせる；に愛想を尽かせる" },
  { word: "province", meaning: "州，省；〔the ～s〕地方；分野" },
  { word: "proponent", meaning: "支持者" },
  { word: "commercial", meaning: "商業(上)の、営利的な" },
  { word: "excessive", meaning: "過度の、法外な" },
  { word: "vulnerable", meaning: "（攻撃などに）弱い，もろい；傷つきやすい" },
  { word: "protective", meaning: "保護する、守ろうとする" },
  { word: "secure", meaning: "安全な、確かな" },
  { word: "obvious", meaning: "明らかな" },
  { word: "reluctant", meaning: "気が進まない，嫌がる（⇔willing）" },
  { word: "confident", meaning: "確信して、自信に満ちた" },
  { word: "intelligent", meaning: "知能の高い、利口な" },
  { word: "barren", meaning: "不毛の、作物ができない" },
  { word: "epidemic", meaning: "流行（病）；蔓延" },
  { word: "reliable", meaning: "信頼できる" },
  { word: "curious", meaning: "好奇心の強い、詮索好きな" },
  { word: "hasty", meaning: "急ぎの、早まった" },
  { word: "behavioral", meaning: "行動の" },
  { word: "bulky", meaning: "かさばった、扱いにくいほど大きい" },
  { word: "faulty", meaning: "(機械・装置などが)欠陥のある" },
  { word: "hectic", meaning: "やたらと忙しい" },
  { word: "knowledgeable", meaning: "よく知っている、物知りの" },
  { word: "tense", meaning: "張り詰めた，緊張した" },
  { word: "intact", meaning: "損なわれていない，手つかずの" },
  { word: "comprehensive", meaning: "包括的な、広範囲にわたる" },
  { word: "hesitant", meaning: "ためらいがちな" },
  { word: "scarce", meaning: "乏しい；珍しい" },
  { word: "defensive", meaning: "防御的な" },
  { word: "permanently", meaning: "永遠に、いつも" },
  { word: "nonetheless", meaning: "それにもかかわらず，それでもなお" },
  { word: "primarily", meaning: "主として、初めに" },
  { word: "intentionally", meaning: "故意に、意図的に" },
  { word: "abruptly", meaning: "突然に" },
  { word: "outsource", meaning: "を外注する、を業務委託する" },
  { word: "applaud", meaning: "に拍手する、を賞賛する" },
  { word: "bribe", meaning: "賄賂" },
  { word: "replicate", meaning: "(同一実験など)を繰り返す、を複製する" },
  { word: "stroll", meaning: "散歩する、ぶらぶら歩く" },
  { word: "swell", meaning: "膨張する，腫れる；を膨らませる" },
  { word: "uphold", meaning: "を支持する、を確認する、を維持する" },
  { word: "vomit", meaning: "吐く、もどす" },
  { word: "expire", meaning: "期限が切れる" },
  { word: "recruit", meaning: "を募る；に新人を補充する" },
  { word: "enhance", meaning: "を高める、を増す" },
  { word: "accumulate", meaning: "を蓄積する，集める；積もる" },
  { word: "designate", meaning: "を指定する；を任命する" },
  { word: "conceal", meaning: "を隠す（≒hide）；を秘密にする" },
  { word: "disregard", meaning: "を無視する；を軽視する" },
  { word: "accelerate", meaning: "を加速させる，促進する；加速する" },
  { word: "revive", meaning: "を復活させる；復活する" },
  { word: "enact", meaning: "(法案)を制定する、を通過させる" },
  { word: "exert", meaning: "を及ぼす；（力など）を行使する" },
  { word: "leak", meaning: "漏れる；を漏らす" },
  { word: "jail", meaning: "刑務所，拘置所（≒prison）" },
  { word: "reform", meaning: "を改革する、を改善する" },
  { word: "declare", meaning: "を宣言する、を断言する" },
  { word: "outline", meaning: "の要点を述べる；の輪郭を描く" },
  { word: "annoy", meaning: "をいらいらさせる、を悩ます" },
  { word: "interfere", meaning: "干渉する，介入する；邪魔する" },
  { word: "nest", meaning: "(鳥の)巣" },
  { word: "founder", meaning: "創設者" },
  { word: "biologist", meaning: "生物学者" },
  { word: "arrangement", meaning: "準備、配置、取り決め" },
  { word: "landfill", meaning: "ごみ埋め立て地" },
  { word: "trunk", meaning: "(木の)幹、(象の)鼻、(自動車の)" },
  { word: "principle", meaning: "(個人の)主義、信条、原則" },
  { word: "series", meaning: "連続、一続き" },
  { word: "independence", meaning: "独立、自立" },
  { word: "exploration", meaning: "探検、調査" },
  { word: "justice", meaning: "正義、公正、司法、裁判" },
  { word: "humanity", meaning: "人類" },
  { word: "involvement", meaning: "関与、巻き込まれること" },
  { word: "accounting", meaning: "経理、会計(学)" },
  { word: "discrimination", meaning: "（～に対する）差別（against）；区別" },
  { word: "inequality", meaning: "不平等" },
  { word: "master", meaning: "修士" },
  { word: "millennium", meaning: "千年間，千年紀" },
  { word: "refusal", meaning: "拒否、拒絶" },
  { word: "wound", meaning: "（銃弾・刃物などによる）傷；痛手" },
  { word: "absence", meaning: "不在、欠席" },
  { word: "distribution", meaning: "分配、配給" },
  { word: "wilderness", meaning: "荒野；（庭・町などの）放置された部分" },
  { word: "concentration", meaning: "濃度、集中、専念" },
  { word: "craft", meaning: "工芸品、(手先でする)作業" },
  { word: "crust", meaning: "地殻、パンの耳、(動物の)甲殻" },
  { word: "basement", meaning: "地階、地下室" },
  { word: "janitor", meaning: "(アパート・ビル・学校などの)用務員、管理人" },
  { word: "prejudice", meaning: "偏見、先入観" },
  { word: "prosperity", meaning: "繁栄、繁盛" },
  { word: "robbery", meaning: "強盗(事件)" },
  { word: "warranty", meaning: "保証(書)" },
  { word: "appetite", meaning: "食欲；欲求" },
  { word: "bullet", meaning: "銃弾" },
  { word: "preparation", meaning: "準備、支度" },
  { word: "citizenship", meaning: "市民権、公民権、市民[国民]であること" },
  { word: "stale", meaning: "(パンなどが)堅くなった、鮮度の落ちた、陳腐な" },
  { word: "disadvantaged", meaning: "(経済的・社会的に)恵まれない" },
  { word: "ongoing", meaning: "継続している，進行中の" },
  { word: "sturdy", meaning: "頑丈な、たくましい、不屈の" },
  { word: "unauthorized", meaning: "権限のない、(公的に)認可されていない" },
  { word: "verbal", meaning: "口頭での、言葉の[に関する]" },
  { word: "weary", meaning: "疲れ果てた；（～に）うんざりした（of）" },
  { word: "equivalent", meaning: "相当する、同等の" },
  { word: "intense", meaning: "極度の、激しい" },
  { word: "consecutive", meaning: "連続した" },
  { word: "noticeable", meaning: "著しい、目立つ" },
  { word: "crucial", meaning: "重大な、決定的な" },
  { word: "electrical", meaning: "電気の、電気を扱う" },
  { word: "steep", meaning: "（傾斜が）急な；急激な；法外な" },
  { word: "civil", meaning: "(軍人・官史に対して)民間の、一般市民の" },
  { word: "supreme", meaning: "最高の" },
  { word: "elite", meaning: "えり抜きの" },
  { word: "broad", meaning: "(幅の)広い、広範囲な" },
  { word: "industrial", meaning: "産業の、工業の" },
  { word: "allied", meaning: "連合の、同盟を組んだ" },
  { word: "external", meaning: "外部の；対外的な" },
  { word: "mere", meaning: "ほんの、単なる" },
  { word: "latter", meaning: "後半の、後ろの方の、後者の" },
  { word: "presidential", meaning: "大統領の[による]、社長の" },
  { word: "ethical", meaning: "倫理(上)の、道徳の" },
  { word: "realistic", meaning: "現実的な、実際的な" },
  { word: "harmless", meaning: "害のない" },
  { word: "underlying", meaning: "潜在的な、根本的な" },
  { word: "urgent", meaning: "緊急の" },
  { word: "complimentary", meaning: "無料の、賞賛する" },
  { word: "eager", meaning: "熱望して、熱心な" },
  { word: "loudly", meaning: "大声で、騒々しく" },
  { word: "accordingly", meaning: "それ相応に、従って、そんなわけで" },
  { word: "occasionally", meaning: "ときどき" },
  { word: "smoothly", meaning: "順調に、滑らかに" },
  { word: "frankly", meaning: "率直に、正直に" },
  { word: "notably", meaning: "とりわけ" },
  { word: "continuously", meaning: "連続して、継続して" },
  { word: "compel", meaning: "（人）に強いて～させる" },
  { word: "distinguish", meaning: "区別する、を区別する" },
  { word: "heighten", meaning: "を高める、を増大させる" },
  { word: "ruin", meaning: "を台無しにする、を駄目にする" },
  { word: "equip", meaning: "に備えつける" },
  { word: "export", meaning: "を輸出する" },
  { word: "glance", meaning: "ちらりと見る" },
  { word: "notify", meaning: "に知らせる" },
  { word: "overdo", meaning: "を使い過ぎる、をやり過ぎる" },
  { word: "pierce", meaning: "に穴を開ける、を突き通す" },
  { word: "overestimate", meaning: "を過大評価する[見積もる]" },
  { word: "raid", meaning: "(警察が)に手入れを行う、(軍隊が)を襲撃する" },
  { word: "recall", meaning: "を思い出す、(商品など)を回収する" },
  { word: "simplify", meaning: "を簡単にする" },
  { word: "wrinkle", meaning: "(顔などに)しわを寄せる、(衣装など)にしわを作る" },
  { word: "conspire", meaning: "陰謀を企てる、共謀する" },
  { word: "imitate", meaning: "をまねる、を見習う" },
  { word: "inhale", meaning: "を吸い込む" },
  { word: "overrate", meaning: "過大評価される" },
  { word: "sympathize", meaning: "同情する" },
  { word: "glide", meaning: "滑らかに動く、音もなく移動する" },
  { word: "kidnap", meaning: "を誘拐する" },
  { word: "pretend", meaning: "のつもりになる、～するふりをする" },
  { word: "simmer", meaning: "(煮立たない程度に)こことこ煮える[≒boil gently]" },
  { word: "thaw", meaning: "解凍される、溶ける" },
  { word: "unfold", meaning: "（閉じたもの）を開く；を明らかにする；開く；明らかになる" },
  { word: "detain", meaning: "を勾留[留置]する、(人)を引き留める" },
  { word: "puncture", meaning: "(タイヤ)をパンクさせる、に穴をあける" },
  { word: "strangle", meaning: "(発展・活動など)を抑圧する、を窒息させる" },
  { word: "hygiene", meaning: "衛生（状態）；健康法" },
  { word: "oppression", meaning: "抑圧、虐待" },
  { word: "collaboration", meaning: "合作、共同、協力" },
  { word: "harbor", meaning: "港、避難所" },
  { word: "lawn", meaning: "芝生" },
  { word: "pedestrian", meaning: "歩行者" },
  { word: "racism", meaning: "人種差別(主義[政策])" },
  { word: "summit", meaning: "(先進国)首脳会議、サミット、(山などの)頂上" },
  { word: "bug", meaning: "病原菌（が起こす病気）；虫；盗聴器；（機械・プログラムの）欠陥" },
  { word: "dirt", meaning: "汚れ、泥、ほこり" },
  { word: "maternity", meaning: "妊産婦の、母であること" },
  { word: "stroke", meaning: "脳卒中；（ボールを）打つこと；（雷などの）一撃" },
  { word: "tale", meaning: "(事実・伝説・架空の)話、(文学作品としての)物語" },
  { word: "certainty", meaning: "確実性、確信" },
  { word: "imbalance", meaning: "不均衡、アンバランス" },
  { word: "incidence", meaning: "発生(率)" },
  { word: "pit", meaning: "穴、くぼみ" },
  { word: "texture", meaning: "感触，手触り；本質；質感" },
  { word: "thumb", meaning: "(手の)親指" },
  { word: "undergraduate", meaning: "学部学生" },
  { word: "wisdom", meaning: "知恵、賢明さ" },
  { word: "bride", meaning: "花嫁、新婦" },
  { word: "dictator", meaning: "独裁者、専制君主" },
  { word: "signature", meaning: "署名；特徴" },
  { word: "testament", meaning: "あかし、証拠" },
  { word: "attachment", meaning: "添付ファイル、添付書類" },
  { word: "bachelor", meaning: "独身の男性、学士" },
  { word: "blister", meaning: "水ぶくれ" },
  { word: "blockade", meaning: "(港などの)封鎖、経済[通信]封鎖" },
  { word: "condo", meaning: "分譲マンション" },
  { word: "invoice", meaning: "明細請求書、納品書" },
  { word: "leisure", meaning: "自由な時間、余暇" },
  { word: "meditation", meaning: "瞑想、黙想" },
  { word: "procession", meaning: "(儀式などの)行列、行進" },
  { word: "unrest", meaning: "(社会的な)混乱、不安、(心の)動揺" },
  { word: "equator", meaning: "赤道" },
  { word: "exhausted", meaning: "疲れ果てた" },
  { word: "problematic", meaning: "問題のある、疑わしい" },
  { word: "desirable", meaning: "望ましい" },
  { word: "geological", meaning: "地質(学)上の" },
  { word: "rash", meaning: "早まった、軽率な" },
  { word: "solitary", meaning: "ひとりの、孤独の" },
  { word: "uneven", meaning: "でこぼこな、平でない" },
  { word: "antique", meaning: "骨董の，アンティークの；古風な" },
  { word: "dense", meaning: "密集した，密度の高い；（霧などが）濃い" },
  { word: "economical", meaning: "経済的な、安上がりな" },
  { word: "fictional", meaning: "架空の、フィクションの" },
  { word: "gradual", meaning: "徐々の，緩やかな" },
  { word: "intimate", meaning: "親密な；密接な" },
  { word: "lengthy", meaning: "長い、長時間の" },
  { word: "ultimate", meaning: "最終の、究極の" },
  { word: "victorious", meaning: "勝利を得た、勝ち誇った" },
  { word: "witty", meaning: "機知に富んだ" },
  { word: "blurry", meaning: "ぼやけた、不鮮明な" },
  { word: "exceptional", meaning: "例外的に優れた、まれな" },
  { word: "finite", meaning: "有限の、限られた" },
  { word: "on-the-job", meaning: "実地の、職場での" },
  { word: "vacant", meaning: "空いている" },
  { word: "cheery", meaning: "陽気な、元気な" },
  { word: "cowardly", meaning: "卑怯な、臆病な" },
  { word: "immeasurable", meaning: "計り知れない、果てしない、広大な" },
  { word: "impaired", meaning: "～に障害のある、弱った、損なわれた" },
  { word: "impassable", meaning: "(川・道などが)通行できない、(困難・障害などが)克服できない" },
  { word: "inactive", meaning: "不活発な、停止中の" },
  { word: "inconvenient", meaning: "不便な、不都合な" },
  { word: "superstitious", meaning: "迷信深い、迷信の" },
  { word: "unpleasant", meaning: "不愉快な、いやな" },
  { word: "wicked", meaning: "悪意のある、意地の悪い" },
  { word: "ecological", meaning: "環境の、生態(学)の" },
  { word: "imaginary", meaning: "想像上の、架空の" },
  { word: "ripe", meaning: "熟した；成熟した" },
  { word: "disguise", meaning: "を（～に）変装させる（as）；を偽る" },
  { word: "curb", meaning: "を抑制する、を制御する" },
  { word: "restrain", meaning: "を制止する；を規制する" },
  { word: "stumble", meaning: "よろけながら歩く；（～に）つまずく（on/over）" },
  { word: "diminish", meaning: "を減らす；減少する（≒decrease）" },
  { word: "rotate", meaning: "回転する；循環する；を回転させる" },
  { word: "compress", meaning: "を要約する、を短縮する、を圧縮して詰め込む" },
  { word: "decode", meaning: "(暗号・符号)を解読する" },
  { word: "offset", meaning: "を相殺する，埋め合わせる；をオフセット印刷にする" },
  { word: "bid", meaning: "（～に）の値をつける（for/on）；（挨拶）を述べる" },
  { word: "burst", meaning: "破裂する；（～を）突然始める（into）" },
  { word: "overtake", meaning: "を追い抜く；に追いつく（≒catch up with）；（災難・強い感情などが）を襲う" },
  { word: "retain", meaning: "を保持する" },
  { word: "litter", meaning: "(場所)を散らかす" },
  { word: "prohibit", meaning: "を禁止する" },
  { word: "discipline", meaning: "を罰する、を訓練する" },
  { word: "yield", meaning: "を産出する、屈する、(権利など)を譲る" },
  { word: "sweep", meaning: "（を）掃く；を一掃する；さっと通過する" },
  { word: "dictate", meaning: "を指図する；を書き取らせる；を規定する" },
  { word: "inject", meaning: "（人）に注射する，を注入する；を導入する" },
  { word: "urge", meaning: "に熱心に勧める" },
  { word: "mimic", meaning: "をまねる" },
  { word: "roam", meaning: "（を）歩き回る；放浪する" },
  { word: "assess", meaning: "を査定する、を評価する" },
  { word: "boast", meaning: "を誇る；（を）自慢する" },
  { word: "drag", meaning: "を引きずる；ぐずぐずする" },
  { word: "repay", meaning: "を返済する" },
  { word: "overthrow", meaning: "(政府・体制など)を打倒する" },
  { word: "fulfill", meaning: "(約束・任務など)を果たす、(条件・要求など)を満たす" },
  { word: "doom", meaning: "〔通例受身形で〕運命にある" },
  { word: "affiliate", meaning: "を提携させる、を合併する" },
  { word: "assault", meaning: "に暴行する；を攻撃する" },
  { word: "testimony", meaning: "証言、証拠" },
  { word: "errand", meaning: "（人の）使い，使い走り；用件" },
  { word: "friction", meaning: "不和；摩擦" },
  { word: "coalition", meaning: "連立、合同" },
  { word: "influx", meaning: "(人・物の)殺到、(水・空気の)流入" },
  { word: "curse", meaning: "悪態，ののしりの言葉；呪い；〔通例a ～〕災い" },
  { word: "app", meaning: "アプリ" },
  { word: "visibility", meaning: "視界、視野、目に見えること" },
  { word: "fabric", meaning: "織物，布（地）；構造" },
  { word: "collision", meaning: "衝突；対立" },
  { word: "dioxide", meaning: "二酸化物" },
  { word: "orbit", meaning: "軌道" },
  { word: "trial", meaning: "裁判、試験、試み" },
  { word: "literacy", meaning: "(特定分野の)知識、技能、読み書きの能力" },
  { word: "scheme", meaning: "計画（≒plan）；体系；陰謀" },
  { word: "completion", meaning: "完了、完成" },
  { word: "expertise", meaning: "専門的知識[技術、意見]" },
  { word: "diploma", meaning: "卒業[修了]証書、(学位・資格の)証明書" },
  { word: "livelihood", meaning: "生計、生活手段" },
  { word: "motive", meaning: "動機" },
  { word: "recession", meaning: "不況；後退" },
  { word: "surrounding", meaning: "周囲の状況、環境" },
  { word: "fortune", meaning: "財産、幸運、運命" },
  { word: "token", meaning: "(気持ちなどの)しるし、記念品" },
  { word: "trace", meaning: "跡、形跡" },
  { word: "venture", meaning: "危険を冒して進む；を思い切ってする" },
  { word: "physician", meaning: "内科医、医師" },
  { word: "perspective", meaning: "観点" },
  { word: "physics", meaning: "物理学" },
  { word: "legislation", meaning: "法律；立法" },
  { word: "barn", meaning: "家畜小屋、(農家の)納屋" },
  { word: "daring", meaning: "大胆な、勇敢な" },
  { word: "transparent", meaning: "透明な；明快な" },
  { word: "tragic", meaning: "悲惨な、悲劇的な" },
  { word: "sinister", meaning: "邪悪な、不吉な" },
  { word: "striking", meaning: "著しい、目立つ" },
  { word: "plural", meaning: "複数の、2つ[2人]以上の、複数形の" },
  { word: "vital", meaning: "必要不可欠な" },
  { word: "sensitive", meaning: "敏感な、傷つきやすい" },
  { word: "remarkable", meaning: "注目に値する、著しい" },
  { word: "minimal", meaning: "最小(限度)の" },
  { word: "bankrupt", meaning: "破産宣告を受けた；破綻している" },
  { word: "authentic", meaning: "本物の；信頼できる" },
  { word: "moderate", meaning: "適度な；穏健な" },
  { word: "alien", meaning: "異質の、外国の" },
  { word: "prompt", meaning: "迅速な" },
  { word: "random", meaning: "無作為の、任意の" },
  { word: "decisive", meaning: "決定的な、断固たる" },
  { word: "inevitable", meaning: "避けられない、必然的な" },
  { word: "acid", meaning: "酸性の；酸っぱい；辛辣な" },
  { word: "climatic", meaning: "気候(上)の、風土の" },
  { word: "incredible", meaning: "信じられない、驚くほどの" },
  { word: "precise", meaning: "正確な、厳格な" },
  { word: "invaluable", meaning: "極めて貴重な[高価]な" },
  { word: "stern", meaning: "厳しい；いかめしい" },
  { word: "indifferent", meaning: "無関心な（≒uninterested）" },
  { word: "charitable", meaning: "慈善の、慈悲深い" },
  { word: "massive", meaning: "大量の、大規模な、巨大な" },
  { word: "comparable", meaning: "匹敵する、同様の" },
  { word: "irrational", meaning: "不合理な" },
  { word: "cynical", meaning: "冷笑的な，皮肉な" },
  { word: "overly", meaning: "あまりに、過度に" },
  { word: "literally", meaning: "文字どおり、まさしく" },
  { word: "voluntarily", meaning: "自発的に" },
  { word: "technically", meaning: "厳密に(言えば)、専門[技術]的に" },
  { word: "wholly", meaning: "完全に、全く" },
  { word: "approximately", meaning: "おおよそ、ほぼ" },
  { word: "uniquely", meaning: "比類なく、独特に" },
  { word: "bewilder", meaning: "（通例受身形で）当惑する" },
  { word: "clutch", meaning: "をぐっとつかむ" },
  { word: "discard", meaning: "を捨てる" },
  { word: "enlist", meaning: "入隊する、参加する、(支持・協力)を得る" },
  { word: "heed", meaning: "(助言・警告など)に注意する" },
  { word: "liberate", meaning: "を解放する" },
  { word: "overlap", meaning: "（一部）重なる；（と）重複［共通］する" },
  { word: "reconstruct", meaning: "を再建する、を改変する" },
  { word: "shriek", meaning: "悲鳴をあげる、甲高い声[音]を出す" },
  { word: "sprain", meaning: "(足首・手首など)をくじく、を捻挫する" },
  { word: "resent", meaning: "に憤慨する" },
  { word: "thrive", meaning: "繁栄する，うまくいく；繁茂する" },
  { word: "embrace", meaning: "を抱擁する、を(喜んで)受け入れる" },
  { word: "excel", meaning: "（～で）秀でている（in/at）；に勝る" },
  { word: "enroll", meaning: "登録する，入会する；を登録させる" },
  { word: "retrieve", meaning: "（情報）を検索する；を取り戻す；を回復する" },
  { word: "degrade", meaning: "の面目を失わせる、の質[価値]を低下させる" },
  { word: "reconcile", meaning: "を（～と）一致させる（with）；を和解させる" },
  { word: "contaminate", meaning: "を汚染する；を堕落させる" },
  { word: "disrupt", meaning: "を混乱させる；を分裂させる" },
  { word: "divert", meaning: "（注意など）をそらす；を迂回させる；（資金など）を転用する" },
  { word: "grumble", meaning: "不平を述べる" },
  { word: "provoke", meaning: "（感情・行動など）を引き起こす；を挑発する" },
  { word: "outweigh", meaning: "より価値がある、より重い" },
  { word: "crave", meaning: "(を)切望する" },
  { word: "sustain", meaning: "を持続させる、を支える" },
  { word: "disclose", meaning: "を公表する，暴く" },
  { word: "tempt", meaning: "を（...する）気にさせる（to do）；を引きつける" },
  { word: "resign", meaning: "（を）辞任する；を放棄する" },
  { word: "dismiss", meaning: "を解雇する、(意見など)を退ける" },
  { word: "surpass", meaning: "を上回る" },
  { word: "bounce", meaning: "跳ねる；反射する；を弾ませる；（Ｅメールが）（宛先不明で）返送される" },
  { word: "bureau", meaning: "（官庁の）局；事務局；案内所" },
  { word: "dependency", meaning: "依存、従属" },
  { word: "discomfort", meaning: "不快、不便" },
  { word: "drawback", meaning: "欠点、不利な点" },
  { word: "feast", meaning: "祝宴；大ごちそう；楽しみ" },
  { word: "hydrogen", meaning: "水素" },
  { word: "modernization", meaning: "近代化、現代化、最新式化" },
  { word: "objective", meaning: "目的、目標" },
  { word: "poll", meaning: "世論調査、投票(数)、投票所" },
  { word: "ration", meaning: "(食料・物資などの)割当(量)" },
  { word: "revenue", meaning: "歳入（⇔expenditure 歳出）；収益" },
  { word: "scholarship", meaning: "奨学金、学識" },
  { word: "upbringing", meaning: "(子供の)養育、しつけ" },
  { word: "compliment", meaning: "賛辞" },
  { word: "excerpt", meaning: "抜粋、引用" },
  { word: "faith", meaning: "信仰(心)、信用" },
  { word: "segment", meaning: "部分、区分" },
  { word: "downturn", meaning: "(景気などの)下降(状態)" },
  { word: "temper", meaning: "気質，気性；機嫌；かんしゃく" },
  { word: "fragment", meaning: "断片" },
  { word: "intersection", meaning: "(進路の)交差点" },
  { word: "anarchy", meaning: "無秩序、無政府状態" },
  { word: "breakup", meaning: "(人間関係の)解消、別れ" },
  { word: "privilege", meaning: "特権" },
  { word: "exemption", meaning: "(義務・責任などの)免除" },
  { word: "monarch", meaning: "君主" },
  { word: "narrative", meaning: "話、物語" },
  { word: "sensation", meaning: "漠然とした感じ、感覚、大騒ぎ" },
  { word: "apprentice", meaning: "見習い(工)、初心者" },
  { word: "chore", meaning: "雑用、家事、いやな仕事" },
  { word: "dehydration", meaning: "脱水(症状)" },
  { word: "questionable", meaning: "疑わしい" },
  { word: "outdated", meaning: "時代[流行]遅れの、旧式の" },
  { word: "forthcoming", meaning: "来るべき" },
  { word: "gross", meaning: "総計の；甚だしい；粗野な" },
  { word: "overdue", meaning: "支払期限を過ぎた、(予定の日時より)遅れた" },
  { word: "contemporary", meaning: "現代の、現代的な、同時代の" },
  { word: "drastic", meaning: "徹底的な，抜本的な；極端な" },
  { word: "conditional", meaning: "～しだいの、条件付きの" },
  { word: "subjective", meaning: "主観的な" },
  { word: "exotic", meaning: "外来の；異国風の" },
  { word: "intensive", meaning: "集中的な、徹底的な" },
  { word: "obscure", meaning: "（世に）知られていない；不明瞭な" },
  { word: "tedious", meaning: "退屈な" },
  { word: "exclusive", meaning: "高級な、排他的な" },
  { word: "decent", meaning: "まずまずの；きちんとした；上品な" },
  { word: "considerate", meaning: "思いやりのある" },
  { word: "durable", meaning: "長持ちする、丈夫な" },
  { word: "perpetual", meaning: "永続的な；ひっきりなしの" },
  { word: "proficient", meaning: "堪能な、熟達した" },
  { word: "acoustic", meaning: "音響の；聴覚の；（楽器が）アコースティックの" },
  { word: "biographical", meaning: "伝記の" },
  { word: "botanical", meaning: "植物の、植物学(上)の" },
  { word: "brutal", meaning: "残酷な、無情な" },
  { word: "commendable", meaning: "賞賛されるべき、立派な" },
  { word: "desperate", meaning: "絶望的な、強く望んで、必死の" },
  { word: "extravagant", meaning: "浪費する、(要求などが)過度な" },
  { word: "filthy", meaning: "汚い、不潔な" },
  { word: "serene", meaning: "穏やかな、平静な" },
  { word: "valid", meaning: "法律的に有効な、理にかなった" },
  { word: "inherent", meaning: "生来の，本来的に備わっている" },
  { word: "merely", meaning: "単なる、ただの、単に" },
  { word: "somehow", meaning: "何とかして、とにかく" },
  { word: "subsequently", meaning: "その後、続いて" },
  { word: "deliberately", meaning: "故意に、慎重に" },
  { word: "gently", meaning: "優しく、静かに" },
  { word: "via", meaning: "～の手段によって、～経由で" },
  { word: "alongside", meaning: "～と一緒に、～と並んで" },
  { word: "portray", meaning: "を描く；（の役）を演じる" },
  { word: "dispatch", meaning: "を派遣する；を発送する；を処理する" },
  { word: "quote", meaning: "が～と述べたと伝える、を引用する" },
  { word: "amend", meaning: "を改正する、を修正する" },
  { word: "betray", meaning: "をうっかり表す；を裏切る" },
  { word: "wither", meaning: "(植物などが)しおれる" },
  { word: "omit", meaning: "を省略する" },
  { word: "fabricate", meaning: "をでっち上げる、を組み立てる" },
  { word: "violate", meaning: "（法律・規則など）に違反する；を侵害する" },
  { word: "allege", meaning: "を主張する" },
  { word: "integrate", meaning: "を統合する；融合する" },
  { word: "underestimate", meaning: "（を）過小評価する；（を）軽く見る；を少なく見積もる" },
  { word: "escort", meaning: "を護衛[護送]する、に付き添う" },
  { word: "facilitate", meaning: "を促進する、を容易にする" },
  { word: "initiate", meaning: "を新たに始める" },
  { word: "convey", meaning: "を伝える、を運ぶ" },
  { word: "populate", meaning: "に住む，の住民である；に人を住まわせる" },
  { word: "reinforce", meaning: "を補強する、を強化する" },
  { word: "attain", meaning: "を獲得する，達成する；に達する" },
  { word: "cheat", meaning: "(試験で)カンニングをする、をだます" },
  { word: "deceive", meaning: "をだます（≒take in）" },
  { word: "frustrate", meaning: "に不満を抱かせる、を挫折させる" },
  { word: "subsidize", meaning: "に補助金[助成金]を支給する" },
  { word: "alternate", meaning: "代わりの；交互の" },
  { word: "dedicate", meaning: "を捧げる" },
  { word: "endeavor", meaning: "～しようと(懸命に)努力する、を(真剣に)試みる" },
  { word: "intrigue", meaning: "に興味を持たせる；陰謀を企てる" },
  { word: "soar", meaning: "急上昇する；空高く飛ぶ" },
  { word: "tease", meaning: "（を）からかう；をいじめる" },
  { word: "confer", meaning: "(賞・学位・栄誉・権利など)を授与する、相談する" },
  { word: "forbid", meaning: "を禁じる" },
  { word: "nod", meaning: "(頭)を軽く下げる、うなずく" },
  { word: "oblige", meaning: "に義務づける；に恩恵を施す" },
  { word: "discontent", meaning: "不満" },
  { word: "disposal", meaning: "処分、売却" },
  { word: "exile", meaning: "亡命（者）；（国外）追放" },
  { word: "foe", meaning: "敵" },
  { word: "itinerary", meaning: "旅行の日程、旅行計画" },
  { word: "persecution", meaning: "迫害" },
  { word: "publication", meaning: "出版(物)、発行" },
  { word: "riddle", meaning: "なぞなぞ、不可解な人[もの、事実]" },
  { word: "sanitation", meaning: "公衆衛生（学）；下水［衛生］設備" },
  { word: "component", meaning: "構成部品[部分、要素]" },
  { word: "quota", meaning: "割当量[数]、ノルマ" },
  { word: "cuisine", meaning: "（独特の）料理，料理法" },
  { word: "detour", meaning: "迂回(路)、回り道" },
  { word: "inmate", meaning: "(刑務所などの)収容者、入院患者" },
  { word: "fatigue", meaning: "(相当の)疲労" },
  { word: "uproar", meaning: "大騒ぎ、騒動" },
  { word: "coincidence", meaning: "偶然の一致" },
  { word: "correspondence", meaning: "通信、一致" },
  { word: "ballot", meaning: "投票、投票用紙、投票総数" },
  { word: "competence", meaning: "能力、資格" },
  { word: "enterprise", meaning: "事業、企業" },
  { word: "hazard", meaning: "危険（要素）；偶然" },
  { word: "explosion", meaning: "爆発、急激な増加" },
  { word: "famine", meaning: "飢饉；（食糧・物資の）ひどい不足" },
  { word: "acceptance", meaning: "受諾、受け取り" },
  { word: "leftover", meaning: "(特に食事の)残りもの" },
  { word: "apprehension", meaning: "不安、懸念" },
  { word: "wreck", meaning: "残骸、難破(船)" },
  { word: "landmark", meaning: "（ある場所の）目印；画期的な出来事" },
  { word: "dweller", meaning: "居住者" },
  { word: "geometry", meaning: "幾何学" },
  { word: "standby", meaning: "(いざというとき)頼りになるもの(人)、交替要因" },
  { word: "diversity", meaning: "多様性" },
  { word: "accuracy", meaning: "正確さ、的確さ" },
  { word: "tap", meaning: "(水道などの)蛇口" },
  { word: "brick", meaning: "れんが" },
  { word: "bay", meaning: "入江、湾" },
  { word: "lenient", meaning: "寛大な" },
  { word: "stubborn", meaning: "頑固な，強情な（≒obstinate）；手に負えない" },
  { word: "clumsy", meaning: "不器用な" },
  { word: "perilous", meaning: "とても危険な" },
  { word: "adverse", meaning: "不都合な；逆の" },
  { word: "persistent", meaning: "執拗な、固執する、持続する" },
  { word: "outrageous", meaning: "法外な、途方もない、けしからぬ" },
  { word: "skeptical", meaning: "（～に）懐疑的な（of/about）" },
  { word: "legitimate", meaning: "合法的な；妥当な" },
  { word: "corrupt", meaning: "を堕落させる；を買収する；堕落する" },
  { word: "experimental", meaning: "実験の、実験[試験]的な" },
  { word: "improper", meaning: "不適切な、無作法な" },
  { word: "spontaneous", meaning: "自然発生的な；自発的な" },
  { word: "unconditional", meaning: "無条件の、絶対的な" },
  { word: "counterfeit", meaning: "偽造の、偽の" },
  { word: "dizzy", meaning: "目まいがする；当惑した" },
  { word: "sustainable", meaning: "持続できる、維持できる" },
  { word: "democratic", meaning: "民主主義の、民主的な" },
  { word: "conservative", meaning: "保守的な" },
  { word: "fundamental", meaning: "基本的な、必須の" },
  { word: "ambitious", meaning: "(計画などが)野心的な、(人が)大志を抱いた" },
  { word: "concrete", meaning: "具体的な、明確な、コンクリート製の" },
  { word: "cruel", meaning: "残酷な" },
  { word: "inferior", meaning: "劣悪な、劣った" },
  { word: "ample", meaning: "十分すぎるほどの；広い" },
  { word: "inaccurate", meaning: "不正確な、誤りのある" },
  { word: "inadequate", meaning: "不十分な、不適当な" },
  { word: "inappropriate", meaning: "ふさわしくない、不適当な" },
  { word: "uncertain", meaning: "はっきり分からない、(人が)確信がない" },
  { word: "vague", meaning: "あいまいな、不明確な" },
  { word: "retreat", meaning: "引っ込む、退く" },
  { word: "revolt", meaning: "暴動[反乱]を起こす、をむかむかさせる" },
  { word: "deflect", meaning: "(人の注意・非難など)をそらす、の方向を変えさせる" },
  { word: "demote", meaning: "を降格する" },
  { word: "despise", meaning: "を軽蔑する、をひどく嫌う" },
  { word: "grasp", meaning: "を理解する、をしっかりと握る" },
  { word: "summon", meaning: "を呼び出す、を召喚する、(議会など)を招集する" },
  { word: "expel", meaning: "を追放する；を吐き出す" },
  { word: "redeem", meaning: "(失敗・欠点など)を補う、を埋め合わせる" },
  { word: "comprise", meaning: "から成る；を構成する" },
  { word: "prevail", meaning: "普及している；支配的である；（～に）打ち勝つ（over）" },
  { word: "eject", meaning: "を取り出す、を追い出す" },
  { word: "falsify", meaning: "を偽造する" },
  { word: "obstruct", meaning: "をふさぐ、を妨害する" },
  { word: "depict", meaning: "を描く" },
  { word: "tremble", meaning: "震える" },
  { word: "confess", meaning: "（を）告白する" },
  { word: "stare", meaning: "じっと見つめる" },
  { word: "ache", meaning: "痛む、うずく" },
  { word: "reflect", meaning: "を反映する、を反射する、熟考する" },
  { word: "assert", meaning: "を主張する" },
  { word: "impose", meaning: "(規則・税・罰金など)を課[科]す、を押しつける" },
  { word: "interpret", meaning: "を解釈する、を通訳する" },
  { word: "devote", meaning: "(努力・時間など)を捧げる、に専念する" },
  { word: "deteriorate", meaning: "(状況・質など)が悪化する" },
  { word: "contemplate", meaning: "（を）熟考する；を予想する" },
  { word: "delegate", meaning: "(権限・責任など)を委譲[委任]する、(人)を代表として派遣する" },
  { word: "propel", meaning: "を進ませる、(人)を駆り立てる" },
  { word: "recede", meaning: "後退する、退く" },
  { word: "scrape", meaning: "(泥・ペンキ・さびなど)をこすり取る、の表面をこする" },
  { word: "smash", meaning: "を粉砕する；を強打する；粉々に壊れる；激突する" },
  { word: "scold", meaning: "(特に子供)をしかる" },
  { word: "amuse", meaning: "を楽しませる" },
  { word: "overhaul", meaning: "(システムなど)を総点検する、を分解修理する" },
  { word: "herd", meaning: "(牛・羊などの)群" },
  { word: "bait", meaning: "誘惑物、(釣り針・わなにつける)餌" },
  { word: "petition", meaning: "請願(書)、嘆願(書)" },
  { word: "ransom", meaning: "身代金、(身代金などによる)解放" },
  { word: "fragrance", meaning: "芳香" },
  { word: "insight", meaning: "見識、洞察力" },
  { word: "conquest", meaning: "征服、(欠点・課題などの)克服" },
  { word: "sincerity", meaning: "誠実" },
  { word: "tariff", meaning: "関税" },
  { word: "sanction", meaning: "制裁(措置)、認可" },
  { word: "sphere", meaning: "領域；球体；天体" },
  { word: "outcast", meaning: "見捨てられた人、浮浪者" },
  { word: "affair", meaning: "事情、事柄、問題" },
  { word: "scandal", meaning: "スキャンダル、不正行為" },
  { word: "allergy", meaning: "アレルギー" },
  { word: "destruction", meaning: "破壊、破滅" },
  { word: "peasant", meaning: "(発展途上国などの)小作人、貧農" },
  { word: "burden", meaning: "負担、重荷、荷物" },
  { word: "faculty", meaning: "(大学・学部の)教授陣、学部、才能、能力" },
  { word: "tactics", meaning: "作戦，方策；戦術，戦法" },
  { word: "fare", meaning: "(乗り物の)運賃、料金" },
  { word: "manner", meaning: "方法、風習、行儀、作法" },
  { word: "correlation", meaning: "相互[相関]関係" },
  { word: "weed", meaning: "雑草、草" },
  { word: "command", meaning: "命令、指図、(外国語などを)自由に使える能力" },
  { word: "quarter", meaning: "４分の１、(都市の特定の)地区、四半期" },
  { word: "availability", meaning: "(入手の)可能性、有用[有効]性" },
  { word: "caution", meaning: "用心、注意、警戒、警告" },
  { word: "prevention", meaning: "予防、防止、妨害" },
  { word: "reptile", meaning: "爬虫類(動物)" },
  { word: "fate", meaning: "運命、(最終的な)結末" },
  { word: "inclination", meaning: "意向、願望、好み" },
  { word: "scorn", meaning: "軽蔑、侮蔑" },
  { word: "contempt", meaning: "軽蔑；恥辱" },
  { word: "domain", meaning: "分野；領域；ドメイン" },
  { word: "pillar", meaning: "柱、支柱" },
  { word: "tender", meaning: "柔らかい、優しい" },
  { word: "awkward", meaning: "ばつの悪い、気まずい、ぎこちない" },
  { word: "fierce", meaning: "猛烈な；どう猛な" },
  { word: "peculiar", meaning: "変な、特有の" },
  { word: "genuine", meaning: "本物の" },
  { word: "vigorous", meaning: "精力的な；激しい；活力のある" },
  { word: "gloomy", meaning: "陰気な；薄暗い；悲観的な" },
  { word: "medieval", meaning: "中世の" },
  { word: "subtle", meaning: "微妙な、かすかな" },
  { word: "rigid", meaning: "厳しい；硬直した" },
  { word: "coarse", meaning: "粗い、粗野な" },
  { word: "humble", meaning: "謙虚な、地位[身分]などが低い" },
  { word: "slack", meaning: "たるんだ、(商売などが)不活発な" },
  { word: "trivial", meaning: "取るに足らない" },
  { word: "mutual", meaning: "相互の" },
  { word: "redundant", meaning: "不要な、余分な、(表現などが)冗長な" },
  { word: "premature", meaning: "早過ぎる、(判断などが)早まった" },
  { word: "attentive", meaning: "注意深い" },
  { word: "integral", meaning: "不可欠な、必要な" },
  { word: "memorable", meaning: "忘れられない、記憶すべき" },
  { word: "persuasive", meaning: "説得力のある" },
  { word: "prevalent", meaning: "蔓延している、広く行き渡っている" },
  { word: "unaware", meaning: "気づかないで、知らないで" },
  { word: "worthwhile", meaning: "(時間・労力・金をかける)価値のある" },
  { word: "amazing", meaning: "驚くべき" },
  { word: "eligible", meaning: "適格の，資格のある；（結婚相手として）望ましい" },
  { word: "vicious", meaning: "悪意[敵意]のある、乱暴な" },
  { word: "invisible", meaning: "見えない" },
  { word: "invalid", meaning: "(法的に)無効な" },
  { word: "rotten", meaning: "(食べ物などが)腐った、(道徳的に)腐敗した" },
  { word: "plague", meaning: "疫病；（害虫などの）異常発生" },
  { word: "sponsor", meaning: "に資金を提供する、を後援する" },
  { word: "honor", meaning: "を賞賛する、に与える、を尊敬する" },
  { word: "remark", meaning: "～と述べる" },
  { word: "incorporate", meaning: "を取り[組み]入れる" },
  { word: "resolve", meaning: "(問題など)を解決する、を決意する" },
  { word: "sway", meaning: "(ゆっくりと)揺れる、動揺する" },
  { word: "inherit", meaning: "(遺伝で)を受け継ぐ、を相続する" },
  { word: "pile", meaning: "を大量に積む、を積み重ねる、積み重なる" },
  { word: "renovate", meaning: "を改修[改築]する" },
  { word: "maximize", meaning: "を最大限にする" },
  { word: "uncover", meaning: "(遺跡など)を発掘する、の覆いを取る、を明るみに出す" },
  { word: "mislead", meaning: "に誤った考えを持たせる、を欺く" },
  { word: "opt", meaning: "選ぶ" },
  { word: "outnumber", meaning: "より数で勝る" },
  { word: "presume", meaning: "と思う；と推定する；を前提とする" },
  { word: "refine", meaning: "を洗練する；を精製する" },
  { word: "stir", meaning: "をかき回す；を揺り動かす" },
  { word: "strive", meaning: "懸命に努力する" },
  { word: "thrill", meaning: "をわくわく[ぞくぞく]させる" },
  { word: "tighten", meaning: "を固く締める、を強化する" },
  { word: "arouse", meaning: "（感情など）を引き起こす；を目覚めさせる" },
  { word: "buzz", meaning: "(場所が)ざわつく、どよめく" },
  { word: "converge", meaning: "集まる、集中する" },
  { word: "deduct", meaning: "を控除する、を減じる" },
  { word: "disconnect", meaning: "(人)のインターネットへの接続を切る、の接続を断つ" },
  { word: "gossip", meaning: "うわさ話をする" },
  { word: "wander", meaning: "(当てもなく)歩き回る、ぶらつく" },
  { word: "suck", meaning: "（を）吸う；（を）しゃぶる" },
  { word: "dye", meaning: "を～色に染める、を染める" },
  { word: "trespass", meaning: "(不法)侵入する、侵害する" },
  { word: "graze", meaning: "(家畜などが)牧草を食べる" },
  { word: "entrust", meaning: "AにBを任せる" },
  { word: "peer", meaning: "同僚、仲間、同等[対等]の者" },
  { word: "molecule", meaning: "分子、微粒子" },
  { word: "meantime", meaning: "その間" },
  { word: "merit", meaning: "価値、優秀さ、長所" },
  { word: "prospect", meaning: "見込み、見通し、期待" },
  { word: "chatter", meaning: "くだらないおしゃべり" },
  { word: "funeral", meaning: "葬式" },
  { word: "methodology", meaning: "方法論、研究方法" },
  { word: "bundle", meaning: "束、包み" },
  { word: "burglar", meaning: "強盗、泥棒" },
  { word: "canyon", meaning: "峡谷" },
  { word: "duration", meaning: "（時間の）継続，持続（時間）" },
  { word: "fountain", meaning: "噴水、源泉、湧き水" },
  { word: "genius", meaning: "天賦の才、天才(的な人)" },
  { word: "grassland", meaning: "牧草地、草原" },
  { word: "interval", meaning: "（時間の）間隔；合間；隔たり；小休止" },
  { word: "longevity", meaning: "長寿；寿命；長年勤続" },
  { word: "mode", meaning: "方法、様式" },
  { word: "needle", meaning: "針、縫い針、編み針" },
  { word: "organizer", meaning: "主催者、まとめ役、幹事" },
  { word: "rehearsal", meaning: "(劇・音楽などの)リハーサル、下げいこ" },
  { word: "servant", meaning: "(特に住み込みの)使用人、召使" },
  { word: "sociology", meaning: "社会学" },
  { word: "spectacle", meaning: "(印象的な)光景、壮観、見もの" },
  { word: "norm", meaning: "標準、規範、典型" },
  { word: "certificate", meaning: "証明書；免許状" },
  { word: "vice", meaning: "悪習、悪" },
  { word: "knot", meaning: "結び目、結び方" },
  { word: "rubber", meaning: "ゴム、ゴム製品" },
  { word: "asteroid", meaning: "小惑星" },
  { word: "syndrome", meaning: "症候群、シンドローム" },
  { word: "detention", meaning: "拘置、留置" },
  { word: "distress", meaning: "苦悩、苦痛" },
  { word: "ignition", meaning: "(エンジンの)点火装置、点火" },
  { word: "esteem", meaning: "尊敬、尊重" },
  { word: "hospitality", meaning: "親切なもてなし，歓待；受容性" },
  { word: "legacy", meaning: "遺産" },
  { word: "sane", meaning: "(考え方などが)健全な、分別のある、正気の" },
  { word: "doubtful", meaning: "(物・事が)疑わしい、(人が)疑わしく思う" },
  { word: "favorable", meaning: "好意的な、好ましい" },
  { word: "generous", meaning: "気前のよい、寛大な" },
  { word: "hollow", meaning: "空洞の；空虚な；うわべだけの" },
  { word: "internal", meaning: "内部の、内側の、国内の" },
  { word: "interpersonal", meaning: "人間[対人]関係の" },
  { word: "staple", meaning: "必需食品；主要産物" },
  { word: "tolerant", meaning: "寛容な、包容力のある" },
  { word: "folk", meaning: "民間(起源)の、民衆の" },
  { word: "furious", meaning: "激怒した；猛烈な" },
  { word: "ironic", meaning: "皮肉な、反語的な" },
  { word: "pale", meaning: "(人・顔色などが)青白い、血の気を失った、(色が)淡い、薄い" },
  { word: "pregnant", meaning: "妊娠した" },
  { word: "rewarding", meaning: "満足感が得られる、報われる" },
  { word: "sacred", meaning: "神聖な、聖なる、宗教的な" },
  { word: "terrific", meaning: "素晴らしい、すてきな" },
  { word: "abridged", meaning: "簡約[短縮]された" },
  { word: "dull", meaning: "退屈な、頭が鈍い" },
  { word: "faint", meaning: "かすかな；めまいがする；弱々しい" },
  { word: "irresponsible", meaning: "無責任な" },
  { word: "notorious", meaning: "悪名高い（≒infamous）" },
  { word: "recurrent", meaning: "(周期的に)繰り返される、(病気などが)再発する" },
  { word: "irresistible", meaning: "抵抗できない、非常に魅力的な" },
  { word: "binding", meaning: "拘束力のある、義務を負わせる" },
  { word: "dejected", meaning: "落胆した、元気のない" },
  { word: "fictitious", meaning: "架空の、偽りの" },
  { word: "gracious", meaning: "親切な、丁寧な" },
  { word: "upcoming", meaning: "やがて起ころう[現れよう]としている、来るべき" },
  { word: "abundant", meaning: "豊富な" },
  { word: "grind", meaning: "（穀物など）をひく" },
  { word: "archive", meaning: "〔しばしば～s〕記録文書，公文書；公文書保管所；（コンピューターの）アーカイブ" },
  { word: "devise", meaning: "を考案する" },
  { word: "precede", meaning: "に先行する" },
  { word: "horrify", meaning: "を怖がらせる" },
  { word: "lodge", meaning: "(苦情・抗議など)を申し出る、を預ける、を泊める" },
  { word: "mediate", meaning: "調停する、仲裁する" },
  { word: "mingle", meaning: "付き合う、仲間に入る、混ざる" },
  { word: "perspire", meaning: "汗をかく" },
  { word: "concede", meaning: "(しぶしぶ)～と認める" },
  { word: "hinder", meaning: "を妨げる" },
  { word: "waver", meaning: "(心が)揺れ動く、迷う" },
  { word: "formulate", meaning: "(計画など)を(注意深く)まとめる、を明確に述べる" },
  { word: "exhale", meaning: "(息・煙・言葉など)を吐き出す" },
  { word: "rebound", meaning: "(ボールなどが)跳ね返る" },
  { word: "gratify", meaning: "を喜ばせる、を満足させる" },
  { word: "pledge", meaning: "を誓う，約束する；を与えることを約束する" },
  { word: "fasten", meaning: "をしっかり留める、を固定する" },
  { word: "relay", meaning: "を伝達する、を取り次ぐ、を中継で送る" },
  { word: "align", meaning: "を一直線に並べる" },
  { word: "ascend", meaning: "（を）上がる" },
  { word: "gaze", meaning: "じっと見る" },
  { word: "adore", meaning: "が大好きである、を敬愛する" },
  { word: "chill", meaning: "(食べ物・飲み物など)を冷やす、冷える" },
  { word: "curve", meaning: "カーブする、曲がる" },
  { word: "deflate", meaning: "(タイヤ・風船などが)しぼむ、をしぼませる" },
  { word: "detach", meaning: "を分離する、を取り外す" },
  { word: "enclose", meaning: "を同封する；を取り囲む" },
  { word: "fetch", meaning: "を（行って）持って［連れて］くる" },
  { word: "proclaim", meaning: "を宣言する" },
  { word: "forge", meaning: "を偽造する；（関係など）を築く；を鍛造する" },
  { word: "outburst", meaning: "(火山・怒り・笑いなど)の爆発" },
  { word: "dimension", meaning: "局面、寸法、規模、次元" },
  { word: "swarm", meaning: "大群" },
  { word: "sequel", meaning: "続編、結果" },
  { word: "artifact", meaning: "人工遺物、工芸品" },
  { word: "mercy", meaning: "慈悲；〔通例a ～〕幸運" },
  { word: "successor", meaning: "後継者、相続人" },
  { word: "triumph", meaning: "(大)勝利、成功" },
  { word: "clause", meaning: "(法律・条約などの)条項、(文の)節" },
  { word: "analogy", meaning: "類推；類似" },
  { word: "downfall", meaning: "破滅、転落、(雨・雪などの)大降り" },
  { word: "fusion", meaning: "融合(物)、(政府などの)連立" },
  { word: "fracture", meaning: "骨折、割れ目、裂け目" },
  { word: "menace", meaning: "困りもの、危険人物、脅威" },
  { word: "setback", meaning: "(進歩・発展の)妨げ、支障" },
  { word: "empathy", meaning: "共感、感情移入" },
  { word: "tumble", meaning: "転倒、(株価などの)暴落" },
  { word: "diameter", meaning: "直径" },
  { word: "momentum", meaning: "勢い、はずみ" },
  { word: "troop", meaning: "軍隊、兵隊" },
  { word: "pharmacy", meaning: "薬屋、薬局" },
  { word: "nightmare", meaning: "悪夢、(悪夢のような)恐ろしい経験" },
  { word: "slope", meaning: "坂、斜面" },
  { word: "glacier", meaning: "氷河" },
  { word: "grief", meaning: "(死などに対する)深い悲しみ、悲痛" },
  { word: "misery", meaning: "惨めさ、悲惨さ" },
  { word: "accent", meaning: "なまり、方言" },
  { word: "ambassador", meaning: "大使" },
  { word: "autopsy", meaning: "検死" },
  { word: "blast", meaning: "爆発、爆破、突風" },
  { word: "courtesy", meaning: "礼儀正しさ；好意；優遇" },
  { word: "deed", meaning: "(意図的な)行為、行い" },
  { word: "discourse", meaning: "話し合い，会話；講演；論説" },
  { word: "impulse", meaning: "衝動" },
  { word: "jar", meaning: "(広口の)びん、つぼ" },
  { word: "sibling", meaning: "兄弟姉妹(の１人)" },
  { word: "enthusiasm", meaning: "熱狂、熱中" },
  { word: "treasure", meaning: "宝物、貴重品" },
  { word: "horizontal", meaning: "水平な" },
  { word: "indefinite", meaning: "限定されない、不定の、はっきりしない" },
  { word: "vulgar", meaning: "下品な、無作法な" },
  { word: "resilient", meaning: "回復力のある、弾力(性)ある" },
  { word: "aquatic", meaning: "(動植物が)水生の、水の" },
  { word: "insistent", meaning: "強く主張する、執拗な" },
  { word: "frantic", meaning: "大急ぎの、気が狂いそうな" },
  { word: "deceptive", meaning: "人を惑わすような" },
  { word: "illogical", meaning: "筋の通らない、不合理な" },
  { word: "elaborate", meaning: "精巧な、入念な" },
  { word: "mellow", meaning: "(性格が)円熟した、柔らかくて豊かな[美しい]" },
  { word: "boundless", meaning: "無限の" },
  { word: "cordial", meaning: "心温まる、心からの" },
  { word: "seasonal", meaning: "季節(ごと)の" },
  { word: "sour", meaning: "酸っぱい" },
  { word: "swift", meaning: "素早い" },
  { word: "cumulative", meaning: "累積する、しだいに増加する" },
  { word: "savage", meaning: "残酷な、凶暴な" },
  { word: "admirable", meaning: "賞賛に値する、素晴らしい" },
  { word: "informative", meaning: "有益な、情報[知識]を提供する" },
  { word: "proportional", meaning: "釣り合った、比例した" },
  { word: "simultaneous", meaning: "同時に起こる" },
  { word: "static", meaning: "変化[進歩]のない" },
  { word: "uneasy", meaning: "不安な、心配な、落ち着かない" },
  { word: "unequal", meaning: "(権利などが)不平等な" },
  { word: "autonomous", meaning: "自治の、自主的な" },
  { word: "bold", meaning: "大胆な、勇敢な" },
  { word: "pessimistic", meaning: "悲観的な" },
  { word: "repetitive", meaning: "繰り返しの" },
  { word: "respiratory", meaning: "呼吸器に関する、呼吸の" },
  { word: "coherent", meaning: "一貫した，筋の通った；結束した" },
  { word: "account for ～", meaning: "(割合・分量など)を占める、～(の理由)を説明する" },
  { word: "accuse A of B", meaning: "AをBの罪で告訴する、AをBの理由で非難する" },
  { word: "act on ～", meaning: "(忠告・情報など)に従って行動する、～に影響を及ぼす" },
  { word: "act out ～", meaning: "(物語・経験など)を身振りで実演する" },
  { word: "add up to ～", meaning: "(合計が)～になる、結局～ということになる" },
  { word: "adhere to ～", meaning: "(信念・規則など)を順守する、～に固執する" },
  { word: "air out ～", meaning: "(部屋など)を換気する、(衣類・寝具など)を外気に当てる" },
  { word: "all but", meaning: "ほとんど" },
  { word: "allow for ～", meaning: "～を考慮に入れる、～を見込む" },
  { word: "answer for ～", meaning: "～の責任を負う、～の罰を受ける" },
  { word: "aspire to do ～", meaning: "～することを熱望[切望]する" },
  { word: "attribute A to B", meaning: "AをBのせいと考える" },
  { word: "back down", meaning: "撤回する、敗北[非]を認める" },
  { word: "back off", meaning: "手を引く、撤回する、後退する" },
  { word: "back up ～", meaning: "～を裏付ける、～を支援する、(ファイルなど)のコピーを取る" },
  { word: "back on ～", meaning: "～を当てにする" },
  { word: "be committed to ～", meaning: "～に献身している" },
  { word: "be destined to do ～", meaning: "～する運命である" },
  { word: "(be) free of ～", meaning: "(料金・税金など)がない、～免除されている" },
  { word: "be obsessed with ～", meaning: "(妄想・固定観念など)に取りつかれている" },
  { word: "be subject to ～", meaning: "(病気など)にかかりやすい、(影響など)を受けやすい" },
  { word: "blast off", meaning: "打ち上げられる、発射される" },
  { word: "blow up", meaning: "(かんかんに)怒る、爆発する" },
  { word: "bounce back", meaning: "(打撃・病気などから)回復する、立ち直る" },
  { word: "branch off", meaning: "(話題が)変わる、(わき道に)それる" },
  { word: "break away from ～", meaning: "(伝統・習慣など)を断つ、(束縛など)から逃れる" },
  { word: "break down", meaning: "決裂する、失敗する、故障する" },
  { word: "break off ～", meaning: "～を中断する、～を急にやめる" },
  { word: "break out", meaning: "勃発する、(伝染病などが)発生する" },
  { word: "bring about ～", meaning: "～を引き起こす、～を招く" },
  { word: "bring down ～", meaning: "(人・政府など)を(打ち)倒す" },
  { word: "bring off ～", meaning: "～をやってのける、～を成し遂げる" },
  { word: "bring on ～", meaning: "(災い・病気など)をもたらす" },
  { word: "bring out ～", meaning: "(才能・性質など)を引き出す、～を発揮させる" },
  { word: "bump into ～", meaning: "～にばったり出会う" },
  { word: "burn out ～", meaning: "(人)を疲れ果てさせる、～を燃え尽きさせる" },
  { word: "by means of ～", meaning: "～用いて、～によって" },
  { word: "call for ～", meaning: "～を必要とする、～を要求する" },
  { word: "call off ～", meaning: "～を中止する" },
  { word: "call on ～", meaning: "～を訪ねる、(人)に頼む" },
  { word: "carry away ～", meaning: "無我夢中になる、～を持ち去る" },
  { word: "carry through ～", meaning: "～を成し遂げる、～を成就させる" },
  { word: "catch up on ～", meaning: "(近況など)について新しい情報を知る、～の遅れを取り戻す" },
  { word: "check off ～", meaning: "～にチェックマークをつける" },
  { word: "chip in ～", meaning: "(金・労力などを)出し合う" },
  { word: "clean out ～", meaning: "～の中をきれいにする、～を空にする" },
  { word: "clear out ～", meaning: "～の中身を出してきれいに片付ける、～を空にする" },
  { word: "clear up (～)", meaning: "(誤解など)を解く、(問題など)を解明する、～片付ける、晴れる" },
  { word: "close in (on ～)", meaning: "(～を)包囲する、(～に)追ってくる" },
  { word: "come after ～", meaning: "～の後をつける、～を追跡する" },
  { word: "come before ～", meaning: "(問題などが)(法廷など)で審議される、(法廷など)に出頭する" },
  { word: "come down to ～", meaning: "要するに～ということになる" },
  { word: "come down with ～", meaning: "(軽い病気)にかかる" },
  { word: "come into ～", meaning: "～の状態になる" },
  { word: "come off", meaning: "結局～になる、行われる" },
  { word: "come through", meaning: "要求に応える、伝えられる" },
  { word: "comply with ～", meaning: "(規則・基準など)に従う" },
  { word: "contribute to ～", meaning: "～の一因となる、～に寄与[貢献]する～に寄付する" },
  { word: "cope with ～", meaning: "～うまく処理する、～に対処する" },
  { word: "count for ～", meaning: "～の価値がある" },
  { word: "count on ～", meaning: "～を当てにする" },
  { word: "cover for ～", meaning: "～の代わり[代理]を務める" },
  { word: "cover up ～", meaning: "～(の事実)を隠す、～を秘密にする" },
  { word: "crack up", meaning: "神経が参る、気が変になる、大笑いする" },
  { word: "cross out ～", meaning: "～を線を引いて消す" },
  { word: "cut back (on ～)", meaning: "(～を)削減[縮小]する" },
  { word: "cut down (on ～)", meaning: "(～を)減らす" },
  { word: "cut in (on ～)", meaning: "(話などに)割り込む、さえぎる" },
  { word: "deal in ～", meaning: "(商品)を商う、(仕事など)に従事する" },
  { word: "deprive A of B", meaning: "AからBを奪う" },
  { word: "die down", meaning: "静まる、衰える" },
  { word: "die out", meaning: "絶滅する" },
  { word: "dispose of ～", meaning: "～を処分する、を捨てる" },
  { word: "do away with ～", meaning: "～を廃止する、～を取り除く" },
  { word: "drag on", meaning: "(会議などがだらだらと)長引く" },
  { word: "drag out ～", meaning: "～を(必要以上に)長引かせる" },
  { word: "draw on ～", meaning: "(技術・経験など)に頼る、～を利用する" },
  { word: "draw up ～", meaning: "(計画)を立てる、(報告書など)を作成する" },
  { word: "dream up ～", meaning: "(奇抜な考え・計画など)を思いつく、～を考え出す" },
  { word: "drive off [away] ～", meaning: "～を追い払う" },
  { word: "drive up ～", meaning: "(価格など)を急速に上昇させる" },
  { word: "drop back (to ～)", meaning: "(～に)後退する、順位が下がる" },
  { word: "drop out (of ～)", meaning: "(活動・集団から)身を引く、(学校を)中途退学する" },
  { word: "ease into ～", meaning: "(仕事など)に徐々に慣れる" },
  { word: "eat up ～", meaning: "～を使い果たす、～を食べ尽くす" },
  { word: "embark on [upon] ～", meaning: "(事業など)に乗り出す、～に着手する" },
  { word: "endear A to B", meaning: "AをBに慕わせる" },
  { word: "even up ～", meaning: "～を等しくする、～を均等にする" },
  { word: "face off", meaning: "対決する" },
  { word: "fall away", meaning: "減少する、弱まる、衰える" },
  { word: "fall back on ～", meaning: "～を当てにする" },
  { word: "fall for ～", meaning: "(うまい話・売り込みなど)に乗せられる、～に強く引きつけられる" },
  { word: "fall off", meaning: "(数・量が)減少する、(質が)低下する" },
  { word: "fall on ～", meaning: "(責任・仕事などが)～に降りかかる、(記念日などが)～に当たる" },
  { word: "fall through", meaning: "(計画などが)駄目になる、失敗する" },
  { word: "fall under ～", meaning: "(影響・監督など)を受ける" },
  { word: "feel for ～", meaning: "～に同情する、～を思いやる" },
  { word: "figure out ～", meaning: "～を理解する、～を解決する" },
  { word: "fill out ～", meaning: "(書類)に必要事項を記入する" },
  { word: "fire up ～", meaning: "～始動させる、～に火をつける" },
  { word: "fit into ～", meaning: "～に溶け込む、～に収まる" },
  { word: "fix up ～", meaning: "～を修理する、～を改装する" },
  { word: "for all ～", meaning: "～にもかかわらず、～を考慮しても" },
  { word: "for the time being", meaning: "当分の間(は)、さしあたり" },
  { word: "force down ～", meaning: "(感情など)を抑える" },
  { word: "free up ～", meaning: "～を自由化する、～解放する" },
  { word: "frown on [upon] ～", meaning: "～に難色を示す、～に不賛成の意を表す" },
  { word: "gear up ～", meaning: "準備をする" },
  { word: "get around (～)", meaning: "あちこち動き回る、歩き回る、～をうまく避ける、～を逃れる" },
  { word: "get around to doing ～", meaning: "～をする余裕[暇]ができる" },
  { word: "get away with ～", meaning: "～を(罰などを受けずに)うまくやる" },
  { word: "get by ～", meaning: "何とかやっていく、通り抜ける" },
  { word: "get down to ～", meaning: "～本気で取りかかる" },
  { word: "get in on ～", meaning: "～に参加する、～に加わる" },
  { word: "get into ～", meaning: "(本・映画・音楽など)に夢中になる、(ある状態)になる" },
  { word: "get on with ～", meaning: "(仕事など)を続ける、(人)とうまくやっていく" },
  { word: "give away ～", meaning: "(秘密・答えなど)をばらす、～をただで与える、～を安く売る" },
  { word: "give in (to ～)", meaning: "(～に)降参する、屈する、負ける" },
  { word: "give off ～", meaning: "(光・音・においなど)を発する" },
  { word: "give A over to B", meaning: "AをBに預ける、AをBに引き渡す" },
  { word: "give rise to ～", meaning: "～の原因となる、(悪い事態)を生じさせる" },
  { word: "go back on ～", meaning: "(約束など)を破る" },
  { word: "go for ～", meaning: "～を選ぶ" },
  { word: "grow into ～", meaning: "(成長して)(服など)を着られるようになる" },
  { word: "grow on ～", meaning: "(人)の気にいるようになる、(習慣などが)～の身につてくる" },
  { word: "grow out of ～", meaning: "(成長して)(行為・習慣など)から脱する、～から生じる" },
  { word: "hand down ～", meaning: "(伝統・慣習など)を(後世に)伝える、(判決など)を言い渡す" },
  { word: "hand off ～", meaning: "～を任せる、～を引き渡す" },
  { word: "hand out A (to B)", meaning: "(Bに)Aを配る" },
  { word: "hang around (～)", meaning: "(～を)ぶらつく、うろつく" },
  { word: "hang on", meaning: "(少し)待つ、電話を切らずにおく" },
  { word: "hang up ～", meaning: "(電話を)切る" },
  { word: "head off (～)", meaning: "～を阻止する、～を回避する、出かける、立ち去る" },
  { word: "head out", meaning: "出かける、立ち去る" },
  { word: "hold back ～", meaning: "～を抑えておく" },
  { word: "hold off ～", meaning: "～を引き延ばす、～を延期する" },
  { word: "hold out (～)", meaning: "(敵・逆境・圧力などに)もちこたえる、～を差し出す" },
  { word: "hold over ～", meaning: "続映[続演]される、～を延期する" },
  { word: "in a row", meaning: "連続で" },
  { word: "in favor of ～", meaning: "～に賛成して、～を支持して" },
  { word: "in response to ～", meaning: "～に応えて、～に応じて" },
  { word: "in terms of ～", meaning: "～の観点から" },
  { word: "in the event of ～", meaning: "(万一)～の場合には" },
  { word: "in vain", meaning: "無駄に、効果なく、～にすぐ飛びつく" },
  { word: "jump at ～", meaning: "～にすぐ飛びつく" },
  { word: "keep track of ～", meaning: "(人の動向・情勢など)に注意している、～の跡をたどる" },
  { word: "keep up with ～", meaning: "(時勢・流行・人・仕事・勉強など)に遅れずについていく" },
  { word: "kick around ～", meaning: "(計画・提案など)をあれこれ検討する" },
  { word: "kick in", meaning: "(薬などが)効き始める、機能し始める" },
  { word: "kick off A (with B)", meaning: "(Bで)Aを開始する" },
  { word: "kick A out (of B)", meaning: "(Bから)Aを追い出す[首にする]" },
  { word: "knock down ～", meaning: "～を取り壊す、～を解体する、～を殴り倒す" },
  { word: "lay into ～", meaning: "～を厳しく非難する、～を攻撃する" },
  { word: "lay off ～", meaning: "(一時的にまたは永久に) ～を解雇する" },
  { word: "leave off (～)", meaning: "(～を)やめる" },
  { word: "let alone ～", meaning: "まして～、～は言うまでもなく" },
  { word: "let down ～", meaning: "～を失望させる、～(の期待・信頼)を裏切る" },
  { word: "let out ～", meaning: "(声など)を出す、(感情)を表す、～を外に出す" },
  { word: "let up", meaning: "手を緩める、(望ましくないことが)弱まる、(風雨などが)やむ" },
  { word: "level off [out]", meaning: "横ばいになる、安定する" },
  { word: "lift off", meaning: "(飛行機などが)離陸する" },
  { word: "live up to ～", meaning: "(期待など)に応える、(規範など)に従って行動する" },
  { word: "lock in ～", meaning: "～を固定する、(鍵をかけて)～を閉じ込める" },
  { word: "look down on ～", meaning: "～を見下す、～を軽蔑する" },
  { word: "make (both) ends meet", meaning: "(収支を合わせて)収入内で何とかやりくりする" },
  { word: "make do with ～", meaning: "(あり合わせのもの)で済ます" },
  { word: "make it", meaning: "間に合う、成功する、(会合などに)出席できる" },
  { word: "make out (～)", meaning: "～を理解する、うまくやる" },
  { word: "make over ～", meaning: "～を作り変える、～変身させる" },
  { word: "mark down ～", meaning: "～を値下げする、～を書き留める" },
  { word: "mark out ～", meaning: "(線などで)～を区画する、～を区切る" },
  { word: "miss out on ～", meaning: "(機会・好機など)を逸する" },
  { word: "narrow down ～", meaning: "(範囲など)を制限する、～を狭くする" },
  { word: "on a ～ basis", meaning: "～の基準で、～の原則で" },
  { word: "on [in] behalf of A", meaning: "Aを代表して、Aに代わって" },
  { word: "on the contrary", meaning: "それどころか、まるで反対で" },
  { word: "on the spot", meaning: "その場で、即座に" },
  { word: "on the verge of ～", meaning: "～の間際[寸前]で" },
  { word: "over the hump", meaning: "難局を脱して、峠を越して" },
  { word: "owing to ～", meaning: "～のために、～の理由で" },
  { word: "pack up", meaning: "(仕事などが終わって)持ち物をまとめる、荷造りする" },
  { word: "pass for ～", meaning: "～で通る、～と見なされる" },
  { word: "pass off A (as B)", meaning: "Aを(Bだと)偽る" },
  { word: "pass A on (to B)", meaning: "A(もの・情報・病気・利益など)を(Bに)伝える[渡す]" },
  { word: "pass out", meaning: "気絶する" },
  { word: "pay off ～", meaning: "(借金など)を全部支払う" },
  { word: "phase out ～", meaning: "～を段階的に廃止[排除]する" },
  { word: "pick over ～", meaning: "～念入りに調べて選ぶ、～を吟味する" },
  { word: "pick through ～", meaning: "～の中をくまなく探す" },
  { word: "pile up", meaning: "(仕事・借金などが)どんどんたまる、山積する" },
  { word: "pin down ～", meaning: "～を押さえつける、～を動けなくする" },
  { word: "play down ～", meaning: "～を(実際より)重要でないように見せようとする" },
  { word: "play out (～)", meaning: "(物事・状況が)展開する、徐々に進展する、～を最後まで演じる" },
  { word: "play up ～", meaning: "～を誇張する、～強調する" },
  { word: "point to ～", meaning: "(状況・証拠などが)～を示す、(大事な点・理由など)を指摘する" },
  { word: "pull back (～)", meaning: "後退する、～を後退させる、思いとどまる" },
  { word: "pull in ～", meaning: "(観客・客など)を引きつける、(利益・金など)を得る" },
  { word: "pull off ～", meaning: "(困難なこと)をやってのける" },
  { word: "pull through ～", meaning: "(病気・苦境など)を切り抜ける" },
  { word: "push for ～", meaning: "～を要求する、～を得ようと努める" },
  { word: "push through ～", meaning: "(議案など)を通す、～を突き進む" },
  { word: "put down ～", meaning: "(金額)を手付金として払う、～を書き留める" },
  { word: "put forth ～", meaning: "(力など)を発揮する、(計画・案など)を提出する" },
  { word: "put toward ～", meaning: "～を提案[提出]する" },
  { word: "put in ～", meaning: "(設備など)を備え付ける、(金・時間・精力など)をつぎ込む" },
  { word: "put A through (to B)", meaning: "Aの電話を(Bに)つなぐ" },
  { word: "read off ～", meaning: "(リストなど)を読み上げる" },
  { word: "refrain from doing ～", meaning: "～するのを控える、～するのをやめる" },
  { word: "regardless of ～", meaning: "～に(も)かかわらず、～にかまわず" },
  { word: "roll in (～)", meaning: "(金など)がたくさんある、転がり込む、どっと集まる" },
  { word: "roll up ～", meaning: "～をくるくると巻く、(そで・すそ)をまくり上げる" },
  { word: "round off ～", meaning: "～を締めくくる、～をうまく終える" },
  { word: "round up ～", meaning: "(散らばった人など)を集める、～を逮捕する" },
  { word: "rule out ～", meaning: "～を排除する、～を除外する" },
  { word: "run against ～", meaning: "～に不利になる" },
  { word: "run down ～", meaning: "(車・運転手が)～をひく、～のことを悪く言う、～を突き止める" },
  { word: "run through ～", meaning: "ざっと～を読み上げる[に目を通す]" },
  { word: "scoop up ～", meaning: "～を抱き上げる、～をすくい上げる" },
  { word: "scratch out ～", meaning: "～を削除する、やっと(生計)を立てる" },
  { word: "see about ～", meaning: "～を検討する、～を手配する、～を何とかする" },
  { word: "see A off", meaning: "(空港・駅などで)Aを見送る" },
  { word: "see through ～", meaning: "～を見抜く、～を見破る、～を通して見る" },
  { word: "sell out", meaning: "(期待を)裏切る、(ものが)売り切れる" },
  { word: "send for ～", meaning: "(人・助けなど)を呼ぶ、～に来てもらう" },
  { word: "send out for ～", meaning: "(食べ物)の出前を頼む" },
  { word: "set aside ～", meaning: "(時間・金など)をとっておく、～をわきへどける" },
  { word: "set down ～", meaning: "～を書き留める" },
  { word: "set in", meaning: "(季節・流行・好ましくないものなどが)始まる、起こる" },
  { word: "set off (～)", meaning: "出発する、～を引き起こす、～を作動させる" },
  { word: "set out to do ～", meaning: "～することに着手する、～し始める" },
  { word: "set up ～", meaning: "(会合など)を準備する、～を設置する、(会社・組織など)を作る" },
  { word: "settle down", meaning: "ゆったりとくつろぐ、落ち着く、定住する" },
  { word: "settle up (with ～)", meaning: "(～と)精算する、(～に)勘定を支払う" },
  { word: "shake up ～", meaning: "～を刷新する、～を動揺させる、～を奮い立たせる" },
  { word: "show off (～)", meaning: "いいところを見せる、～を見せびらかす" },
  { word: "show up", meaning: "現れる、やってくる" },
  { word: "sign up for ～", meaning: "(署名して)～に参加する、(受講など)の届けを出す" },
  { word: "single out ～", meaning: "～を(特に)選び出す" },
  { word: "sink in", meaning: "十分に理解される、分かってもらう" },
  { word: "sit back", meaning: "何もしないで[手をこまねいて]いる、くつろぐ、(いすに)深く座る" },
  { word: "sit by", meaning: "(悪い事態を)黙って見ている、傍観する" },
  { word: "sit in", meaning: "参加する、見学[参観]する、代理を務める" },
  { word: "skim over ～", meaning: "～をざっと見る、～表面的に扱う" },
  { word: "slip by", meaning: "(時・機会が)いつの間にか過ぎる" },
  { word: "smooth over ～", meaning: "(話し合いをして)(問題・困難など)を処理しやすくする" },
  { word: "speak for ～", meaning: "～を代表して意見を述べる、～を代弁する、～への支持を表明する" },
  { word: "split up (～)", meaning: "別れる、分裂する、～を分裂させる" },
  { word: "spring from ～", meaning: "～から生じる、(人が)～の出である" },
  { word: "spring up", meaning: "急に生まれる、急成長する" },
  { word: "stand down (as ～)", meaning: "(公職など)を辞任する" },
  { word: "stand for ～", meaning: "～の略である、～を意味する、～を支持する" },
  { word: "stand up to ～", meaning: "～に抵抗する、～に立ち向かう、～に耐える" },
  { word: "stay off ～", meaning: "(健康のため)～を控える、～に近づかない" },
  { word: "step down [aside]", meaning: "辞任する" },
  { word: "stick around", meaning: "そこらで待つ、帰らずにいる" },
  { word: "stick to [by] ～", meaning: "(主義など)を堅持する、～をやり続ける" },
  { word: "stick up for ～", meaning: "～をあくまでも擁護する、～を支持する" },
  { word: "stick with ～", meaning: "～を最後までやり抜く、～を続けてする" },
  { word: "stir in ～", meaning: "～を入れてかき混ぜる" },
  { word: "stir up ～", meaning: "(騒ぎなど)を引き起こす、(想像力・記憶など)をかき立てる" },
  { word: "sum up ～", meaning: "～を要約する" },
  { word: "take in ～", meaning: "～を摂取する、(光景など)を観察する、～をだます、～を理解する" },
  { word: "tale on ～", meaning: "(特にきつい仕事・責任)を引き受ける" },
  { word: "take over ～", meaning: "～を引き継ぐ、～を買収する、～を占領する" },
  { word: "take up ～", meaning: "～を趣味[職業・学問]として始める、(問題など)を取り上げる" },
  { word: "talk down to A", meaning: "Aを見下した調子で話す" },
  { word: "talk A into doing ～", meaning: "Aを説得して～させる" },
  { word: "talk up ～", meaning: "(人・もの)を実際以上に興味深いもののように話す" },
  { word: "tear down ～", meaning: "～を取り壊す、～を解体する、～を殴り倒す" },
  { word: "tell on ～", meaning: "(特に子供が)～のことを告げ口する、～にこたえる" },
  { word: "the other way around", meaning: "(方角・事情などが)逆に[で]" },
  { word: "throw off ～", meaning: "(衣服など)をさっと脱ぐ[脱ぎ捨てる]、～を払いのける" },
  { word: "throw up (～)", meaning: "嘔吐する、(食べ物)を吐く" },
  { word: "tidy up ～", meaning: "(部屋・家・机など)を片付ける、～を整理する" },
  { word: "tie up ～", meaning: "忙しくて身動きできない、～を固く縛る" },
  { word: "tip over (～)", meaning: "ひっくり返る、倒れる、～をひっくり返す" },
  { word: "touch up ～", meaning: "(絵・文章・化粧など)を手直しする、～を修正する" },
  { word: "track down ～", meaning: "～を追跡して捕らえる、～を追い詰める" },
  { word: "trip up (A)", meaning: "Aをつまずかせる、つまずく、しくじる" },
  { word: "try out ～", meaning: "～を試してみる、～の効果を試す" },
  { word: "tune in (to ～)", meaning: "(局・番組などに)テレビ[ラジオ]のチャンネルを合わせる" },
  { word: "tune up (～)", meaning: "(楽器)を調律する、(エンジン・機械など)を整備する、調律する" },
  { word: "turn around (～)", meaning: "(商売・経済など)を好転させる、～の向きを変える、好転する" },
  { word: "turn away ～", meaning: "～を追い払う、(客など)の入場を断る、～を背ける" },
  { word: "turn in (～)", meaning: "～を提出する、寝る" },
  { word: "turn out", meaning: "であることがわかる、集まる" },
  { word: "turn to ～", meaning: "～に頼る、(犯罪・悪習など)に走る、～に取りかかる" },
  { word: "walk off [away] with ～", meaning: "～を盗む、(賞など)をあっさり手に入れる" },
  { word: "wander off", meaning: "はぐれる、(道路・場所から)外れる、(主題から)脱線する" },
  { word: "want for ～", meaning: "～を欠いている" },
  { word: "wash away ～", meaning: "～を洗い流す、(記憶・感情など)を洗い去る" },
  { word: "wash down ～", meaning: "(食べ物など)を流し込む、～を洗い流す" },
  { word: "watch over ～", meaning: "～の世話をする、～を見守る、～を監視する" },
  { word: "wear off", meaning: "(薬効・印象・痛みなどが)しだいに弱まる、すり減ってなくなる" },
  { word: "wear out ～", meaning: "～を疲れ果てさせる" },
  { word: "weigh on ～", meaning: "～に重くのしかかる、～を圧迫する、～を苦しめる" },
  { word: "win over ～", meaning: "～を説得する" },
  { word: "wipe out ～", meaning: "～を消滅[絶滅]させる、～を撲滅する" },
  { word: "work out ～", meaning: "(計画・対策など)を練る、(問題)を解決する、～を計算する" },
  { word: "wrap up ～", meaning: "(仕事・交渉など)を滞りなく終える" }
];
export default words;